'use client'
import {useEffect,useId,useRef,useState} from 'react'
import {executeMarketQuestion} from '@/lib/market-inventory-action'
import {saveMarketComparison,createMarketComparisonName} from '@/lib/market-comparisons'
import FilterSelect from '../market-filters/FilterSelect'
import {priceRangeOptions} from '../market-filters/options'
import {applyFilterChange,optionLabel,optionValue} from '../market-filters/utils'
import type {ExplorerOptions,Filters,Language} from '../market-filters/types'
import {summaryKeys,summarySnapshot,summaryIdentity,summaryLabel,summaryOptions,summaryOptionMatches,type SummaryKey} from '../market-summary/contract'
import {dimensionLabel} from '../market-composition/contract'
import {comparisonQuestion,pairWidths,type ComparisonResult,type ComparisonSide,type Metric} from './contract'
import shared from '../market-summary/workspace.module.css'
import styles from './comparison.module.css'
const keys=[...summaryKeys,'price_range'] as const
function side(filters:Filters,prefix:'a'|'b'):Filters{return Object.fromEntries(keys.filter(k=>filters[`${prefix}_${k}`]).map(k=>[k,filters[`${prefix}_${k}`]]))}
function prefixed(a:Filters,b:Filters):Filters{return Object.fromEntries([['a',a],['b',b]].flatMap(([p,f])=>keys.filter(k=>(f as Filters)[k]).map(k=>[`${p}_${k}`,(f as Filters)[k]])))}
type Commit={a:Filters;b:Filters;labels:string[][];result:ComparisonResult}
export default function MarketComparison({options,filters,language='en'}:{options:ExplorerOptions;filters:Filters;language?:Language}){
 const es=language==='es',id=useId(),market=(i:number)=>`${es?'Mercado':'Market'} ${i===0?'A':'B'}`
 const [a,setA]=useState(()=>side(filters,'a')),[b,setB]=useState(()=>side(filters,'b'))
 const [committed,setCommitted]=useState<Commit|null>(null),[expanded,setExpanded]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[saveStatus,setSaveStatus]=useState('')
 const generation=useRef(0),busy=useRef(false),saving=useRef(false),heading=useRef<HTMLHeadingElement>(null),inputHeading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>()=>{generation.current++},[])
 useEffect(()=>{if(committed)heading.current?.focus()},[committed])
 const identity=JSON.stringify(prefixed(side(filters,'a'),side(filters,'b'))),previous=useRef(identity)
 useEffect(()=>{if(previous.current!==identity){previous.current=identity;generation.current++;busy.current=false;setPending(false);setA(side(filters,'a'));setB(side(filters,'b'));setExpanded(true);setError('')}},[identity,filters])
 function labels(f:Filters){const values=summaryIdentity(summarySnapshot(f),options,language);if(f.price_range){const option=priceRangeOptions.find(o=>optionValue(o)===f.price_range);if(!option)throw Error('Unavailable range');values.push(`${es?'Rango de precio de oferta (CRC)':'Asking-price range (CRC)'}: ${optionLabel(option,language)}`)}return values}
 function field(key:typeof keys[number],index:number){
  const draft=index===0?a:b,set=index===0?setA:setB,choices=key==='price_range'?priceRangeOptions:summaryOptions(key,options,language,draft)
  const matches=(o:typeof choices[number],v:string)=>key==='price_range'?optionValue(o)===v:summaryOptionMatches(key,o,v)
  const selected=draft[key]?.split(',').map(v=>choices.find(o=>matches(o,v))),unavailable=selected?.some(o=>!o)
  const restored=unavailable?[{slug:draft[key],term_name:es?'Selección no disponible — selecciona de nuevo':'Selection unavailable — choose again'},...choices]:selected?.length&&!choices.some(o=>optionValue(o)===draft[key])?[{slug:draft[key],term_name:selected.map(o=>optionLabel(o!,language)).join(' / ')},...choices]:choices
  const label=key==='price_range'?(es?'Rango de precio de oferta (CRC)':'Asking-price range (CRC)'):summaryLabel(key,language)
  return <FilterSelect key={key} compact label={label} accessibleLabel={`${market(index)} · ${label}`} filterKey={key} options={restored} filters={draft} language={language} emptyLabel={es?'Sin restricción':'Any'} onFilterChange={(k,v)=>{set(current=>k==='accessibility'?{...current,[k]:v||undefined}:applyFilterChange(current,k,v));setError('')}}/>
 }
 async function apply(){if(busy.current)return;const left={...a},right={...b};let names:string[][];try{names=[labels(left),labels(right)]}catch{setError(es?'Revisa las selecciones no disponibles.':'Review unavailable input selections.');return}const ticket=++generation.current;busy.current=true;setPending(true);setError('');try{const result=await executeMarketQuestion('comparison',prefixed(left,right),language) as ComparisonResult;if(ticket!==generation.current)return;setCommitted({a:left,b:right,labels:names,result});setExpanded(false);setSaveStatus('')}catch{if(ticket===generation.current)setError(es?'No se pudo completar la comparación. Se conserva el resultado anterior.':'Comparison could not be completed. The previous result is retained.')}finally{if(ticket===generation.current){busy.current=false;setPending(false)}}}
 async function save(){if(!committed||saving.current)return;saving.current=true;setSaveStatus('saving');const snapshot=committed,ticket=generation.current;try{const f=prefixed(snapshot.a,snapshot.b);await saveMarketComparison({name:createMarketComparisonName({filters:f,language}),filters:f,result:snapshot.result,language});if(ticket===generation.current)setSaveStatus(es?'Guardado':'Saved')}catch{if(ticket===generation.current)setSaveStatus(es?'No se pudo guardar':'Could not save')}finally{saving.current=false}}
 const number=new Intl.NumberFormat(es?'es-CR':'en-US',{maximumFractionDigits:2}),missing=es?'No establecido':'Not established'
 function pair(title:string,metric:Metric,formatted:(s:ComparisonSide)=>string|null,secondary?:(s:ComparisonSide)=>string|null){if(!committed)return null;const sides=[committed.result.left,committed.result.right],widths=pairWidths(sides[0].metrics?.[metric],sides[1].metrics?.[metric]);return <div className={styles.pair} data-metric={metric}><h5>{title}</h5><div className={styles.values}>{sides.map((s,i)=><div className={styles.value} key={i}><p>{market(i)}</p><strong>{formatted(s)??missing}</strong>{secondary&&secondary(s)&&<p>{secondary(s)}</p>}{widths[i]!==null&&<div className={styles.track} aria-hidden="true"><div className={styles.fill} data-value={s.metrics?.[metric]} style={{width:`${widths[i]}%`}}/></div>}</div>)}</div></div>}
 const sides=committed?[committed.result.left,committed.result.right]:[]
 const lens=(key:string,title:string,question:string,children:React.ReactNode)=><section className={styles.lens} aria-labelledby={`${id}-${key}`}><h3 id={`${id}-${key}`}>{title}</h3><p className={shared.sectionQuestion}>{question}</p>{children}</section>
 return <article className={shared.summary} aria-label={es?'Comparación de mercados':'Market Comparison'}>
  <header className={shared.introduction}><p className={shared.eyebrow}>{es?'Fundamentos del mercado':'Market fundamentals'}</p><h2>{es?'Comparación de mercados':'Market Comparison'}</h2><p className={shared.primaryQuestion}>{comparisonQuestion[language]}</p></header>
  {committed&&<section className={styles.definitions} aria-label={es?'Mercados analizados':'Analyzed markets'}><div className={styles.markets}>{sides.map((s,i)=><div key={i} className={styles.market}><h3>{market(i)}</h3><ul>{committed.labels[i].map((l,j)=><li key={j}>{l}</li>)}</ul><p className={styles.population}>n = {number.format(s.sampleSize)} · {es?'anuncios en la población':'listings in population'}</p></div>)}</div><button className={shared.modify} style={{marginTop:16}} disabled={pending} aria-expanded={expanded} aria-controls={`${id}-inputs`} onClick={()=>{setExpanded(v=>!v);if(!expanded)requestAnimationFrame(()=>inputHeading.current?.focus())}}>{expanded?(es?'Cerrar edición':'Close editing'):(es?'Modificar':'Modify')}</button></section>}
  <section id={`${id}-inputs`} className={shared.inputs} hidden={!expanded}><h3 tabIndex={-1} ref={inputHeading}>{es?'Definir los dos mercados':'Define both markets'}</h3><fieldset className={shared.fieldset} disabled={pending}><legend className={shared.srOnly}>{es?'Datos de comparación':'Comparison inputs'}</legend><div className={styles.markets}>{[0,1].map(i=><section className={styles.market} key={i} aria-label={`${market(i)} ${es?'datos':'inputs'}`}><h3>{market(i)}</h3><div className={shared.inputGrid}>{summaryKeys.slice(0,5).map(k=>field(k,i))}{field('price_range',i)}</div><details className={shared.optional}><summary>{es?'Características y medidas opcionales':'Optional characteristics and measurements'}</summary><div className={shared.inputGrid}>{summaryKeys.slice(5).map(k=>field(k,i))}</div></details></section>)}</div><button className={shared.apply} style={{marginTop:20}} onClick={apply} disabled={pending}>{pending?(es?'Comparando…':'Comparing…'):(es?'Comparar mercados':'Compare markets')}</button></fieldset></section>
  {pending&&<p role="status">{es?'Comparando los mercados…':'Comparing markets…'}</p>}{error&&<p role="alert" className={shared.error}>{error}</p>}
  {committed&&<div aria-live="polite" aria-busy={pending}>
   <h3 ref={heading} tabIndex={-1} style={{marginTop:28}}>{es?'Comparación establecida':'Established comparison'}</h3>
   <p className={styles.note}>{es?'n describe toda la población de cada mercado. El resultado actual no incluye los conteos de observaciones válidas de cada estadística de precio o área; no se sustituyen por n.':'n describes each entire market population. The current result does not include valid-observation counts for individual price or area statistics; population n is not substituted for them.'}</p>
   {sides.some(s=>s.sampleSize===0)&&<p role="status">{es?'Una población vacía es un resultado completo. Sus estadísticas no están establecidas.':'An empty population is a complete result. Its statistics are not established.'}</p>}
   {lens('prices',es?'Precios de oferta':'Asking prices',es?'¿Cómo difieren los precios de oferta entre los dos mercados definidos?':'How do asking prices differ between the two defined markets?',<>
    <h4>{es?'Venta · precio total · CRC / USD':'Sale · total asking price · CRC / USD'}</h4>{pair(es?'Media':'Mean','averageSalePrice',s=>s.averageSalePriceCRC,s=>s.averageSalePriceUSD)}{pair(es?'Mediana':'Median','medianSalePrice',s=>s.medianSalePriceCRC,s=>s.medianSalePriceUSD)}
    <h4>{es?'Alquiler · precio mensual · CRC / USD':'Rent · monthly asking price · CRC / USD'}</h4>{pair(es?'Media mensual':'Monthly mean','averageRent',s=>s.averageRentCRC,s=>s.averageRentUSD)}{pair(es?'Mediana mensual':'Monthly median','medianRent',s=>s.medianRentCRC,s=>s.medianRentUSD)}<p className={styles.note}>{es?'Cada par de barras parte de cero y comparte una escala en CRC. Venta y alquiler mensual nunca comparten escala. USD es la presentación alternativa del mismo contexto cambiario.':'Each bar pair starts at zero and shares one CRC scale. Sale and monthly Rent never share a scale. USD is the alternative presentation from the same FX context.'}</p>
   </>)}
   {lens('property-area',es?'Área de la propiedad':'Property area',es?'¿Cómo difiere el área media de la propiedad entre los dos mercados definidos?':'How does mean property area differ between the two defined markets?',pair(es?'Media · m²':'Mean · m²','averagePropertyArea',s=>s.averagePropertyArea))}
   {lens('construction-area',es?'Área de construcción':'Construction area',es?'¿Cómo difiere el área media de construcción entre los dos mercados definidos?':'How does mean construction area differ between the two defined markets?',pair(es?'Media · m²':'Mean · m²','averageConstructionArea',s=>s.averageConstructionArea))}
   {lens('characteristics',es?'Características canónicas':'Canonical characteristics',es?'¿Cómo difieren las membresías registradas y su prevalencia entre los dos mercados definidos?':'How do recorded memberships and their prevalence differ between the two defined markets?',<>
    <p className={styles.note}>{es?'Las barras comparten una escala fija de 0 a 100% de la población de cada mercado. No implican presencia o ausencia real cuando falta evidencia.':'Bars share a fixed 0–100% scale of each market population. They do not imply real-world presence or absence where evidence is missing.'}</p>
    {Array.from(new Set(sides.flatMap(s=>s.prevalence.dimensions.map(d=>d.dimension)))).map(dimension=>{const dims=sides.map(s=>s.prevalence.dimensions.find(d=>d.dimension===dimension));const terms=Array.from(new Map(dims.flatMap(d=>(d?.terms??[]).map(t=>[t.termId,t] as const))).values());return <section key={dimension}><h4>{dimensionLabel(dimension,language)}</h4><div className={styles.values}>{dims.map((d,i)=><div key={i} className={styles.coverage}><b>{market(i)}</b><p>{es?'Con evidencia registrada':'With recorded evidence'}: {d?.representedN??missing} / {d?.denominatorN??missing}</p><p>{es?'Sin evidencia registrada':'Without recorded evidence'}: {d?.unrepresentedN??missing}</p><p>{es?'Categoría de mayor conteo':'Leading category by count'}: {d?.terms[0]?.label[language]??missing}</p></div>)}</div>{terms.length===0&&<p>{es?'No se devolvieron membresías registradas.':'No recorded memberships returned.'}</p>}{terms.map(t=><div className={styles.pair} key={t.termId} data-term-id={t.termId}><h5>{t.label[language]}</h5><div className={styles.values}>{dims.map((d,i)=>{const found=d?.terms.find(v=>v.termId===t.termId);return <div key={i} className={styles.value}><p>{market(i)}</p>{found?<><strong>{found.count} {es?'anuncios':'listings'} · {found.percentage===null?missing:`${number.format(found.percentage)}%`}</strong>{found.percentage!==null&&<div className={styles.track} aria-hidden="true"><div className={styles.fill} style={{width:`${found.percentage}%`}}/></div>}</>:<p>{es?'Sin membresía devuelta para este término':'No returned membership for this term'}</p>}</div>})}</div></div>)}</section>})}
   </>)}
   <details className={shared.method}><summary>{es?'Metodología':'Methodology'}</summary><p>{es?'Cada mercado se adquiere por separado bajo sus filtros canónicos. Las selecciones de una dimensión usan OR; las dimensiones usan AND. Las restricciones numéricas requieren evidencia coincidente.':'Each market is acquired separately under its canonical filters. Selections within one dimension use OR; dimensions use AND. Numerical constraints require matching evidence.'}</p><p>{es?'Las estadísticas usan evidencia válida. La media y la mediana no estiman valor justo ni esperado. Los importes y áreas textuales se redondean según el motor; las barras usan los valores numéricos establecidos antes del formato. Cada par de áreas comparte una escala desde cero.':'Statistics use valid evidence. Mean and median do not estimate fair or expected value. Amounts and areas follow the engine’s rounded text formatting; bars use its established numbers before formatting. Each area pair shares a zero-based scale.'}</p><p>{es?'La prevalencia usa anuncios distintos con membresía registrada y toda la población como denominador. Varias membresías pueden sumar más del 100%. Los términos se alinean por identidad canónica; una etiqueta no establece identidad.':'Prevalence uses distinct listings with recorded membership and the entire population as denominator. Multiple memberships may sum above 100%. Terms align by canonical identity; labels do not establish identity.'}</p><p>{es?'Las diferencias observadas no establecen causas, recomendaciones ni ganadores. No se calculan diferencias firmadas ni porcentuales entre A y B.':'Observed differences establish no causes, recommendations or winners. Signed and percentage differences between A and B are not calculated.'}</p></details>
   <div className={styles.save}><button className={shared.modify} disabled={saveStatus==='saving'||pending} onClick={save}>{es?'Guardar comparación':'Save comparison'}</button><p role="status">{saveStatus==='saving'?(es?'Guardando…':'Saving…'):saveStatus}</p></div>
  </div>}
 </article>
}
