'use client'
import {useEffect,useRef,useState} from 'react'
import {readCampaigns,campaignOptions,changeCampaign,campaignPerformance} from './campaign-actions'
import {campaignSurfaces,type Campaign,type CampaignConfiguration,type Creative} from '@/lib/campaign-contract'
import '../components/campaigns.css'
type CreativeRow={id:string;revision:string;versionId:string;payload:Creative}
type Target={id:string;name:string;name_es?:string}
const emptyCreative:Creative={headline_en:'',headline_es:'',copy_en:'',copy_es:'',cta_en:'Learn more',cta_es:'Más información',destination_en:'/en',destination_es:'/es',alt_en:'',alt_es:'',image:null,video:null}
export default function AdminPromotions({language,manage}:{language:'en'|'es';manage:boolean}){
 const es=language==='es',t=(a:string,b:string)=>es?b:a
 const [rows,setRows]=useState<Campaign[]>([]),[state,setState]=useState(''),[after,setAfter]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [draft,setDraft]=useState<Campaign|null>(null),[kind,setKind]=useState('TWUANIS'),[targets,setTargets]=useState<Target[]>([]),[creativeRows,setCreativeRows]=useState<CreativeRow[]>([]),[creative,setCreative]=useState<CreativeRow|null>(null),[performance,setPerformance]=useState<Record<string,unknown>[]>([]),[reason,setReason]=useState('')
 const baseline=useRef(''),retry=useRef<{body:string;id:string}|null>(null),mediaRetry=useRef<{file:File;id:string}|null>(null)
 const dirty=JSON.stringify(draft??creative??null)!==baseline.current&&!!(draft||creative)
 useEffect(()=>{function unload(e:BeforeUnloadEvent){if(dirty||busy)e.preventDefault()}function leave(e:Event){if(busy||(dirty&&!window.confirm(t('Discard unsaved changes?','¿Descartar cambios sin guardar?'))))e.preventDefault()}window.addEventListener('admin-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('admin-leave',leave);window.removeEventListener('beforeunload',unload)}},[dirty,busy,es])
 async function load(cursor:string|null=null){setBusy(true);const r=await readCampaigns(cursor,state||null);if(r.ok){setRows(r.data);setAfter(cursor)}else setMessage(t('Campaigns unavailable.','Campañas no disponibles.'));setBusy(false)}
 async function loadCreatives(cursor:string|null=null){const r=await campaignOptions('CREATIVE',cursor);if(r.ok)setCreativeRows(r.data)}
 useEffect(()=>{void load()},[state])
 useEffect(()=>{void loadCreatives()},[])
 useEffect(()=>{let live=true;setTargets([]);void campaignOptions(kind).then(r=>{if(live&&r.ok)setTargets(r.data)});return()=>{live=false}},[kind])
 const targetLabels:Record<string,string>={TWUANIS:'Twuanis',PACKAGE:t('Package','Paquete'),ADD_ON:t('Add-on','Complemento'),OFFER:t('Offer','Oferta'),ENGINE:t('Engine','Motor')}
 const surfaceLabels:Record<string,string>={homepage:t('Homepage','Página de inicio'),banner:t('Banner','Franja'),popup:t('Popup','Ventana emergente'),package:t('Package page','Página de paquetes'),'intelligence-hub':t('Intelligence Hub','Centro de inteligencia'),'market-hub':t('Market Hub','Centro de mercado')}
 const labels:Record<string,string>={draft:t('Draft','Borrador'),scheduled:t('Scheduled','Programada'),active:t('Active','Activa'),paused:t('Paused','Pausada'),ended:t('Ended','Finalizada'),archived:t('Archived','Archivada')}
 async function send(body:Record<string,unknown>){const text=JSON.stringify(body);if(retry.current?.body!==text)retry.current={body:text,id:crypto.randomUUID()};setBusy(true);const r=await changeCampaign(retry.current.id,body);setBusy(false);if(r.ok){retry.current=null;setDraft(null);setCreative(null);setPerformance([]);setReason('');baseline.current='';await load();await loadCreatives();setMessage(t('Saved.','Guardado.'))}else setMessage(r.code==='stale'?t('Changed elsewhere. Reload before editing.','Cambió en otra sesión. Vuelva a cargar.'):t('Could not save. Check inputs. Retry keeps the same request.','No se pudo guardar. Revise los datos. El reintento conserva la solicitud.'))}
 function save(op:string){if(!draft)return;if(!['create','configure'].includes(op)&&dirty){setMessage(t('Save or discard edits first.','Guarde o descarte los cambios primero.'));return}void send({operation:op,reason,...(draft.id?{id:draft.id,expected:draft.revision}:{targetClass:kind,targetId:draft.targetId}),...(['create','configure'].includes(op)?{configuration:draft.configuration}:{})})}
 function cfg<K extends keyof CampaignConfiguration>(key:K,value:CampaignConfiguration[K]){if(draft)setDraft({...draft,configuration:{...draft.configuration,[key]:value}})}
 const localDate=(s:string)=>s&&Number.isFinite(Date.parse(s))?new Date(Date.parse(s)-21600000).toISOString().slice(0,19):''
 async function upload(file:File,field:'image'|'video'){if(!creative)return;if(mediaRetry.current?.file!==file)mediaRetry.current={file,id:crypto.randomUUID()};const f=new FormData();f.set('file',file);f.set('request',mediaRetry.current.id);setBusy(true);try{const r=await fetch('/api/campaign-media',{method:'POST',body:f});const result=await r.json();if(!r.ok||!result.ok)throw Error();setCreative({...creative,payload:{...creative.payload,[field]:result.id}});mediaRetry.current=null;setMessage(t('Media prepared. Save the creative to use it.','Medio preparado. Guarde el creativo para usarlo.'))}catch{setMessage(t('Upload incomplete. Retrying this file retains its identity; uncertain files are not deleted.','Carga incompleta. El reintento conserva la identidad; no se eliminan archivos inciertos.'))}finally{setBusy(false)}}
 function back(){if(!dirty||window.confirm(t('Discard unsaved changes?','¿Descartar cambios sin guardar?'))){setDraft(null);setCreative(null);baseline.current='';setPerformance([])}}
 return <div className="admin-campaigns"><p>{t('Campaigns market Twuanis. They do not change prices, rights or analytics.','Las campañas promocionan Twuanis. No cambian precios, derechos ni análisis.')}</p><p role="status">{message}</p>
 {!draft&&!creative?<><label>{t('Status','Estado')}<select value={state} onChange={e=>setState(e.target.value)}><option value="">{t('All','Todos')}</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button disabled={busy} onClick={()=>void load()}>{t('Refresh','Actualizar')}</button>{manage&&<><button onClick={()=>{const d:Campaign={id:'',revision:'',state:'draft',targetClass:'TWUANIS',targetId:'',configuration:{name:'',creativeVersion:'',surfaces:[],audience:'ALL',startsAt:'',endsAt:'',frequency:1,priority:0,external:[]}};setKind('TWUANIS');baseline.current=JSON.stringify(d);setDraft(d)}}>{t('Create Campaign','Crear campaña')}</button><button onClick={()=>{const c={id:'',revision:'',versionId:'',payload:{...emptyCreative}};baseline.current=JSON.stringify(c);setCreative(c)}}>{t('Create creative','Crear creativo')}</button></>}
 <div className="campaign-grid">{rows.slice(0,25).map(c=><article className="admin-card" key={c.id}><h3>{c.configuration.name}</h3><p>{c.targetClass} · {c.targetId}</p><p>{labels[c.state]}</p><button onClick={()=>{baseline.current=JSON.stringify(c);setDraft(structuredClone(c));setKind(c.targetClass);void campaignPerformance(c.id).then(r=>{if(r.ok)setPerformance(r.data)})}}>{t('Inspect / edit','Inspeccionar / editar')}</button></article>)}</div>{!rows.length&&!busy&&<p>{t('No campaigns.','No hay campañas.')}</p>}{after&&<button onClick={()=>void load()}>{t('First page','Primera página')}</button>}{rows.length>25&&<button onClick={()=>void load(rows[24].id)}>{t('Next page','Página siguiente')}</button>}
 <h3>{t('Reusable creatives','Creativos reutilizables')}</h3>{creativeRows.slice(0,25).map(c=><button key={c.id} onClick={()=>{baseline.current=JSON.stringify(c);setCreative(structuredClone(c))}}>{es?c.payload.headline_es:c.payload.headline_en}</button>)}{creativeRows.length>25&&<button onClick={()=>void loadCreatives(creativeRows[24].id)}>{t('More creatives','Más creativos')}</button>}
 </>:<button disabled={busy} onClick={back}>{t('Back','Volver')}</button>}
 {creative&&<form onSubmit={e=>{e.preventDefault();void send({operation:creative.id?'creative.configure':'creative.create',...(creative.id?{id:creative.id,expected:creative.revision}:{}),creative:creative.payload})}}><fieldset disabled={busy||!manage}><legend>{t('Creative — immutable new version','Creativo — nueva versión inmutable')}</legend><p>{t('Changes do not replace versions already used by Campaigns. Select the new version explicitly.','Los cambios no reemplazan versiones ya usadas. Seleccione la nueva versión explícitamente.')}</p>
 {(['headline','copy','cta','destination','alt'] as const).flatMap(k=>(['en','es'] as const).map(lang=>{const key=`${k}_${lang}` as keyof Creative;const label=({headline:t('Headline','Titular'),copy:t('Copy','Texto'),cta:t('CTA label','Etiqueta CTA'),destination:t('Information route','Ruta informativa'),alt:t('Media description','Descripción del medio')})[k];return <label key={key}>{label} {lang.toUpperCase()}<input required={!['copy','alt'].includes(k)} maxLength={k==='copy'?2000:300} value={creative.payload[key]??''} onChange={e=>setCreative({...creative,payload:{...creative.payload,[key]:e.target.value}})}/></label>}))}
 <p>{t('JPEG ≤600 KB; MP4 ≤4 MB. System-owned Campaign media only; no listing media or external imports.','JPEG ≤600 KB; MP4 ≤4 MB. Medios de campaña del sistema; sin medios de propiedades ni importaciones externas.')}</p>
 {(['image','video'] as const).map(k=><label key={k}>{k==='image'?t('Image','Imagen'):t('Video','Video')}<input type="file" accept={k==='image'?'image/jpeg':'video/mp4'} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,k)}}/>{creative.payload[k]&&<><code>{creative.payload[k]}</code><button type="button" onClick={()=>setCreative({...creative,payload:{...creative.payload,[k]:null}})}>{t('Remove from this version','Quitar de esta versión')}</button></>}</label>)}{mediaRetry.current&&<button type="button" onClick={()=>void upload(mediaRetry.current!.file,mediaRetry.current!.file.type==='image/jpeg'?'image':'video')}>{t('Retry media upload','Reintentar carga')}</button>}<button type="submit">{t('Save creative','Guardar creativo')}</button></fieldset></form>}
 {draft&&<><form onSubmit={e=>{e.preventDefault();save(draft.id?'configure':'create')}}><fieldset disabled={busy||!manage||['ended','archived'].includes(draft.state)}>
 {!draft.id&&<><label>{t('Target class','Clase de destino')}<select value={kind} onChange={e=>{setKind(e.target.value);setDraft({...draft,targetClass:e.target.value,targetId:''})}}>{['TWUANIS','PACKAGE','ADD_ON','OFFER','ENGINE'].map(k=><option key={k} value={k}>{targetLabels[k]}</option>)}</select></label><p>{t('Feature targets unavailable until canonical Feature authority exists.','Los destinos de función no están disponibles hasta que exista autoridad canónica.')}</p><label>{t('Canonical target','Destino canónico')}<select required value={draft.targetId} onChange={e=>setDraft({...draft,targetId:e.target.value})}><option value="">{t('Choose','Seleccione')}</option>{targets.slice(0,25).map(x=><option key={x.id} value={x.id}>{es?(x.name_es??x.name):x.name}</option>)}</select></label>{targets.length>25&&<button type="button" onClick={()=>void campaignOptions(kind,targets[24].id).then(r=>{if(r.ok)setTargets(r.data)})}>{t('More targets','Más destinos')}</button>}</>}
 <label>{t('Campaign name','Nombre de campaña')}<input required maxLength={300} value={draft.configuration.name} onChange={e=>cfg('name',e.target.value)}/></label><label>{t('Creative version','Versión del creativo')}<select required value={draft.configuration.creativeVersion} onChange={e=>cfg('creativeVersion',e.target.value)}><option value="">{t('Choose','Seleccione')}</option>{draft.configuration.creativeVersion&&!creativeRows.some(c=>c.versionId===draft.configuration.creativeVersion)&&<option value={draft.configuration.creativeVersion}>{t('Existing pinned version','Versión existente fijada')}</option>}{creativeRows.map(c=><option key={c.versionId} value={c.versionId}>{es?c.payload.headline_es:c.payload.headline_en} · v{c.revision}</option>)}</select></label>
 {creativeRows.length>25&&<button type="button" onClick={()=>void loadCreatives(creativeRows[24].id)}>{t('More creatives','Más creativos')}</button>}<fieldset><legend>{t('Owned placements','Ubicaciones propias')}</legend>{campaignSurfaces.map(s=><label key={s}><input type="checkbox" checked={draft.configuration.surfaces.includes(s)} onChange={e=>cfg('surfaces',e.target.checked?[...draft.configuration.surfaces,s]:draft.configuration.surfaces.filter(x=>x!==s))}/>{surfaceLabels[s]}</label>)}</fieldset>
 <label>{t('Audience','Audiencia')}<select value={draft.configuration.audience} onChange={e=>cfg('audience',e.target.value as CampaignConfiguration['audience'])}><option value="ALL">{t('All visitors','Todos los visitantes')}</option><option value="AUTHENTICATED">{t('Authenticated','Autenticados')}</option><option value="UNAUTHENTICATED">{t('Unauthenticated','No autenticados')}</option></select></label>
 <p>{t('Costa Rica time. End is exclusive.','Hora de Costa Rica. El fin es exclusivo.')}</p>{(['startsAt','endsAt'] as const).map(k=><label key={k}>{k==='startsAt'?t('Starts','Inicio'):t('Ends','Fin')}<input type="datetime-local" step="1" required value={localDate(draft.configuration[k])} onChange={e=>cfg(k,e.target.value?e.target.value+'-06:00':'')}/></label>)}
 <label>{t('Maximum deliveries per browser session (up to 24 hours)','Máximo de entregas por sesión del navegador (hasta 24 horas)')}<input type="number" min={1} max={20} required value={draft.configuration.frequency} onChange={e=>cfg('frequency',Number(e.target.value))}/></label><p>{t('Delivery limits are conservative; an unviewed delivery still uses a slot. Impressions count only browser-reported visibility. Dismissal suppresses this Campaign for the session.','Los límites son conservadores: una entrega no vista usa un espacio. Las impresiones cuentan solo visibilidad reportada por el navegador. Cerrar oculta esta campaña durante la sesión.')}</p>
 <label>{t('Priority','Prioridad')}<input type="number" min={-1000} max={1000} value={draft.configuration.priority} onChange={e=>cfg('priority',Number(e.target.value))}/></label>
 <fieldset><legend>{t('External relationships — no ad automation','Relaciones externas — sin automatización publicitaria')}</legend>{['FACEBOOK','INSTAGRAM','GOOGLE'].map(channel=>{const x=draft.configuration.external.find(v=>v.channel===channel);return <div key={channel}><label><input type="checkbox" checked={!!x} onChange={e=>cfg('external',e.target.checked?[...draft.configuration.external,{channel,provenance:'reference',externalId:'',audience:'',status:'planned',reference:'',adId:'',adSetId:''}]:draft.configuration.external.filter(v=>v.channel!==channel))}/>{channel}</label>{x&&<><p>{t('Evidence provenance','Procedencia de evidencia')}: {x.provenance==='manual'?t('Manually recorded','Registrada manualmente'):x.provenance==='imported'?t('Imported evidence','Evidencia importada'):t('External reference only; no live metrics','Solo referencia externa; sin métricas en vivo')}</p>{['externalId','adId','adSetId','audience','status','reference'].map(k=><label key={k}>{({externalId:t('External campaign identity','Identidad externa de campaña'),adId:t('External ad identity','Identidad externa del anuncio'),adSetId:t('External ad-set identity','Identidad externa del conjunto de anuncios'),audience:t('External audience reference','Referencia de audiencia externa'),status:t('External status','Estado externo'),reference:t('Provenance / tracking reference','Referencia de procedencia / seguimiento')} as Record<string,string>)[k]}<input maxLength={300} value={String(x[k]??'')} onChange={e=>cfg('external',draft.configuration.external.map(v=>v.channel===channel?{...v,[k]:e.target.value}:v))}/></label>)}</>}</div>})}</fieldset>
 <button type="submit">{t('Save Campaign','Guardar campaña')}</button></fieldset></form>
 {draft.id&&manage&&draft.state!=='archived'&&<fieldset disabled={busy}><label>{t('Reason','Motivo')}<input maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{[['schedule',t('Schedule','Programar')],['pause',t('Pause','Pausar')],['resume',t('Resume','Reanudar')],['end',t('End','Finalizar')],['archive',t('Archive','Archivar')]].filter(([op])=>op==='schedule'?draft.state==='draft':op==='pause'?['active','scheduled'].includes(draft.state):op==='resume'?draft.state==='paused':op==='end'?draft.state!=='ended':true).map(([op,label])=><button key={op} onClick={()=>save(op)}>{label}</button>)}</fieldset>}
 {draft.creativeEvidence&&<section><h3>{t('Pinned creative evidence','Evidencia del creativo fijado')}</h3><p>EN: {draft.creativeEvidence.headline_en} — {draft.creativeEvidence.copy_en}</p><p>ES: {draft.creativeEvidence.headline_es} — {draft.creativeEvidence.copy_es}</p></section>}{draft.id&&<section><h3>{t('Performance by configuration','Rendimiento por configuración')}</h3><p>{t('Browser-reported visibility and clicks, not unique people, conversions or revenue. External references are not live platform metrics.','Visibilidad y clics reportados por el navegador, no personas únicas, conversiones ni ingresos. Las referencias externas no son métricas en vivo.')}</p>{performance.slice(0,25).map(p=><p key={String(p.id)}>v{String(p.version)} — {t('Impressions','Impresiones')}: {String(p.impressions)} · {t('Clicks','Clics')}: {String(p.clicks)} · CTR: {Number(p.impressions)>0?(100*Number(p.clicks)/Number(p.impressions)).toFixed(2)+'%':t('Not established','No establecido')}</p>)}{performance.length>25&&<button onClick={()=>void campaignPerformance(draft.id,String(performance[24].id)).then(r=>{if(r.ok)setPerformance(r.data)})}>{t('More history','Más historial')}</button>}</section>}
 </>}
 </div>
}
