'use client'
import {useState} from 'react'
import {resolveListingImages} from '@/app/utils/resolveListingImages'
import {optimizeListingImage} from '@/app/utils/optimizeListingImage'
import {adminUpload,adminMediaControl,adminResumeMedia} from './media-actions'
export default function AdminMedia({listing,images,groups,owner,language,changed,pending,readOnly=false}:{readOnly?:boolean;pending:string[];listing:string;images:string|null;groups:{managed:string[];source:string[]}|null;owner:string|null;language:'en'|'es';changed:()=>void}){
 const es=language==='es',[file,setFile]=useState<File|null>(null),[request,setRequest]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(false)
 let parsed:string[]=[];try{const p=JSON.parse(images||'[]');parsed=Array.isArray(p)?p:[]}catch{parsed=(images||'').split('|').filter(Boolean)}
 const managed=groups?.managed??(owner?parsed:[]),source=groups?.source??(!owner?parsed:[])
 async function upload(){if(!file)return;setBusy(true);setError(false);const id=request||crypto.randomUUID();setRequest(id);const f=new FormData();f.set('request',id);f.set('listing',listing);f.set('file',file);const r=await adminUpload(f);setBusy(false);setError(!r.ok);if(r.ok){setFile(null);setRequest('');changed()}}
 async function control(operation:'reorder'|'remove',values:string[]){setBusy(true);const r=await adminMediaControl(crypto.randomUUID(),listing,images,operation,values);setBusy(false);setError(!r.ok);if(r.ok)changed()}
 return <section><h3>{es?'Imágenes':'Images'}</h3><p>{es?'Las imágenes gestionadas por Twuanis aparecen antes de las referencias de la fuente.':'Twuanis-managed images appear before source references.'}</p><ol>{managed.map((p,i)=><li key={p}><img alt={es?'Imagen gestionada':'Managed image'} src={resolveListingImages([p])[0]} width={120} height={90}/><span>{owner?(es?'Del cliente':'Customer-managed'):(es?'Gestionada por Twuanis':'Twuanis-managed')} {i+1}</span><button hidden={readOnly} disabled={busy||i===0} onClick={()=>{const order=[...managed];[order[i-1],order[i]]=[order[i],order[i-1]];control('reorder',order)}}>{es?'Subir posición':'Move earlier'}</button><button hidden={readOnly} disabled={busy} onClick={()=>control('remove',[p])}>{es?'Quitar':'Remove'}</button></li>)}</ol><ol>{source.map((p,i)=><li key={p}><img alt={es?'Imagen de fuente':'Source image'} src={p} width={120} height={90}/>{es?'Referencia de fuente':'Source reference'} {i+1}: <span>{p}</span><button hidden={readOnly} disabled={busy} onClick={()=>control('remove',[p])}>{es?'Quitar referencia':'Remove reference'}</button></li>)}</ol>
 {!readOnly&&<>{pending.map(id=><button key={id} disabled={busy} onClick={async()=>{setBusy(true);const r=await adminResumeMedia(id);setBusy(false);setError(!r.ok);if(r.ok)changed()}}>{es?'Reintentar adjuntar carga pendiente':'Retry pending attachment'}</button>)}<label>{es?'Agregar imagen (JPEG, PNG o WebP)':'Add image (JPEG, PNG or WebP)'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!!request} onChange={async e=>{try{const f=e.target.files?.[0];if(f)setFile(await optimizeListingImage(f));setError(false)}catch{setError(true)}}}/></label><button disabled={busy||!file} onClick={upload}>{request?(es?'Reintentar misma carga':'Retry same upload'):(es?'Cargar imagen':'Upload image')}</button></>}{error&&<p role="alert">{es?'No se confirmó la operación. Reintente la misma carga; la propiedad conserva su identidad.':'The operation was not confirmed. Retry the same upload; the listing retains its identity.'}</p>}</section>
}
