'use client'
import {useEffect,useRef,useState} from 'react'
import {readAdminAddons,changeAdminAddon} from './addon-actions'
import type {AddonCatalog,AddonProjection} from './addon-contract'
import type {AdminLanguage} from './admin-contract'
const labels={en:{loading:'Loading add-ons…',error:'Request failed. Check access and reload.',stale:'This product changed. Reload before editing.',reload:'Reload',back:'Back',next:'Next page',first:'First page',inspect:'Inspect',create:'Create Add-on',name:'Name',description:'Description',save:'Save',copy:'Commercial copy',terms:'Future commercial terms',days:'Elapsed days',prices:'Standard prices',schedule:'Whole-job quantity pricing',capacity:'Homepage capacity',lifetime:'Lifetime pricing right; no product access',unconfigured:'Not configured',unavailable:'Customer acquisition is unavailable. Checkout and payment fulfillment are not activated.',missing:'Spanish commercial copy not configured',reason:'Reason',archive:'Archive',confirm:'Archive this product? Existing purchased rights remain unchanged.',dirty:'Discard unsaved changes?',saved:'Saved.',readOnly:'Read-only access',empty:'No add-ons.',draft:'Draft',active:'Active',inactive:'Inactive',archived:'Archived',target:'Target',version:'Configuration version',behavior:'Registered behavior'},es:{loading:'Cargando complementos…',error:'No se pudo completar la solicitud. Revise su acceso y vuelva a cargar.',stale:'Este producto cambió. Vuelva a cargar antes de editar.',reload:'Volver a cargar',back:'Volver',next:'Página siguiente',first:'Primera página',inspect:'Ver detalles',create:'Crear complemento',name:'Nombre',description:'Descripción',save:'Guardar',copy:'Texto comercial',terms:'Condiciones comerciales futuras',days:'Días transcurridos',prices:'Precios estándar',schedule:'Precio por cantidad del trabajo completo',capacity:'Capacidad de la página principal',lifetime:'Derecho de precios de por vida; no concede acceso a productos',unconfigured:'Sin configurar',unavailable:'La adquisición no está disponible. No se han activado el pago ni el cumplimiento comercial.',missing:'Texto comercial en español sin configurar',reason:'Motivo',archive:'Archivar',confirm:'¿Archivar este producto? Los derechos adquiridos no cambian.',dirty:'¿Descartar cambios sin guardar?',saved:'Guardado.',readOnly:'Acceso de solo lectura',empty:'No hay complementos.',draft:'Borrador',active:'Activo',inactive:'Inactivo',archived:'Archivado',target:'Destino',version:'Versión de configuración',behavior:'Comportamiento registrado'}}
const behaviors:Record<string,[string,string]>={featured_collection:['Featured collection','Colección destacada'],priority_over_organic:['Search priority','Prioridad en resultados'],homepage_carousel:['Homepage carousel','Carrusel de inicio'],province_contextual_priority:['Province context priority','Prioridad por provincia'],property_type_contextual_priority:['Property-type context priority','Prioridad por tipo de propiedad'],bulk_import_job:['Whole-job customer import','Importación completa del cliente'],founding_pricing_entitlement:['Lifetime pricing right','Derecho de precios de por vida'],premium_listing_experience:['Future listing experience','Experiencia futura del anuncio']}
export default function AdminAddons({language,manage}:{language:AdminLanguage;manage:boolean}){
 const t=labels[language],busyRef=useRef(false),ticket=useRef<{payload:string;id:string}|null>(null)
 const [catalog,setCatalog]=useState<AddonCatalog|null>(null),[selected,setSelected]=useState<AddonProjection|null>(null),[draft,setDraft]=useState<AddonProjection|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[cursor,setCursor]=useState<string|null>(null),[creating,setCreating]=useState(false),[name,setName]=useState(''),[behavior,setBehavior]=useState(''),[reason,setReason]=useState('')
 const dirty=(creating&&(name!==''||behavior!==''))||(!!selected&&JSON.stringify(selected)!==JSON.stringify(draft))
 const behaviorLabel=(id:string)=>behaviors[id]?.[language==='es'?1:0]??id
 async function load(after:string|null=cursor){setBusy(true);try{const r=await readAdminAddons(after);if(r.ok){setCatalog(r.data);setCursor(after);setSelected(null);setDraft(null);setCreating(false);setName('');setBehavior('');setReason('');setMessage('')}else setMessage(t.error)}finally{setBusy(false)}}
 useEffect(()=>{let alive=true;readAdminAddons(null).then(r=>{if(alive){if(r.ok)setCatalog(r.data);else setMessage(labels[language].error)}});return()=>{alive=false}},[])
 useEffect(()=>{const leave=(e:Event)=>{if(busyRef.current||(dirty&&!window.confirm(t.dirty)))e.preventDefault()};const unload=(e:BeforeUnloadEvent)=>{if(dirty||busyRef.current)e.preventDefault()};window.addEventListener('admin-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('admin-leave',leave);window.removeEventListener('beforeunload',unload)}},[dirty,t.dirty])
 async function execute(command:Record<string,unknown>){if(busyRef.current)return;const payload=JSON.stringify(command);if(ticket.current?.payload!==payload)ticket.current={payload,id:crypto.randomUUID()};busyRef.current=true;setBusy(true);try{const r=await changeAdminAddon(ticket.current.id,command);if(!r.ok){setMessage(r.code==='stale'?t.stale:t.error);return}ticket.current=null;await load(command.operation==='create'?null:cursor);setMessage(t.saved)}catch{setMessage(t.error)}finally{busyRef.current=false;setBusy(false)}}
 function save(operation:string,fields:Record<string,unknown>){if(!selected||!draft)return;const remainder=structuredClone(draft);if(operation==='copy')Object.assign(remainder,{name_en:selected.name_en,name_es:selected.name_es,description_en:selected.description_en,description_es:selected.description_es});if(operation==='configuration')Object.assign(remainder,{durationDays:selected.durationDays,standardPrices:selected.standardPrices,quantityTiers:selected.quantityTiers});if(JSON.stringify(remainder)!==JSON.stringify(selected)&&!window.confirm(t.dirty))return;void execute({operation,product:selected.id,expected:selected.revision,reason,...fields})}
 const editable=manage&&selected?.state!=='archived'
 return <div aria-busy={busy}><p>{t.unavailable}</p>{!manage&&<p>{t.readOnly}</p>}{message&&<p role="status">{message}</p>}<button disabled={busy} onClick={()=>{if(!dirty||window.confirm(t.dirty))void load()}}>{t.reload}</button>
 {!catalog&&!message&&<p>{t.loading}</p>}
 {manage&&!selected&&<button disabled={busy} onClick={()=>{if(!dirty||window.confirm(t.dirty)){setCreating(!creating);setName('');setBehavior('')}}}>{t.create}</button>}
 {creating&&catalog&&<form onSubmit={e=>{e.preventDefault();void execute({operation:'create',name_en:name,behavior})}}><fieldset disabled={busy}><legend>{t.create}</legend><label>{t.name} EN<input required maxLength={300} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t.behavior}<select required value={behavior} onChange={e=>setBehavior(e.target.value)}><option value="">—</option>{catalog.createBehaviors.map(b=><option key={b} value={b}>{behaviorLabel(b)}</option>)}</select></label><button>{t.create}</button></fieldset></form>}
 {selected&&draft?<><button disabled={busy} onClick={()=>{if(!dirty||window.confirm(t.dirty)){setSelected(null);setDraft(null)}}}>{t.back}</button><h3>{language==='es'?(selected.name_es??selected.name_en):selected.name_en}</h3><p><code>{selected.id}</code></p><p>{t.target}: {selected.target==='listing'?(language==='es'?'Anuncio':'Listing'):selected.target==='account'?(language==='es'?'Cuenta':'Account'):(language==='es'?'Operación':'Operation')}</p><p>{behaviorLabel(selected.behavior)} · {t[selected.state]} · {t.version} {selected.version}</p>
 <form onSubmit={e=>{e.preventDefault();save('copy',{name_en:draft.name_en,name_es:draft.name_es,description_en:draft.description_en,description_es:draft.description_es})}}><fieldset disabled={!editable||busy}><legend>{t.copy}</legend>{(['name_en','name_es','description_en','description_es'] as const).map(k=><label key={k}>{k.startsWith('name')?t.name:t.description} {k.endsWith('en')?'EN':'ES'}<textarea required={k==='name_en'} maxLength={k.startsWith('name')?300:4000} value={draft[k]??''} onChange={e=>setDraft({...draft,[k]:e.target.value||null})}/></label>)}{!draft.name_es&&<p>{t.missing}</p>}{editable&&<button>{t.save}</button>}</fieldset></form>
 {draft.capacity!==null&&<p>{t.capacity}: {draft.capacity}</p>}{draft.termKind==='lifetime'&&<p>{t.lifetime}</p>}
 {draft.termKind==='unconfigured'?<p>{t.unconfigured}</p>:<form onSubmit={e=>{e.preventDefault();save('configuration',draft.termKind==='whole_job'?{tiers:draft.quantityTiers}:{prices:draft.standardPrices,...(draft.termKind==='elapsed_days'?{durationDays:draft.durationDays}:{})})}}><fieldset disabled={!editable||busy}><legend>{t.terms}</legend>{draft.termKind==='elapsed_days'&&<label>{t.days}<input required type="number" min="1" max="3650" step="1" value={draft.durationDays??''} onChange={e=>setDraft({...draft,durationDays:e.target.value===''?null:Number(e.target.value)})}/></label>}
 {draft.termKind==='whole_job'?<><h4>{t.schedule}</h4>{draft.quantityTiers.map((row,i)=><label key={row.min}>{row.min}–{row.max} · USD<input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" value={row.unitRate} onChange={e=>setDraft({...draft,quantityTiers:draft.quantityTiers.map((r,j)=>j===i?{...r,unitRate:e.target.value}:r)})}/></label>)}<p>{language==='es'?'501+ y CRC: sin precio.':'501+ and CRC: unpriced.'}</p></>:<><h4>{t.prices}</h4>{(draft.termKind==='lifetime'?['USD'] as const:['USD','CRC'] as const).map(cur=><label key={cur}>{cur}<input required inputMode="decimal" pattern={cur==='CRC'?'[0-9]+':'[0-9]+(\\.[0-9]{1,2})?'} value={draft.standardPrices[cur]??''} onChange={e=>setDraft({...draft,standardPrices:{...draft.standardPrices,[cur]:e.target.value}})}/></label>)}</>}{editable&&<button>{t.save}</button>}</fieldset></form>}
 {editable&&selected.termKind!=='unconfigured'&&<fieldset disabled={busy}><legend>{language==='es'?'Ciclo de vida':'Lifecycle'}</legend><label>{t.reason}<input maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="admin-actions" style={{flexWrap:'wrap'}}>{(['active','inactive'] as const).filter(s=>s!==selected.state).map(s=><button key={s} onClick={()=>save('lifecycle',{state:s})}>{t[s]}</button>)}<button disabled={!reason.trim()} onClick={()=>{if(window.confirm(t.confirm))save('lifecycle',{state:'archived'})}}>{t.archive}</button></div></fieldset>}
 </>:catalog&&<>{catalog.products.length===0&&<p>{t.empty}</p>}{catalog.products.slice(0,25).map(p=><article key={p.id} style={{padding:'1rem',margin:'1rem 0',border:'1px solid var(--border)',borderRadius:8}}><h3>{language==='es'?(p.name_es??p.name_en):p.name_en}</h3><p><code>{p.id}</code></p><p>{t[p.state]} · {behaviorLabel(p.behavior)}</p><p>{p.durationDays!==null?`${p.durationDays} ${t.days}`:p.termKind==='lifetime'?t.lifetime:p.termKind==='whole_job'?t.schedule:t.unconfigured}</p><p>{Object.entries(p.standardPrices).map(([c,v])=>`${c} ${v}`).join(' / ')}</p>{!p.name_es&&<p>{t.missing}</p>}<button disabled={busy} onClick={()=>{if(dirty&&!window.confirm(t.dirty))return;setCreating(false);setName('');setBehavior('');setSelected(p);setDraft(structuredClone(p));setReason('')}}>{t.inspect}</button></article>)}<div className="admin-actions">{cursor&&<button disabled={busy} onClick={()=>void load(null)}>{t.first}</button>}{catalog.products.length>25&&<button disabled={busy} onClick={()=>void load(catalog.products[24].id)}>{t.next}</button>}</div></>}
 </div>
}
