'use client'
import {useEffect,useRef,useState} from 'react'
import {adminRead,adminCommand,adminEdit} from './actions'
import AdminCreate from './AdminCreate'
import AdminMedia from './AdminMedia'
import type {AdminLanguage} from './admin-contract'
type Row={ [key:string]:unknown;pending_media:string[];images:string|null;media_groups:{managed:string[];source:string[]}|null;id:string;title:string|null;transaction_type:string;listing_status:string;listing_origin:string;property_type:string;province:string;canton:string;district:string;updated_at:string;owner_id:string|null;source_name:string|null;source_listing_id:string|null;canonical_revision:string;property_area:string|null;construction_area:string|null;description:string|null}
const words={en:{search:'Title prefix, listing ID or source ID',all:'All',status:'Status',origin:'Origin',transaction:'Transaction',province:'Province',canton:'Canton',district:'District',property_type:'Property Type',apply:'Search',previous:'Previous',next:'Next',empty:'No listings found.',error:'The request failed. Refresh and check your access.',loading:'Loading…',back:'Back to listings',title:'Title',place:'Geography',actions:'Actions',open:'Inspect',save:'Save changes',area:'Property Area (m²)',construction:'Construction Area (m²)',unchanged:'Unchanged',set:'Set value',clear:'Clear / mark unknown',archive:'Archive',restore:'Restore as draft',delete:'Request permanent deletion',reason:'Administrative reason',confirm:'Type DELETE to confirm',deleteWord:'DELETE',sourceNote:'Source-managed listing. Future source observations may update fields permitted by ingestion policy.',deletedDenied:'Permanent deletion is unavailable because canonical history must be preserved.',saved:'Saved.',description:'Description',identity:'Identity / ownership',correction:'Edit canonical measurements',customer:'Customer-owned',system:'System / Manual',imported:'Source-managed / Imported',sale:'Sale',rent:'Rent',draft:'Draft',active:'Active',expired:'Expired',archived:'Archived',deleted:'Deleted'},es:{search:'Inicio del título, ID de propiedad o ID de origen',all:'Todos',status:'Estado',origin:'Origen',transaction:'Transacción',province:'Provincia',canton:'Cantón',district:'Distrito',property_type:'Tipo de propiedad',apply:'Buscar',previous:'Anterior',next:'Siguiente',empty:'No se encontraron propiedades.',error:'La solicitud falló. Actualice y revise su acceso.',loading:'Cargando…',back:'Volver a propiedades',title:'Título',place:'Geografía',actions:'Acciones',open:'Ver detalles',save:'Guardar cambios',area:'Área del terreno (m²)',construction:'Área de construcción (m²)',unchanged:'Sin cambios',set:'Establecer valor',clear:'Borrar / marcar como desconocida',archive:'Archivar',restore:'Restaurar como borrador',delete:'Solicitar eliminación permanente',reason:'Motivo administrativo',confirm:'Escriba ELIMINAR para confirmar',deleteWord:'ELIMINAR',sourceNote:'Propiedad gestionada por una fuente. Las observaciones futuras pueden actualizar los campos permitidos por la política de importación.',deletedDenied:'La eliminación permanente no está disponible porque debe conservarse el historial canónico.',saved:'Guardado.',description:'Descripción',identity:'Identidad / titularidad',correction:'Editar medidas canónicas',customer:'De un cliente',system:'Sistema / Manual',imported:'Gestionada por fuente / Importada',sale:'Venta',rent:'Alquiler',draft:'Borrador',active:'Activa',expired:'Vencida',archived:'Archivada',deleted:'Eliminada'}}
type Option={id:string;term_name:string;term_name_en:string|null;term_name_es:string|null}
export default function AdminListings({language,manage}:{language:AdminLanguage;manage:boolean}) {
 const [creating,setCreating]=useState(false)
 const t=words[language],[filters,setFilters]=useState<Record<string,string>>({}),[committed,setCommitted]=useState<Record<string,string>>({}),[page,setPage]=useState(0),[cursors,setCursors]=useState<Array<{id:string;updated_at:string}>>([]),[rows,setRows]=useState<Row[]>([]),[detail,setDetail]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[refresh,setRefresh]=useState(0)
 const [options,setOptions]=useState<Record<string,Option[]>>({});const generation=useRef(0)
 useEffect(()=>{let live=true;Promise.all(['province','property_type'].map(async dimension=>{const r=await adminRead({mode:'options',dimension});return [dimension,r.ok?r.data:[]] as const})).then(entries=>{if(live)setOptions(Object.fromEntries(entries))});return()=>{live=false}},[])
 useEffect(()=>{const id=++generation.current;setBusy(true);setError(false);adminRead({mode:'list',...committed,...(page>0?{after:cursors[page-1]}:{})}).then(r=>{if(id!==generation.current)return;setBusy(false);if(r.ok)setRows(r.data);else{setError(true);setRows([])}});return()=>{generation.current++}},[committed,page,refresh,cursors])
 async function changeGeo(dimension:string,value:string){setFilters(f=>({...f,[dimension]:value,...(dimension==='province'?{canton:'',district:''}:dimension==='canton'?{district:''}:{})}));if(dimension==='district')return;const child=dimension==='province'?'canton':'district';setOptions(o=>({...o,[child]:[],...(dimension==='province'?{district:[]}:{})}));if(value){const r=await adminRead({mode:'options',dimension:child,parent:value});if(r.ok)setOptions(o=>({...o,[child]:r.data}))}}
 async function inspect(id:string){setBusy(true);setError(false);const r=await adminRead({mode:'detail',listing:id});setBusy(false);if(r.ok&&r.data)setDetail(r.data);else setError(true)}
 const label=(value:string)=>t[value as keyof typeof t]||value
 if(creating)return <AdminCreate language={language} cancel={()=>setCreating(false)} done={id=>{setCreating(false);inspect(id);setRefresh(n=>n+1)}}/>
 return <>{error&&<p role="alert">{t.error}</p>}{busy&&<p role="status">{t.loading}</p>}{detail?<AdminDetail key={detail.id+detail.updated_at} row={detail} language={language} manage={manage} back={()=>setDetail(null)} changed={()=>{inspect(detail.id);setRefresh(n=>n+1)}}/>:<>
  {manage&&<button onClick={()=>setCreating(true)}>{language==='es'?'Agregar propiedad':'Add Listing'}</button>}
  <form className="admin-filters" onSubmit={e=>{e.preventDefault();setPage(0);setCursors([]);setCommitted({...filters})}}>
   <label>{t.search}<input maxLength={128} value={filters.search||''} onChange={e=>setFilters(f=>({...f,search:e.target.value}))}/></label>
   {(['status','origin','transaction'] as const).map(k=><label key={k}>{t[k]}<select value={filters[k]||''} onChange={e=>setFilters(f=>({...f,[k]:e.target.value}))}><option value="">{t.all}</option>{(k==='status'?['draft','active','expired','archived','deleted']:k==='origin'?['customer','system','imported']:['sale','rent']).map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}
   {(['province','canton','district','property_type'] as const).map(k=><label key={k}>{t[k]}<select value={filters[k]||''} onChange={e=>k==='property_type'?setFilters(f=>({...f,[k]:e.target.value})):changeGeo(k,e.target.value)}><option value="">{t.all}</option>{(options[k]||[]).map(o=><option key={o.id} value={o.id}>{(language==='es'?o.term_name_es:o.term_name_en)||o.term_name}</option>)}</select></label>)}<button disabled={busy}>{t.apply}</button>
  </form>
  {!busy&&!rows.length&&<p>{t.empty}</p>}
  <table className="admin-list-table"><thead><tr>{[t.title,t.transaction,t.property_type,t.place,t.status,t.origin,t.actions].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.slice(0,25).map(r=><tr key={r.id}><td>{r.title||r.id}</td><td>{label(r.transaction_type)}</td><td>{r.property_type}</td><td>{[r.province,r.canton,r.district].filter(Boolean).join(' / ')}</td><td>{label(r.listing_status)}</td><td>{label(r.listing_origin)}</td><td><button onClick={()=>inspect(r.id)} disabled={busy}>{t.open}</button></td></tr>)}</tbody></table>
  <div className="admin-list-mobile">{rows.slice(0,25).map(r=><article key={r.id}><h3>{r.title||r.id}</h3><p>{label(r.transaction_type)} · {label(r.listing_status)} · {label(r.listing_origin)}</p><p>{[r.province,r.canton,r.district].filter(Boolean).join(' / ')}</p><button onClick={()=>inspect(r.id)} disabled={busy}>{t.open}</button></article>)}</div>
  <div className="admin-actions"><button disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>{t.previous}</button><span>{page+1}</span><button disabled={busy||rows.length<=25} onClick={()=>{const r=rows[24];setCursors(c=>[...c.slice(0,page),{id:r.id,updated_at:r.updated_at}]);setPage(p=>p+1)}}>{t.next}</button></div>
 </>}</>
}
function AdminDetail({row,language,manage,back,changed}:{row:Row;language:AdminLanguage;manage:boolean;back:()=>void;changed:()=>void}) {
 const t=words[language],[modes,setModes]=useState<Record<string,string>>({}),[values,setValues]=useState<Record<string,string>>({}),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[fields,setFields]=useState<Record<string,string>>({}),[title,setTitle]=useState(row.title||''),[description,setDescription]=useState(row.description||'')
 useEffect(()=>{const dirty=Object.keys(fields).length>0||Object.values(modes).some(Boolean)||title!==(row.title||'')||description!==(row.description||'');const leave=(e:Event)=>{if(dirty&&!window.confirm(language==='es'?'¿Descartar cambios sin guardar?':'Discard unsaved changes?'))e.preventDefault()};const unload=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener('admin-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('admin-leave',leave);window.removeEventListener('beforeunload',unload)}},[fields,modes,title,description,row,language])
 async function perform(operation:string){if(operation==='archive'&&!window.confirm(language==='es'?'¿Archivar esta propiedad con el motivo indicado?':'Archive this listing with the stated reason?'))return;setBusy(true);setMessage('');let r;
 if(operation==='edit'){
  if(Object.values(modes).includes('clear')&&!window.confirm(language==='es'?'¿Borrar las medidas seleccionadas y marcarlas como desconocidas?':'Clear the selected measurements and mark them unknown?')){setBusy(false);return}
  const changes:Record<string,unknown>={...fields};if(title!==(row.title||''))changes.title=title;if(description!==(row.description||''))changes.description=description;
  for(const key of ['property_area','construction_area']){if(modes[key]==='clear')changes[key]={kind:'clear'};if(modes[key]==='set')changes[key]={kind:'set',value:values[key]}}
  r=await adminEdit(crypto.randomUUID(),row.id,row.canonical_revision,row.updated_at,changes,reason)
 }else r=await adminCommand(crypto.randomUUID(),{operation,listing:row.id,expected:row.canonical_revision,prior_updated_at:row.updated_at,reason});
 setBusy(false);if(r.ok&&r.data.code==='CANONICAL_HISTORY_PREVENTS_DELETE')setMessage(t.deletedDenied);else if(r.ok){setMessage(t.saved);changed()}else setMessage(t.error)
 }
 return <div><button onClick={()=>{if(window.dispatchEvent(new Event('admin-leave',{cancelable:true})))back()}} disabled={busy}>{t.back}</button><h3>{t.identity}</h3><dl>{Object.entries(row).filter(([k])=>['id','owner_id','source_name','source_listing_id','listing_origin','listing_status','transaction_type','property_type','province','canton','district','updated_at'].includes(k)).map(([k,v])=><div key={k}><dt>{({id:language==='es'?'ID de propiedad':'Listing ID',owner_id:language==='es'?'Cuenta titular':'Owner account',source_name:language==='es'?'Fuente':'Source',source_listing_id:language==='es'?'ID en la fuente':'Source listing ID',listing_origin:t.origin,listing_status:t.status,transaction_type:t.transaction,property_type:t.property_type,province:t.province,canton:t.canton,district:t.district,updated_at:language==='es'?'Última actualización':'Last updated'} as Record<string,string>)[k]}</dt><dd>{typeof v==='string'?((k==='listing_status'||k==='listing_origin'||k==='transaction_type')?(t[v as keyof typeof t]||v):v):'—'}</dd></div>)}</dl>{row.listing_origin==='imported'&&<p>{t.sourceNote}</p>}
 <h3>{row.title||'—'}</h3><p>{row.description||'—'}</p><dl>{[[t.area,row.property_area],[t.construction,row.construction_area],[language==='es'?'Precio solicitado original':'Original asking amount',row.transaction_type==='sale'?row.current_price:row.monthly_price],[language==='es'?'Moneda original':'Original currency',row.currency]].map(([label,value])=><div key={String(label)}><dt>{String(label)}</dt><dd>{typeof value==='string'||typeof value==='number'?String(value):'—'}</dd></div>)}</dl>
 <details><summary>{language==='es'?'Hechos y características actuales':'Current facts and characteristics'}</summary><dl>{[['bedrooms','Bedrooms','Dormitorios'],['bathrooms','Bathrooms','Baños'],['parking','Parking','Estacionamientos'],['year_built_range','Year built category','Categoría de año de construcción'],['distance_to_paved_road_range','Road distance category','Categoría de distancia a carretera'],['utility','Utilities','Servicios'],['environment','Environment','Entorno'],['terrain','Terrain','Terreno'],['accessibility','Accessibility','Accesibilidad'],['legal_status','Legal status','Estado legal'],['whatsapp','WhatsApp','WhatsApp']].map(([key,en,es])=><div key={key}><dt>{language==='es'?es:en}</dt><dd>{Array.isArray(row[key])?(row[key] as string[]).join(' · '):typeof row[key]==='string'?row[key] as string:'—'}</dd></div>)}</dl></details>
 <AdminMedia readOnly={!manage} pending={row.pending_media||[]} listing={row.id} images={row.images} groups={row.media_groups} owner={row.owner_id} language={language} changed={changed}/>{manage&&<><form onSubmit={e=>{e.preventDefault();perform('edit')}} className="admin-filters"><label>{t.title}<input maxLength={512} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{t.description}<textarea maxLength={16000} value={description} onChange={e=>setDescription(e.target.value)}/></label>
 <details><summary>{language==='es'?'Otros campos canónicos':'Other canonical fields'}</summary><p>{language==='es'?'Solo se guardan los campos modificados. Use los nombres canónicos exactos; se validan en el servidor.':'Only changed fields are saved. Use exact canonical names; the server validates them.'}</p>{[['province','Province','Provincia'],['canton','Canton','Cantón'],['district','District','Distrito'],['property_type','Property Type','Tipo de propiedad'],['utility','Utilities (separate with |)','Servicios (separe con |)'],['environment','Environment (separate with |)','Entorno (separe con |)'],['terrain','Terrain (separate with |)','Terreno (separe con |)'],['accessibility','Accessibility','Accesibilidad'],['legal_status','Legal status','Estado legal'],['bedrooms','Bedrooms: exact value or canonical category','Dormitorios: valor exacto o categoría canónica'],['bathrooms','Bathrooms: exact value or canonical category','Baños: valor exacto o categoría canónica'],['parking','Parking: exact value or canonical category','Estacionamientos: valor exacto o categoría canónica'],['year_built_range','Year built canonical category','Categoría canónica de año de construcción'],['distance_to_paved_road_range','Road distance category','Categoría de distancia a carretera'],[row.transaction_type==='sale'?'current_price':'monthly_price','Original asking amount','Precio solicitado original'],['currency','Original currency (CRC/USD)','Moneda original (CRC/USD)'],['whatsapp','WhatsApp','WhatsApp']].map(([k,en,es])=><label key={k}>{language==='es'?es:en}<input maxLength={256} value={fields[k]??(typeof row[k]==='string'?row[k] as string:Array.isArray(row[k])?(row[k] as string[]).join('|'):'')} onChange={e=>setFields(f=>({...f,[k]:e.target.value}))}/></label>)}</details>
 {(['property_area','construction_area'] as const).map(k=><fieldset key={k}><legend>{k==='property_area'?t.area:t.construction}</legend><p>{row[k]??'—'}</p><select aria-label={k==='property_area'?t.area:t.construction} value={modes[k]||''} onChange={e=>setModes(m=>({...m,[k]:e.target.value}))}><option value="">{t.unchanged}</option><option value="set">{t.set}</option><option value="clear">{t.clear}</option></select>{modes[k]==='set'&&<input aria-label={t.set} required type="number" min="0.000000001" step="any" value={values[k]||''} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/>}</fieldset>)}<button disabled={busy||['archived','deleted'].includes(row.listing_status)}>{t.save}</button></form>
 <section><h3>{t.actions}</h3><label>{t.reason}<textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="admin-actions">{['archived','deleted'].includes(row.listing_status)?<button disabled={busy} onClick={()=>perform('restore')}>{t.restore}</button>:<button disabled={busy||!reason.trim()} onClick={()=>perform('archive')}>{t.archive}</button>}</div><label>{t.confirm}<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={busy||!reason.trim()||confirmation!==t.deleteWord} onClick={()=>perform('delete')}>{t.delete}</button></section></>}
 {message&&<p role="status">{message}</p>}</div>
}
