
'use client'
import {useEffect,useRef,useState} from 'react'
import {readOrders} from './order-actions'
import type {AdminLanguage} from './admin-contract'
import './orders.css'
type Row={id:string;accountId:string;productId:string;currency:string;source:string;total:string;createdAt:string;paymentDeadline:string;state:string}
type Detail=Row&{requestId:string;terms:Record<string,unknown>;payment:Record<string,unknown>|null;fulfillment:Record<string,unknown>|null;evidenceComplete:boolean}
const labels={en:{intro:'Orders record purchased terms. Payment and fulfillment are separate. Historical facts are read-only.',load:'Loading orders…',error:'Unable to read orders. Check your access and retry.',empty:'No canonical orders.',refresh:'Apply filters',account:'Customer account UUID',kind:'Product class',source:'Price source',currency:'Currency',all:'All',inspect:'Inspect',next:'Next page',first:'First page',back:'Back to orders',terms:'Purchased terms',payment:'Payment acknowledgement',fulfillment:'Fulfillment evidence',none:'No linked evidence recorded',incomplete:'Earlier snapshot: complete Step 8 terms were not recorded. Missing evidence is not inferred.',request:'Request identity',created:'Created',deadline:'Payment deadline',state:'Order state',pending:'Unpaid — pending',expired:'Unpaid — expired',paid:'Paid acknowledgement recorded',package:'Package',addon:'Add-on',identity:'Order identity'},es:{intro:'Los pedidos registran los términos comprados. El pago y la entrega son independientes. Los hechos históricos son de solo lectura.',load:'Cargando pedidos…',error:'No se pueden leer los pedidos. Revise su acceso e inténtelo de nuevo.',empty:'No hay pedidos canónicos.',refresh:'Aplicar filtros',account:'UUID de la cuenta del cliente',kind:'Clase de producto',source:'Origen del precio',currency:'Moneda',all:'Todos',inspect:'Inspeccionar',next:'Página siguiente',first:'Primera página',back:'Volver a pedidos',terms:'Términos comprados',payment:'Constancia de pago',fulfillment:'Evidencia de entrega',none:'No hay evidencia vinculada registrada',incomplete:'Instantánea anterior: no se registraron todos los términos del Paso 8. No se infiere evidencia faltante.',request:'Identidad de solicitud',created:'Creado',deadline:'Fecha límite de pago',state:'Estado del pedido',pending:'Sin pagar — pendiente',expired:'Sin pagar — vencido',paid:'Constancia de pago registrada',package:'Paquete',addon:'Complemento',identity:'Identidad del pedido'}}
const fieldNames:Record<string,[string,string]>={productId:['Product identity','Identidad del producto'],productClass:['Product class','Clase de producto'],configurationId:['Product configuration','Configuración del producto'],configurationVersion:['Configuration version','Versión de configuración'],currency:['Currency','Moneda'],source:['Pricing source','Origen del precio'],standardRate:['Standard unit price','Precio unitario estándar'],standardTotal:['Standard total','Total estándar'],effectiveRate:['Purchased unit price','Precio unitario comprado'],total:['Purchased total','Total comprado'],quantity:['Quantity','Cantidad'],offerId:['Offer identity','Identidad de oferta'],offerConfigurationId:['Offer configuration','Configuración de oferta'],offerVersion:['Offer version','Versión de oferta'],offerEnd:['Offer end','Fin de oferta'],targetKind:['Target type','Tipo de destino'],targetId:['Target identity','Identidad del destino'],terms:['Access / fulfillment terms','Términos de acceso / entrega'],durationDays:['Elapsed days','Días transcurridos'],unit:['Unit','Unidad'],capabilities:['Purchased capabilities','Capacidades compradas'],kind:['Term type','Tipo de plazo'],behavior:['Fulfillment behavior','Comportamiento de entrega'],standardTier:['Standard whole-job tier','Tramo estándar del trabajo completo'],purchasedTier:['Purchased whole-job tier','Tramo comprado del trabajo completo'],lower:['From quantity','Desde cantidad'],upper:['Through quantity','Hasta cantidad'],unitRate:['Unit rate','Tarifa unitaria'],acceptedJob:['Accepted job evidence','Evidencia del trabajo aceptado'],id:['Identity','Identidad'],acceptedQuantity:['Accepted quantity','Cantidad aceptada'],fingerprint:['Accepted input fingerprint','Huella de entrada aceptada'],validator:['Validator version','Versión del validador'],publicationEvidence:['Publication evidence at acceptance','Evidencia de publicación al aceptar'],eventId:['Payment event','Evento de pago'],amount:['Amount','Importe'],acknowledgedAt:['Acknowledged at','Fecha de constancia'],purchaseId:['Purchase identity','Identidad de compra'],paymentId:['Payment identity','Identidad de pago'],activatedAt:['Activated at','Activado'],result:['Recorded result','Resultado registrado']}
function Evidence({value,es}:{value:Record<string,unknown>;es:boolean}){return <dl className="order-evidence">{Object.entries(value).filter(([k])=>!['available','name_en','name_es'].includes(k)).map(([k,v])=><div key={k}><dt>{fieldNames[k]?.[es?1:0]??k}</dt><dd>{v===null||v===undefined?'—':Array.isArray(v)?v.join(', '):typeof v==='object'?<Evidence value={v as Record<string,unknown>} es={es}/>:String(v)}</dd></div>)}</dl>}
export default function AdminOrders({language}:{language:AdminLanguage}){
 const t=labels[language],es=language==='es';const [rows,setRows]=useState<Row[]>([]),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(false);
 const [draft,setDraft]=useState({account:'',kind:'',source:'',currency:''}),[filters,setFilters]=useState(draft),[after,setAfter]=useState<string|undefined>(),[refresh,setRefresh]=useState(0);const sequence=useRef(0);
 useEffect(()=>{const n=++sequence.current;setLoading(true);setError(false);setRows([]);setDetail(null);void readOrders({...filters,account:filters.account||undefined,after}).then(r=>{if(n!==sequence.current)return;if(r.ok&&Array.isArray(r.data))setRows(r.data);else setError(true);setLoading(false)});return()=>{sequence.current++}},[filters,after,refresh]);
 async function inspect(id:string){const n=++sequence.current;setLoading(true);setError(false);const r=await readOrders({id});if(n!==sequence.current)return;if(r.ok&&r.data)setDetail(r.data);else setError(true);setLoading(false)}
 const state=(s:string)=>s==='pending'?t.pending:s==='expired'?t.expired:s==='paid'?t.paid:s;
 return <div className="admin-orders"><p>{t.intro}</p>{error&&<p role="alert">{t.error}</p>}{loading&&<p role="status">{t.load}</p>}
 {detail?<><button onClick={()=>{sequence.current++;setDetail(null);setLoading(false)}}>{t.back}</button><h3>{t.identity}</h3><p className="order-id">{detail.id}</p><dl className="order-evidence">{[[t.account,detail.accountId],[t.request,detail.requestId],[t.state,state(detail.state)],[t.created,detail.createdAt],[t.deadline,detail.paymentDeadline]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{!detail.evidenceComplete&&<p>{t.incomplete}</p>}<h3>{t.terms}</h3><Evidence value={detail.terms} es={es}/><h3>{t.payment}</h3>{detail.payment?<Evidence value={detail.payment} es={es}/>:<p>{t.none}</p>}<h3>{t.fulfillment}</h3>{detail.fulfillment?<Evidence value={detail.fulfillment} es={es}/>:<p>{t.none}</p>}</>:<><form onSubmit={e=>{e.preventDefault();setFilters({...draft});setAfter(undefined)}}><label>{t.account}<input value={draft.account} onChange={e=>setDraft({...draft,account:e.target.value})}/></label>{(['kind','source','currency'] as const).map(k=><label key={k}>{t[k]}<select value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}><option value="">{t.all}</option>{(k==='kind'?['package','addon']:k==='source'?['STANDARD','OFFER']:['USD','CRC']).map(v=><option key={v} value={v}>{v==='package'?t.package:v==='addon'?t.addon:v}</option>)}</select></label>)}<button disabled={loading}>{t.refresh}</button></form>{!loading&&!error&&!rows.length&&<p>{t.empty}</p>}{rows.slice(0,25).map(o=><article key={o.id}><h3>{o.productId}</h3><p className="order-id">{o.id}</p><p>{o.currency} {o.total} · {o.source} · {state(o.state)}</p><p>{t.created}: {o.createdAt}</p><button disabled={loading} onClick={()=>void inspect(o.id)}>{t.inspect}</button></article>)}{after&&<button onClick={()=>setAfter(undefined)}>{t.first}</button>}{rows.length>25&&<button disabled={loading} onClick={()=>setAfter(rows[24].id)}>{t.next}</button>}<button disabled={loading} onClick={()=>setRefresh(x=>x+1)}>{es?'Actualizar':'Refresh'}</button></>}
 </div>
}
