'use client'
import {useEffect,useRef,useState} from 'react'
import {changeAdminOffer,readAdminOffers,readOfferTargets} from './offer-actions'
type Offer={id:string;targetType:'package'|'addon';targetId:string;state:string;revision:string;name_en:string;name_es:string;description_en:string;description_es:string;startsAt:string;endsAt:string;prices:Record<string,string>;tiers:{min:number;max:number;currency:string;unitRate:string}[];priceShape:string}
type Target={id:string;name_en:string;name_es:string|null;standardPrices:Record<string,string>;quantityTiers?:{min:number;max:number;unitRate:string}[]}
export default function AdminOffers({language,manage}:{language:'en'|'es';manage:boolean}){
 const es=language==='es',txt=(en:string,esText:string)=>es?esText:en
 const [rows,setRows]=useState<Offer[]>([]),[status,setStatus]=useState(''),[kind,setKind]=useState<'package'|'addon'>('addon'),[targets,setTargets]=useState<Target[]>([]),[draft,setDraft]=useState<Offer|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[after,setAfter]=useState<string|null>(null),[reason,setReason]=useState('')
 const [filterKind,setFilterKind]=useState(''),[filterCurrency,setFilterCurrency]=useState(''),[filterTarget,setFilterTarget]=useState('')
 const baseline=useRef('');const busyRef=useRef(busy);busyRef.current=busy
 const dirty=!!draft&&JSON.stringify(draft)!==baseline.current
 useEffect(()=>{const leave=(e:Event)=>{if(busyRef.current||(dirty&&!window.confirm(txt('Discard unsaved edits?','¿Descartar cambios sin guardar?'))))e.preventDefault()};const unload=(e:BeforeUnloadEvent)=>{if(dirty||busyRef.current)e.preventDefault()};window.addEventListener('admin-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('admin-leave',leave);window.removeEventListener('beforeunload',unload)}},[dirty,es])
 const stateLabel=(s:string)=>({draft:txt('Draft','Borrador'),scheduled:txt('Scheduled','Programada'),active:txt('Active','Activa'),ended:txt('Ended','Finalizada'),archived:txt('Archived','Archivada')}[s]??s)
 const localDate=(v:string)=>{if(!v||!Number.isFinite(Date.parse(v)))return '';return new Date(Date.parse(v)-6*60*60*1000).toISOString().slice(0,19)}
 const retry=useRef<{body:string;id:string}|null>(null)
 async function load(cursor:string|null=null){setBusy(true);const r=await readAdminOffers({status:status||null,after:cursor,kind:filterKind||null,currency:filterCurrency||null,target:filterTarget||null});if(r.ok&&Array.isArray(r.data?.offers)){setRows(r.data.offers);setAfter(cursor)}else setMessage(txt('Offers could not be loaded.','No se pudieron cargar las ofertas.'));setBusy(false)}
 useEffect(()=>{void load()},[status,filterKind,filterCurrency,filterTarget]) // Explicit navigation/filter reads; no polling.
 useEffect(()=>{let live=true;void readOfferTargets(kind).then(r=>{if(live&&r.ok&&Array.isArray(r.data))setTargets(r.data)});return()=>{live=false}},[kind])
 async function save(operation:string){if(!draft)return;if(!['create','configure'].includes(operation)&&dirty){setMessage(txt('Save or discard configuration edits before changing lifecycle.','Guarde o descarte los cambios antes de cambiar el ciclo de vida.'));return;}setBusy(true);setMessage('');const body:Record<string,unknown>={operation,...(draft.id?{id:draft.id,expected:draft.revision}:{targetType:kind,targetId:draft.targetId}),reason};
 if(operation==='create'||operation==='configure')Object.assign(body,{name_en:draft.name_en,name_es:draft.name_es,description_en:draft.description_en,description_es:draft.description_es,startsAt:draft.startsAt,endsAt:draft.endsAt,...(draft.targetId==='addon-bulk-listing-import'?{tiers:draft.tiers}:{prices:Object.fromEntries(Object.entries(draft.prices).filter(([,v])=>v!==''))})});
 const serialized=JSON.stringify(body);if(retry.current?.body!==serialized)retry.current={body:serialized,id:crypto.randomUUID()};const r=await changeAdminOffer(retry.current.id,body);setBusy(false);
 if(r.ok){retry.current=null;setDraft(null);setReason('');await load();setMessage(txt('Offer saved.','Oferta guardada.'))}else setMessage(r.code==='stale'?txt('This Offer changed. Reload it before saving.','Esta oferta cambió. Vuelva a cargarla antes de guardar.'):txt('The Offer could not be saved. Check the dates, prices and overlapping Offers. Retry uses the same request.','No se pudo guardar. Revise fechas, precios y ofertas superpuestas. El reintento usa la misma solicitud.'))}
 const target=targets.find(t=>t.id===draft?.targetId)
 return <div className="admin-offers"><p>{txt('Offers change temporary prices only. Checkout, payment and fulfillment remain unavailable.','Las ofertas cambian únicamente precios temporales. La compra, el pago y la entrega siguen deshabilitados.')}</p><p role="status">{message}</p>
 {!draft?<><label>{txt('Status','Estado')}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{txt('All','Todos')}</option>{[['draft','Draft','Borrador'],['scheduled','Scheduled','Programada'],['active','Active','Activa'],['ended','Ended','Finalizada'],['archived','Archived','Archivada']].map(([v,en,sp])=><option key={v} value={v}>{txt(en,sp)}</option>)}</select></label>
 <label>{txt('Product class filter','Filtro de clase')}<select value={filterKind} onChange={e=>{setFilterKind(e.target.value);setFilterTarget('')}}><option value="">{txt('All','Todos')}</option><option value="package">{txt('Packages','Paquetes')}</option><option value="addon">{txt('Add-ons','Complementos')}</option></select></label><label>{txt('Currency filter','Filtro de moneda')}<select value={filterCurrency} onChange={e=>setFilterCurrency(e.target.value)}><option value="">{txt('All','Todos')}</option><option>USD</option><option>CRC</option></select></label>
 <button disabled={busy} onClick={()=>void load()}>{txt('Refresh','Actualizar')}</button>{manage&&<button disabled={busy} onClick={()=>setDraft({id:'',revision:'',targetType:kind,targetId:'',state:'draft',name_en:'',name_es:'',description_en:'',description_es:'',startsAt:'',endsAt:'',prices:{USD:'',CRC:''},tiers:[{min:1,max:25,currency:'USD',unitRate:''},{min:26,max:100,currency:'USD',unitRate:''},{min:101,max:500,currency:'USD',unitRate:''}],priceShape:'scalar'})}>{txt('Create draft Offer','Crear oferta en borrador')}</button>}
 {filterTarget&&<button onClick={()=>setFilterTarget('')}>{txt('Clear product filter','Quitar filtro de producto')}</button>}{rows.length===0&&!busy&&<p>{txt('No Offers match these filters.','Ninguna oferta coincide con estos filtros.')}</p>}{rows.slice(0,25).map(o=><article key={o.id} className="admin-card"><h3>{es?o.name_es:o.name_en}</h3><p>{o.targetId} · {stateLabel(o.state)}</p><button disabled={busy} onClick={()=>setFilterTarget(o.targetId)}>{txt('Filter this product','Filtrar este producto')}</button><p>{new Date(o.startsAt).toLocaleString(es?'es-CR':'en-US',{timeZone:'America/Costa_Rica'})} — {new Date(o.endsAt).toLocaleString(es?'es-CR':'en-US',{timeZone:'America/Costa_Rica'})} (Costa Rica)</p><button onClick={()=>{baseline.current=JSON.stringify(o);setKind(o.targetType);setDraft(structuredClone(o))}}>{txt('Inspect / edit','Inspeccionar / editar')}</button></article>)}{after&&<button onClick={()=>void load(null)}>{txt('First page','Primera página')}</button>}{rows.length>25&&<button onClick={()=>void load(rows[24].id)}>{txt('Next','Siguiente')}</button>}</>:<>
 <button disabled={busy} onClick={()=>{if(!dirty||window.confirm(txt('Discard unsaved edits?','¿Descartar cambios sin guardar?')))setDraft(null)}}>{txt('Back','Volver')}</button>
 <form onSubmit={e=>{e.preventDefault();void save(draft.id?'configure':'create')}}><fieldset disabled={busy||!manage||['ended','archived'].includes(draft.state)}>
 {!draft.id&&<><label>{txt('Product class','Clase de producto')}<select value={kind} onChange={e=>{setKind(e.target.value as 'package'|'addon');setDraft({...draft,targetId:''})}}><option value="package">{txt('Package','Paquete')}</option><option value="addon">{txt('Add-on','Complemento')}</option></select></label><label>{txt('Product','Producto')}<select required value={draft.targetId} onChange={e=>setDraft({...draft,targetId:e.target.value})}><option value="">{txt('Choose a product','Seleccione un producto')}</option>{targets.slice(0,25).map(t=><option key={t.id} value={t.id}>{es?(t.name_es??t.name_en):t.name_en}</option>)}</select></label>{targets.length>25&&<button type="button" onClick={()=>void readOfferTargets(kind,targets[24].id).then(r=>{if(r.ok)setTargets(r.data)})}>{txt('More products','Más productos')}</button>}</>}
 <p>{txt('Standard prices','Precios estándar')}: {target?(target.quantityTiers?.length?target.quantityTiers.map(t=>`${t.min}–${t.max}: USD ${t.unitRate}`).join(' / '):Object.entries(target.standardPrices).map(([c,v])=>`${c} ${v}`).join(' / ')):draft.targetId}</p>
 {(['name_en','name_es','description_en','description_es'] as const).map(k=><label key={k}>{k.startsWith('name')?txt('Name','Nombre'):txt('Description','Descripción')} {k.endsWith('en')?'EN':'ES'}<input required={k.startsWith('name')} maxLength={k.startsWith('name')?300:4000} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <p>{txt('Dates and times use Costa Rica time (UTC−06:00).','Las fechas y horas usan la hora de Costa Rica (UTC−06:00).')}</p>
 <label>{txt('Starts','Inicio')}<input type="datetime-local" step="1" required value={localDate(draft.startsAt)} onChange={e=>setDraft({...draft,startsAt:e.target.value?e.target.value+'-06:00':''})}/></label><label>{txt('Ends (inclusive)','Fin (inclusive)')}<input type="datetime-local" step="1" required value={localDate(draft.endsAt)} onChange={e=>setDraft({...draft,endsAt:e.target.value?e.target.value+'-06:00':''})}/></label>
 {draft.targetId==='addon-bulk-listing-import'?draft.tiers.map((t,i)=><label key={t.min}>{t.min}–{t.max} USD<input required inputMode="decimal" value={t.unitRate} onChange={e=>setDraft({...draft,tiers:draft.tiers.map((v,j)=>j===i?{...v,unitRate:e.target.value}:v)})}/></label>):['USD','CRC'].filter(c=>c!=='CRC'||draft.targetId!=='addon-2026-founding-membership').map(c=><label key={c}>{c}<input inputMode="decimal" value={draft.prices[c]??''} onChange={e=>setDraft({...draft,prices:{...draft.prices,[c]:e.target.value}})}/></label>)}
 <button type="submit">{txt('Save configuration','Guardar configuración')}</button></fieldset></form>
 {draft.id&&manage&&draft.state!=='archived'&&<fieldset disabled={busy}><label>{txt('Reason','Motivo')}<input maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{draft.state==='draft'&&<button onClick={()=>void save('schedule')}>{txt('Schedule','Programar')}</button>}{draft.state!=='ended'&&<button onClick={()=>void save('end')}>{txt('End now','Finalizar ahora')}</button>}<button disabled={!reason.trim()} onClick={()=>void save('archive')}>{txt('Archive','Archivar')}</button></fieldset>}
 </>}
 </div>
}
