'use client'
import {useEffect,useRef,useState} from 'react'
import {readAdminPackages,changeAdminPackage} from './package-actions'
import type {PackageCatalog,PackageProjection} from './package-contract'
import type {AdminLanguage} from './admin-contract'
const copy={
 en:{loading:'Loading packages…',error:'The request could not be completed. Check your access and reload.',stale:'This package changed. Reload before editing.',reload:'Reload',empty:'No packages.',inspect:'Inspect',back:'Back to packages',next:'Next page',first:'First page',readOnly:'Read-only access',unavailable:'New acquisition is unavailable until commercial fulfillment is activated.',create:'Create Package',name:'Name',question:'Question',translation:'Spanish commercial copy not approved',identity:'Identity',version:'Configuration version',prices:'Standard prices',term:'Normal access term',month:'month',months:'months',capabilities:'Capabilities',state:'Lifecycle',save:'Save',reason:'Reason',archive:'Archive package',confirm:'Archive this package? Existing purchased rights remain unchanged.',dirty:'Discard unsaved changes?',saved:'Saved.',copy:'Commercial copy',config:'Capabilities and access term',inactive:'Inactive',active:'Active',draft:'Draft',archived:'Archived'},
 es:{loading:'Cargando paquetes…',error:'No se pudo completar la solicitud. Revise su acceso y vuelva a cargar.',stale:'Este paquete cambió. Vuelva a cargar antes de editar.',reload:'Volver a cargar',empty:'No hay paquetes.',inspect:'Ver detalles',back:'Volver a paquetes',next:'Página siguiente',first:'Primera página',readOnly:'Acceso de solo lectura',unavailable:'La adquisición no está disponible hasta activar el cumplimiento comercial.',create:'Crear paquete',name:'Nombre',question:'Pregunta',translation:'Texto comercial en español no aprobado',identity:'Identidad',version:'Versión de configuración',prices:'Precios estándar',term:'Plazo de acceso normal',month:'mes',months:'meses',capabilities:'Capacidades',state:'Ciclo de vida',save:'Guardar',reason:'Motivo',archive:'Archivar paquete',confirm:'¿Archivar este paquete? Los derechos adquiridos no cambian.',dirty:'¿Descartar cambios sin guardar?',saved:'Guardado.',copy:'Texto comercial',config:'Capacidades y plazo de acceso',inactive:'Inactivo',active:'Activo',draft:'Borrador',archived:'Archivado'}
}
export default function AdminPackages({language,manage}:{language:AdminLanguage;manage:boolean}){
 const t=copy[language],busyRef=useRef(false),ticket=useRef<{payload:string;id:string}|null>(null)
 const [catalog,setCatalog]=useState<PackageCatalog|null>(null),[selected,setSelected]=useState<PackageProjection|null>(null),[draft,setDraft]=useState<PackageProjection|null>(null)
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[cursor,setCursor]=useState<string|null>(null),[reason,setReason]=useState('')
 const [creating,setCreating]=useState(false),[createName,setCreateName]=useState(''),[createQuestion,setCreateQuestion]=useState('')
 const dirty=(creating&&(createName!==''||createQuestion!==''))||(!!selected&&JSON.stringify(selected)!==JSON.stringify(draft))
 async function load(after:string|null=cursor){setBusy(true);const r=await readAdminPackages(after);if(r.ok){setCatalog(r.data);setCursor(after);setSelected(null);setDraft(null);setMessage('')}else setMessage(t.error);setBusy(false)}
 useEffect(()=>{let alive=true;readAdminPackages(null).then(r=>{if(!alive)return;if(r.ok)setCatalog(r.data);else setMessage(copy[language].error)});return()=>{alive=false}},[]) // language changes do not reload evidence or discard drafts.
 useEffect(()=>{const leave=(e:Event)=>{if(busyRef.current||(dirty&&!window.confirm(t.dirty)))e.preventDefault()};const unload=(e:BeforeUnloadEvent)=>{if(dirty||busyRef.current){e.preventDefault()}};window.addEventListener('admin-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('admin-leave',leave);window.removeEventListener('beforeunload',unload)}},[dirty,t.dirty])
 async function save(operation:string,fields:Record<string,unknown>){
  if(!selected||busyRef.current)return
  // Each form saves one domain; never silently discard drafts in another domain.
  const remaining=structuredClone(draft),base=structuredClone(selected)
  if(remaining){if(operation==='copy')Object.assign(remaining,{name_en:base.name_en,name_es:base.name_es,question_en:base.question_en,question_es:base.question_es});if(operation==='price')remaining.standardPrices[fields.currency as 'USD'|'CRC']=base.standardPrices[fields.currency as 'USD'|'CRC'];if(operation==='configuration'){remaining.capabilities=base.capabilities;remaining.termQuantity=base.termQuantity}if(JSON.stringify(remaining)!==JSON.stringify(base)&&!window.confirm(t.dirty))return}
  const command={operation,package:selected.id,expected:selected.revision,reason,...fields},payload=JSON.stringify(command)
  if(ticket.current?.payload!==payload)ticket.current={payload,id:crypto.randomUUID()}
  busyRef.current=true;setBusy(true);setMessage('')
  try{const r=await changeAdminPackage(ticket.current.id,command);if(!r.ok){setMessage(r.code==='stale'?t.stale:t.error);return}ticket.current=null;await load();setMessage(t.saved)}finally{busyRef.current=false;setBusy(false)}
 }
 async function create(){
 if(busyRef.current)return;const command={operation:'create',name_en:createName,question_en:createQuestion},payload=JSON.stringify(command);if(ticket.current?.payload!==payload)ticket.current={payload,id:crypto.randomUUID()};busyRef.current=true;setBusy(true);try{const r=await changeAdminPackage(ticket.current.id,command);if(!r.ok){setMessage(t.error);return}ticket.current=null;setCreating(false);setCreateName('');setCreateQuestion('');await load(null);setMessage(t.saved+' '+(r.packageId??''))}finally{busyRef.current=false;setBusy(false)}
 }
 function back(){if(!dirty||window.confirm(t.dirty)){setSelected(null);setDraft(null);setReason('')}}
 const editable=manage&&selected?.state!=='archived'
 return <div aria-busy={busy}>
  <p>{t.unavailable}</p>{manage&&!selected&&<button disabled={busy} onClick={()=>{if(!dirty||window.confirm(t.dirty)){setCreating(!creating);setCreateName('');setCreateQuestion('')}}}>{t.create}</button>}{creating&&<form onSubmit={e=>{e.preventDefault();void create()}}><fieldset disabled={busy}><legend>{t.create}</legend><label>{t.name} EN<input required maxLength={300} value={createName} onChange={e=>setCreateName(e.target.value)}/></label><label>{t.question} EN<textarea required maxLength={4000} value={createQuestion} onChange={e=>setCreateQuestion(e.target.value)}/></label><button>{t.create}</button></fieldset></form>}{!manage&&<p>{t.readOnly}</p>}
  {message&&<p role="status">{message}</p>}<button disabled={busy} onClick={()=>{if(!dirty||window.confirm(t.dirty))void load()}}>{t.reload}</button>
  {!catalog&&!message&&<p>{t.loading}</p>}
  {selected&&draft&&catalog?<>
   <button disabled={busy} onClick={back}>{t.back}</button><h3>{language==='es'?(selected.name_es??selected.name_en):selected.name_en}</h3>
   <p>{t.identity}: <code>{selected.id}</code></p><p>{t.version}: {selected.version}</p><p>{t.state}: {t[selected.state]}</p>
   <form onSubmit={e=>{e.preventDefault();void save('copy',{name_en:draft.name_en,name_es:draft.name_es,question_en:draft.question_en,question_es:draft.question_es})}}><fieldset disabled={!editable||busy}><legend>{t.copy}</legend>
   {(['name_en','name_es','question_en','question_es'] as const).map(k=><label key={k}>{k.startsWith('name')?t.name:t.question} {k.endsWith('es')?'ES':'EN'}<textarea maxLength={k.startsWith('name')?300:4000} required={k.endsWith('en')} value={draft[k]??''} onChange={e=>setDraft({...draft,[k]:e.target.value||null})}/></label>)}
   {(!draft.name_es||!draft.question_es)&&<p>{t.translation}</p>}{editable&&<button>{t.save}</button>}</fieldset></form>
   <fieldset disabled={!editable||busy}><legend>{t.prices}</legend>{(['USD','CRC'] as const).map(currency=><form key={currency} onSubmit={e=>{e.preventDefault();void save('price',{currency,amount:draft.standardPrices[currency]})}}><label>{currency}<input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" value={draft.standardPrices[currency]??''} onChange={e=>setDraft({...draft,standardPrices:{...draft.standardPrices,[currency]:e.target.value}})}/></label>{editable&&<button>{t.save} {currency}</button>}</form>)}</fieldset>
   <form onSubmit={e=>{e.preventDefault();void save('configuration',{capabilities:draft.capabilities,termQuantity:draft.termQuantity})}}><fieldset disabled={!editable||busy}><legend>{t.config}</legend><label>{t.term} ({t.months})<input type="number" min="1" max="120" step="1" required value={draft.termQuantity} onChange={e=>setDraft({...draft,termQuantity:Number(e.target.value)})}/></label>
   {catalog.capabilities.map(c=><label key={c.id} style={{flexDirection:'row',alignItems:'center'}}><input type="checkbox" checked={draft.capabilities.includes(c.id)} onChange={e=>setDraft({...draft,capabilities:e.target.checked?[...draft.capabilities,c.id].sort():draft.capabilities.filter(v=>v!==c.id)})}/>{c[language]}</label>)}{editable&&<button>{t.save}</button>}</fieldset></form>
   {editable&&<fieldset disabled={busy}><legend>{t.state}</legend><label>{t.reason}<input maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="admin-actions" style={{flexWrap:'wrap'}}>{(['active','inactive'] as const).filter(s=>s!==selected.state).map(s=><button key={s} onClick={()=>void save('lifecycle',{state:s})}>{t[s]}</button>)}<button disabled={!reason.trim()} onClick={()=>{if(window.confirm(t.confirm))void save('lifecycle',{state:'archived'})}}>{t.archive}</button></div></fieldset>}
  </>:catalog&&<>
   {catalog.packages.length===0?<p>{t.empty}</p>:<div>{catalog.packages.slice(0,25).map(p=><article key={p.id} style={{padding:'1rem',margin:'1rem 0',border:'1px solid var(--border)',borderRadius:8}}><h3>{language==='es'?(p.name_es??p.name_en):p.name_en}</h3><p><code>{p.id}</code></p><p>{t[p.state]} · {p.capabilities.length} {t.capabilities} · {p.termQuantity} {p.termQuantity===1?t.month:t.months}</p><p>USD {p.standardPrices.USD??'—'} / CRC {p.standardPrices.CRC??'—'}</p>{(!p.name_es||!p.question_es)&&<p>{t.translation}</p>}<button disabled={busy} onClick={()=>{if(dirty&&!window.confirm(t.dirty))return;setCreating(false);setCreateName('');setCreateQuestion('');setSelected(p);setDraft(structuredClone(p));setReason('');setMessage('')}}>{t.inspect}</button></article>)}</div>}
   <div className="admin-actions">{cursor&&<button disabled={busy} onClick={()=>void load(null)}>{t.first}</button>}{catalog.packages.length>25&&<button disabled={busy} onClick={()=>void load(catalog.packages[24].id)}>{t.next}</button>}</div>
  </>}
 </div>
}
