"use client"
import {useEffect,useRef,useState} from 'react'
import {readSinpe,reviewSinpe,retrySinpeFulfillment} from './payment-actions'
import './orders.css'
type Payment={accountId?:string;decisionAt?:string;reason?:string;lateEvidence?:boolean;fulfillmentState?:string;id:string;orderId:string;state:string;expectedAmount:string;currency:string;submittedAt:string;deadline?:string;receivingAccount?:string;customerEvidence?:Record<string,unknown>;review?:Record<string,unknown>;order?:Record<string,unknown>}
const stateNames:Record<string,[string,string]>={REVIEW_PENDING:['Review pending','Pendiente de revisión'],APPROVED:['Approved / matched','Aprobado / aplicado'],RECEIVED_UNMATCHED:['Received funds — NEEDS RESOLUTION','Fondos recibidos — REQUIERE RESOLUCIÓN'],REJECTED:['Rejected','Rechazado']}
const reasonNames:Record<string,[string,string]>={verified:['Verified exact match','Coincidencia exacta verificada'],insufficient_evidence:['Insufficient evidence','Evidencia insuficiente'],reference_mismatch:['Reference mismatch','Referencia no coincide'],amount_mismatch:['Amount mismatch','Importe no coincide'],currency_mismatch:['Currency mismatch','Moneda no coincide'],late_receipt:['Funds received late','Fondos recibidos tarde'],late_submission:['Evidence submitted late','Evidencia enviada tarde'],wrong_order:['Wrong Order','Pedido incorrecto'],timing_not_established:['Receipt time not established','Hora de recepción no establecida'],order_already_paid:['Order already paid','Pedido ya pagado']}
const evidenceLabels:Record<string,[string,string]>={reference:['Submitted reference','Referencia enviada'],senderName:['Sender name','Nombre del remitente'],senderPhone:['Sender phone','Teléfono del remitente'],claimedPaymentDate:['Customer-claimed date','Fecha declarada por el cliente'],actorId:['Reviewer account','Cuenta del revisor'],bankReference:['Verified bank reference','Referencia bancaria verificada'],receivedAt:['Verified receipt time','Fecha de recepción verificada'],amount:['Verified amount','Importe verificado'],currency:['Currency','Moneda'],bankEvidence:['Receiving-bank evidence','Evidencia del banco receptor'],receivingAccount:['Receiving account identity','Identidad de cuenta receptora']}
function PaymentEvidence({value,es}:{value:Record<string,unknown>|undefined;es:boolean}){if(!value||Object.values(value).every(v=>v===null))return <p>{es?'No hay evidencia registrada.':'No evidence recorded.'}</p>;return <dl className="order-evidence">{Object.entries(value).map(([k,v])=><div key={k}><dt>{evidenceLabels[k]?.[es?1:0]||k}</dt><dd>{v===null?'—':String(v)}</dd></div>)}</dl>}
export default function AdminPayments({language,review}:{language:'en'|'es';review:boolean}){
 const es=language==='es',t=(a:string,b:string)=>es?b:a;const[rows,setRows]=useState<Payment[]>([]),[detail,setDetail]=useState<Payment|null>(null),[state,setState]=useState(''),[order,setOrder]=useState(''),[filter,setFilter]=useState({state:'',order:''}),[after,setAfter]=useState<string>(),[refresh,setRefresh]=useState(0),[error,setError]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Record<string,string>>({disposition:'',reason:''});const seq=useRef(0),receipt=useRef<{payload:string;id:string}|null>(null);
 useEffect(()=>{const n=++seq.current;setBusy(true);setError(false);setDetail(null);void readSinpe({...filter,order:filter.order||undefined,after}).then(r=>{if(n!==seq.current)return;setRows(r.ok&&Array.isArray(r.data)?r.data:[]);setError(!r.ok);setBusy(false)});return()=>{seq.current++}},[filter,after,refresh]);
 async function inspect(id:string){const n=++seq.current;setBusy(true);setError(false);const r=await readSinpe({id});if(n!==seq.current)return;if(r.ok&&r.data){setDetail(r.data);setDraft({disposition:'',reason:'',receivingAccount:r.data.receivingAccount||'',bankReference:'',amount:'',currency:'',receivedAt:'',bankEvidence:''});receipt.current=null}else setError(true);setBusy(false)}
 async function decide(){if(!detail||busy)return;const command=draft.disposition==='REJECTED'?{disposition:draft.disposition,reason:draft.reason}:draft;const payload=JSON.stringify(command);if(receipt.current?.payload!==payload)receipt.current={payload,id:crypto.randomUUID()};setBusy(true);const r=await reviewSinpe(detail.id,receipt.current.id,command);setBusy(false);setError(!r.ok);if(r.ok)await inspect(detail.id)}
 const fields=[['receivingAccount','Receiving account identity','Identidad de cuenta receptora'],['bankReference','Verified bank reference','Referencia bancaria verificada'],['amount','Verified received amount','Importe recibido verificado'],['currency','Verified currency (USD / CRC)','Moneda verificada (USD / CRC)'],['receivedAt','Verified receipt time (ISO with timezone)','Fecha de recepción verificada (ISO con zona horaria)'],['bankEvidence','Receiving-bank evidence / exact timestamp source','Evidencia del banco receptor / fuente de fecha exacta']];
 return <div className="admin-orders"><p>{t('Payment is separate from Order and fulfillment. Verify against receiving-bank evidence.','El pago es independiente del pedido y de la entrega. Verifique con evidencia del banco receptor.')}</p>{error&&<p role="alert">{t('Unable to complete request. Reload evidence; retry with unchanged input after an uncertain response.','No se pudo completar. Vuelva a cargar la evidencia; reintente sin cambios si la respuesta fue incierta.')}</p>}{busy&&<p role="status">{t('Loading…','Cargando…')}</p>}
 {detail?<><button disabled={busy} onClick={()=>setDetail(null)}>{t('Back','Volver')}</button><h3>{stateNames[detail.state]?.[es?1:0]}</h3><p className="order-id">{detail.id}</p>{detail.lateEvidence&&<p role="status">{t("LATE EVIDENCE / EXPIRED ORDER — review only; normal approval unavailable","EVIDENCIA TARDÍA / PEDIDO VENCIDO — solo revisión; aprobación normal no disponible")}</p>}<p>{t('Fulfillment','Entrega')}: {detail.fulfillmentState==='PENDING'?t('PENDING — payment approval does not activate access','PENDIENTE — la aprobación del pago no activa el acceso'):detail.fulfillmentState==='COMPLETE'?t('Complete','Completada'):detail.fulfillmentState==='FAILED'?t('Failed — payment remains approved','Fallida — el pago sigue aprobado'):t('Not eligible','No elegible')}</p><dl className="order-evidence">{[[t("Order identity","Identidad del pedido"),detail.orderId],[t("Customer account","Cuenta del cliente"),detail.accountId],[t("Decision time","Fecha de decisión"),detail.decisionAt],[t("Reason","Motivo"),detail.reason?(reasonNames[detail.reason]?.[es?1:0]||detail.reason):undefined]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||"—"}</dd></div>)}</dl><p>{detail.expectedAmount} {detail.currency}</p><p>{t('Order deadline','Fecha límite')}: {detail.deadline}</p><p>{t('Submitted','Enviado')}: {detail.submittedAt}</p>{(['customerEvidence','review','order'] as const).map(k=><section key={k}><h4>{k==='customerEvidence'?t('Immutable customer evidence','Evidencia inmutable del cliente'):k==='review'?t('Reviewer evidence','Evidencia del revisor'):t('Immutable Order / payment / fulfillment','Pedido inmutable / pago / entrega')}</h4><>{k!=='order'?<PaymentEvidence value={detail[k]} es={es}/>:<details><summary>{t("Exact immutable Order evidence","Evidencia exacta e inmutable del pedido")}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(detail[k],null,2)}</pre></details>}</></section>)}
 {review&&detail.state==='APPROVED'&&detail.fulfillmentState!=='COMPLETE'&&<button disabled={busy} onClick={async()=>{setBusy(true);const result=await retrySinpeFulfillment(detail.orderId,crypto.randomUUID());setError(!result.ok);setBusy(false);if(result.ok)await inspect(detail.id)}}>{t('Attempt fulfillment','Intentar entrega')}</button>}
 {review&&detail.state==='REVIEW_PENDING'&&<form onSubmit={e=>{e.preventDefault();void decide()}}><label>{t('Decision','Decisión')}<select required value={draft.disposition} onChange={e=>setDraft({...draft,disposition:e.target.value,reason:''})}><option value="">{t('Select explicitly','Seleccione explícitamente')}</option>{Object.entries(stateNames).filter(([k])=>k!=='REVIEW_PENDING'&&(!detail.lateEvidence||k!=='APPROVED')).map(([k,v])=><option key={k} value={k}>{v[es?1:0]}</option>)}</select></label><label>{t('Reason','Motivo')}<select required value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}><option value="">—</option>{(draft.disposition==='APPROVED'?['verified']:draft.disposition==='REJECTED'?['insufficient_evidence','reference_mismatch']:['amount_mismatch','currency_mismatch','late_receipt','late_submission','wrong_order','timing_not_established','order_already_paid']).map(x=><option key={x} value={x}>{reasonNames[x]?.[es?1:0]||x}</option>)}</select></label>{draft.disposition&&draft.disposition!=='REJECTED'&&fields.map(([key,en,esLabel])=><label key={key}>{t(en,esLabel)}<input required={key!=='receivedAt'||draft.disposition==='APPROVED'} value={draft[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<button disabled={busy||!draft.disposition}>{t('Record review decision','Registrar decisión')}</button></form>}</>:<><form onSubmit={e=>{e.preventDefault();setFilter({state,order});setAfter(undefined)}}><label>{t('Review state','Estado')}<select value={state} onChange={e=>setState(e.target.value)}><option value="">{t('All','Todos')}</option>{Object.entries(stateNames).map(([k,v])=><option key={k} value={k}>{v[es?1:0]}</option>)}</select></label><label>{t('Order identity','Identidad del pedido')}<input value={order} onChange={e=>setOrder(e.target.value)}/></label><button disabled={busy}>{t('Apply filters','Aplicar filtros')}</button></form>{!busy&&!error&&!rows.length&&<p>{t('No canonical payment attempts.','No hay intentos de pago canónicos.')}</p>}{rows.slice(0,25).map(p=><article key={p.id}><h3>{stateNames[p.state]?.[es?1:0]}</h3><p className="order-id">{p.orderId}</p>{p.lateEvidence&&<p>{t("LATE EVIDENCE / EXPIRED ORDER","EVIDENCIA TARDÍA / PEDIDO VENCIDO")}</p>}<p>{p.expectedAmount} {p.currency}</p><button disabled={busy} onClick={()=>void inspect(p.id)}>{t('Inspect','Inspeccionar')}</button></article>)}{after&&<button onClick={()=>setAfter(undefined)}>{t('First page','Primera página')}</button>}{rows.length>25&&<button onClick={()=>setAfter(rows[24].id)}>{t('Next page','Página siguiente')}</button>}<button disabled={busy} onClick={()=>setRefresh(x=>x+1)}>{t('Refresh','Actualizar')}</button></>}
 </div>
}
