'use client'
import {useEffect,useState,useRef} from 'react'
import {adminCommand,adminRead} from './actions'
import type {AdminLanguage} from './admin-contract'
type Term={id:string;official_code:string;term_name:string;term_name_en:string;term_name_es:string}
export default function AdminCreate({language,done,cancel}:{language:AdminLanguage;done:(id:string)=>void;cancel:()=>void}){
 const request=useRef<string|null>(null)
 const es=language==='es',t=(en:string,sp:string)=>es?sp:en
 const [origin,setOrigin]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[options,setOptions]=useState<Record<string,Term[]>>({}),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false)
 useEffect(()=>{let live=true;Promise.all(['province','property_type'].map(async dimension=>{const r=await adminRead({mode:'options',dimension});return [dimension,r.ok?r.data:[]] as const})).then(entries=>{if(live)setOptions(Object.fromEntries(entries))});return()=>{live=false}},[])
 useEffect(()=>{const dirty=!!origin||Object.keys(values).length>0;const leave=(e:Event)=>{if(dirty&&!window.confirm(es?'¿Descartar la creación sin guardar?':'Discard this unsaved listing?'))e.preventDefault()};const unload=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener('admin-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('admin-leave',leave);window.removeEventListener('beforeunload',unload)}},[origin,values,es])
 async function geography(k:string,value:string){setValues(v=>({...v,[k]:value,...(k==='province'?{canton:'',district:''}:k==='canton'?{district:''}:{})}));if(k==='district')return;const child=k==='province'?'canton':'district';setOptions(o=>({...o,[child]:[],...(k==='province'?{district:[]}:{})}));if(value){const r=await adminRead({mode:'options',dimension:child,parent:value});if(r.ok)setOptions(o=>({...o,[child]:r.data}))}}
 const input=(key:string,label:string,type='text',required=true)=><label>{label}<input required={required} type={type} step={type==='number'?'any':undefined} min={type==='number'?'0.000000001':undefined} maxLength={key==='title'?512:256} value={values[key]||''} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setFailed(false);const geo:Record<string,string|null>={};for(const k of ['province','canton','district'])geo[k]=options[k]?.find(o=>o.id===values[k])?.official_code??null;const measurements:Record<string,unknown>={};for(const k of ['property_area','construction_area'])if(values[k])measurements[k]={value:values[k]};const command:Record<string,unknown>={operation:'create',origin,input:{transaction:values.transaction,geography:geo,semantics:{property_type:[values.property_type]},measurements,content:{title:values.title||''},...(values.amount?{money:{amount:values.amount,currency:values.currency}}:{})}};if(origin==='customer')command.customer=values.customer;if(origin==='imported')command.source={source_name:values.source_name,source_listing_id:values.source_listing_id,observation_id:values.observation_id,observed_at:values.observed_at,source_type:values.source_type};request.current??=crypto.randomUUID();const r=await adminCommand(request.current,command);setBusy(false);if(r.ok&&r.data.listing_id)done(r.data.listing_id);else setFailed(true)}
 return <form className="admin-filters" onSubmit={create}><label>{t('Creation path — choose explicitly','Origen — elija explícitamente')}<select required value={origin} onChange={e=>{setOrigin(e.target.value);setValues({})}}><option value="">{t('Choose…','Elija…')}</option><option value="customer">{t('Customer-owned','De un cliente')}</option><option value="system">{t('System / Manual','Sistema / Manual')}</option><option value="imported">{t('Source-managed / Imported','Gestionada por fuente / Importada')}</option></select></label>
 {origin&&<>{origin==='customer'&&input('customer',t('Existing customer account UUID (listing owner)','UUID de una cuenta existente (titular)'))}{origin==='system'&&<p>{t('No customer owner or external source identity.','Sin titular cliente ni identidad de fuente externa.')}</p>}{origin==='imported'&&<>{input('source_name',t('Source namespace','Espacio de nombres de la fuente'))}{input('source_listing_id',t('Source listing ID','ID de propiedad en la fuente'))}{input('observation_id',t('Source observation ID','ID de observación'))}{input('observed_at',t('Observation time (ISO 8601 with timezone)','Fecha de observación (ISO 8601 con zona horaria)'))}<label>{t('Source type','Tipo de fuente')}<select required value={values.source_type||''} onChange={e=>setValues(v=>({...v,source_type:e.target.value}))}><option value="">{t('Choose…','Elija…')}</option>{[['realtor','Real estate agent','Agente inmobiliario'],['bank_remate','Bank foreclosure','Remate bancario'],['developer','Developer','Desarrollador'],['brokerage','Brokerage','Inmobiliaria'],['government','Government','Gobierno'],['owner_direct','Direct owner','Propietario directo'],['unknown','Unknown','Desconocido']].map(([v,en,sp])=><option key={v} value={v}>{t(en,sp)}</option>)}</select></label></>}
 {input('title',t('Title','Título'))}<label>{t('Transaction','Transacción')}<select required value={values.transaction||''} onChange={e=>setValues(v=>({...v,transaction:e.target.value}))}><option value="">{t('Choose…','Elija…')}</option><option value="sale">{t('Sale','Venta')}</option><option value="rent">{t('Rent','Alquiler')}</option></select></label>
 {(['province','canton','district','property_type'] as const).map((k,i)=><label key={k}>{[t('Province','Provincia'),t('Canton','Cantón'),t('District (optional)','Distrito (opcional)'),t('Property Type','Tipo de propiedad')][i]}<select required={k!=='district'} value={values[k]||''} onChange={e=>k==='property_type'?setValues(v=>({...v,[k]:e.target.value})):geography(k,e.target.value)}><option value="">{t('Choose…','Elija…')}</option>{(options[k]||[]).map(o=><option key={o.id} value={o.id}>{(es?o.term_name_es:o.term_name_en)||o.term_name}</option>)}</select></label>)}
 {input('property_area',t('Exact Property Area m² (optional)','Área exacta del terreno m² (opcional)'),'number',false)}{input('construction_area',t('Exact Construction Area m² (optional)','Área exacta de construcción m² (opcional)'),'number',false)}{input('amount',t('Original asking amount (optional)','Precio solicitado original (opcional)'),'number',false)}<label>{t('Currency','Moneda')}<select required={!!values.amount} value={values.currency||''} onChange={e=>setValues(v=>({...v,currency:e.target.value}))}><option value="">{t('Choose…','Elija…')}</option><option>CRC</option><option>USD</option></select></label><button disabled={busy}>{t('Create draft','Crear borrador')}</button></>}
 <button type="button" disabled={busy} onClick={()=>{if(window.dispatchEvent(new Event('admin-leave',{cancelable:true})))cancel()}}>{t('Cancel','Cancelar')}</button>{failed&&<p role="alert">{t('Creation failed. Check the inputs and access.','No se pudo crear. Revise los datos y el acceso.')}</p>}</form>
}
