'use client'
import {useEffect,useRef,useState} from 'react'
import {canCreatePushSubscription,inspectPush,subscribeToPush,unsubscribeFromPush,type PushStatus} from '@/lib/browser-push'
const copy={en:{unavailable:'New Push registrations are currently unavailable.',title:'Push notifications',loading:'Checking browser registration…',unsupported:'Push is unavailable in this browser or device.',permission:'Notification permission has not been requested.',denied:'Permission denied. Change notification permission in your browser or device settings to enable Push later.',off:'Push is off in this browser.',active:'Push registration is active for this account and browser.',cleanup:'Server delivery is off. Browser subscription cleanup is pending.',error:'Push state could not be confirmed. Retry. If this browser was used by another account, sign in to that account and disable Push first; registrations are not transferred.',enable:'Enable Push notifications',disable:'Disable Push notifications',clean:'Finish browser cleanup',retry:'Check again',enabling:'Enabling…',disabling:'Disabling…',delivery:'This setting manages Push registration. Notification delivery is not available yet.'},es:{unavailable:'Los nuevos registros push no están disponibles actualmente.',title:'Notificaciones push',loading:'Comprobando el registro del navegador…',unsupported:'Push no está disponible en este navegador o dispositivo.',permission:'Aún no se ha solicitado permiso para notificaciones.',denied:'Permiso denegado. Cambie el permiso de notificaciones en la configuración del navegador o dispositivo para activar Push más adelante.',off:'Push está desactivado en este navegador.',active:'El registro push está activo para esta cuenta y este navegador.',cleanup:'El envío del servidor está desactivado. Falta limpiar la suscripción del navegador.',error:'No se pudo confirmar el estado de Push. Reintente. Si otra cuenta usó este navegador, inicie sesión en esa cuenta y desactive Push primero; los registros no se transfieren.',enable:'Activar notificaciones push',disable:'Desactivar notificaciones push',clean:'Completar limpieza del navegador',retry:'Comprobar de nuevo',enabling:'Activando…',disabling:'Desactivando…',delivery:'Esta opción administra el registro push. El envío de notificaciones aún no está disponible.'}}
export default function AccountPushSettings({language}:{language:'en'|'es'}){
 const t=copy[language],[status,setStatus]=useState<PushStatus|null>(null),[busy,setBusy]=useState<'enable'|'disable'|'check'|null>('check'),running=useRef(false),alive=useRef(true)
 async function perform(op:'enable'|'disable'|'check'){if(running.current)return;running.current=true;setBusy(op);try{const s=await(op==='enable'?subscribeToPush():op==='disable'?unsubscribeFromPush():inspectPush());if(alive.current)setStatus(s)}catch{if(alive.current)setStatus('error')}finally{running.current=false;if(alive.current)setBusy(null)}}
 useEffect(()=>{alive.current=true;void perform('check');const focus=()=>{void perform('check')};window.addEventListener('focus',focus);return()=>{alive.current=false;window.removeEventListener('focus',focus)}},[])
 return <div className="push-settings"><h3>{t.title}</h3><p id="push-status" role="status">{busy==='enable'?t.enabling:busy==='disable'?t.disabling:busy==='check'?t.loading:status?t[status]:t.loading}</p>
 {canCreatePushSubscription()&&(status==='off'||status==='permission')&&<button type="button" disabled={!!busy} aria-describedby="push-status" onClick={()=>perform('enable')}>{t.enable}</button>}
 {(status==='active'||status==='cleanup')&&<button type="button" disabled={!!busy} aria-describedby="push-status" onClick={()=>perform('disable')}>{status==='cleanup'?t.clean:t.disable}</button>}
 {status!=='unsupported'&&<button type="button" disabled={!!busy} onClick={()=>perform('check')}>{t.retry}</button>}
 <p>{t.delivery}</p><style jsx>{`.push-settings{min-width:0}.push-settings p{overflow-wrap:anywhere;line-height:1.5}.push-settings button{max-width:100%;min-height:44px;margin:4px 8px 4px 0;padding:10px 12px;background:transparent;color:inherit;border:1px solid currentColor;border-radius:9px;font:inherit;white-space:normal}.push-settings :focus-visible{outline:3px solid #ff6b00;outline-offset:3px}`}</style></div>
}
