'use client'
import {useEffect,useRef,useState} from 'react'
import {commercialCatalog,purchaseCommercial,readMyCommercial} from '@/app/commercial/actions'
import Link from 'next/link'
import EmailAuthModal from './EmailAuthModal'
import './customer-commercial.css'
type Language='en'|'es'
export function CommercialCatalog({language,listing,onOrder}:{language:Language;listing?:string;onOrder?:(id:string)=>void}){
 const es=language==='es',t=(en:string,sp:string)=>es?sp:en
 const [currency,setCurrency]=useState<'USD'|'CRC'>('USD'),[after,setAfter]=useState<string|null>(null),[data,setData]=useState<Awaited<ReturnType<typeof commercialCatalog>>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[order,setOrder]=useState('')
 const [signIn,setSignIn]=useState(false)
 const retry=useRef<{key:string;id:string}|null>(null)
 useEffect(()=>{const c=new URLSearchParams(window.location.search).get('currency');if(c==='USD'||c==='CRC')setCurrency(c)},[])
 useEffect(()=>{let live=true;setData(null);commercialCatalog(listing?'addon':'package',currency,after,listing).then(r=>{if(live)setData(r)}).catch(()=>{if(live)setData({ok:false})});return()=>{live=false}},[listing,currency,after])
 async function purchase(product:string){if(busy)return;setBusy(true);setError('');const key=JSON.stringify({product,currency,listing});if(retry.current?.key!==key){const storeKey='twuanis-commercial-intent:'+key;let id=sessionStorage.getItem(storeKey);if(!id){id=crypto.randomUUID();sessionStorage.setItem(storeKey,id)}retry.current={key,id}};try{const r=await purchaseCommercial({request:retry.current.id,kind:listing?'addon':'package',product,currency,...(listing?{listing}:{})});setBusy(false);if(r.ok){sessionStorage.removeItem('twuanis-commercial-intent:'+key);setOrder(r.id);onOrder?.(r.id)}else setError(r.reason)}catch{setError('unavailable')}finally{setBusy(false)}}
 return <section className="customer-commercial">{signIn&&<EmailAuthModal onClose={()=>setSignIn(false)} redirectTo={window.location.pathname+'?currency='+currency+'&lang='+language}/>}<h2>{listing?t('Enhance this listing (optional)','Mejore este anuncio (opcional)'):t('Intelligence Packages','Paquetes de inteligencia')}</h2>
 {listing&&<p>{t('Choose at most one Add-on. Payment does not prevent ordinary publication.','Elija como máximo un complemento. El pago no impide la publicación ordinaria.')}</p>}
 <label>{t('Currency','Moneda')} <select value={currency} disabled={busy} onChange={e=>{setCurrency(e.target.value as 'USD'|'CRC');setAfter(null)}}><option>USD</option><option>CRC</option></select></label>
 {error&&<p role="alert">{error==='authentication'?<>{t('Sign in to continue.','Inicie sesión para continuar.')} <button onClick={()=>setSignIn(true)}>{t('Sign in','Iniciar sesión')}</button></>:error==='inactive'?t('Purchasing is not available yet.','La compra aún no está disponible.'):t('This purchase is unavailable or another acquisition is in progress. Check your Orders before retrying unchanged input.','Esta compra no está disponible o hay otra adquisición en curso. Revise sus pedidos antes de reintentar sin cambios.')}</p>}
 {data?.ok&&data.availability?.order&&<p>{t('An acquisition is already in progress.','Hay una adquisición en curso.')} <Link href={`/commercial/${data.availability.order}?lang=${language}`}>{t('View existing Order','Ver pedido existente')}</Link></p>}
 {order?<p role="status">{t('Order created. Publication remains independent.','Pedido creado. La publicación es independiente.')} <Link href={`/commercial/${order}?lang=${language}`}>{t('View Order / payment','Ver pedido / pago')}</Link></p>:!data?<p role="status">{t('Loading authoritative prices…','Cargando precios oficiales…')}</p>:!data.ok?<p role="alert">{t('Prices could not be loaded. Reload to retry.','No se pudieron cargar los precios. Vuelva a cargar para reintentar.')}</p>:<div className="commercial-grid">{data.products.filter(p=>!listing||p.termKind==='elapsed_days').map(p=><article key={p.id}><h3>{es?(p.nameES||p.nameEN):p.nameEN}</h3><p>{es?(p.questionES||p.questionEN):p.questionEN}</p>{Array.isArray(p.capabilities)&&p.capabilities.length>0&&<ul>{p.capabilities.map((c:{id:string;en:string;es:string})=><li key={c.id}>{es?c.es:c.en}</li>)}</ul>}<p>{t('Standard price','Precio estándar')}: {currency} {p.pricing.standardPrice??'—'}</p>{p.pricing.source==='OFFER'&&<p><strong>{t('Offer price','Precio de oferta')}: {currency} {p.pricing.effectivePrice}</strong></p>}{p.termQuantity&&<p>{p.termQuantity} {t('calendar month(s)','mes(es) calendario')}</p>}{listing&&<p>{t('Availability is rechecked at Order creation and fulfillment. No capacity is reserved by payment.','La disponibilidad se verifica al crear el pedido y al entregar el beneficio. El pago no reserva capacidad.')}</p>}{p.durationDays&&<p>{p.durationDays} {t('days from successful fulfillment','días desde la entrega efectiva')}</p>}
 {data.enabled&&p.pricing.available&&(!listing||data.availability?.products.some(a=>a.id===p.id&&a.available))?<button disabled={busy} onClick={()=>void purchase(p.id)}>{t('Create Order','Crear pedido')}</button>:<p>{t('Acquisition unavailable','Adquisición no disponible')}</p>}</article>)}</div>}
 {data?.ok&&data.next&&!order&&<button disabled={busy} onClick={()=>setAfter(data.next)}>{t('Next','Siguiente')}</button>}{after&&<button onClick={()=>setAfter(null)}>{t('First page','Primera página')}</button>}
 </section>
}
export default function CustomerCommercial({language}:{language:Language}){
 const es=language==='es',t=(en:string,sp:string)=>es?sp:en
 const [area,setArea]=useState('rights'),[after,setAfter]=useState<string|null>(null),[history,setHistory]=useState(false),[revision,setRevision]=useState(0),[listing,setListing]=useState<string>(),[data,setData]=useState<Awaited<ReturnType<typeof readMyCommercial>>|null>(null)
 useEffect(()=>{let live=true;setData(null);readMyCommercial(area,after,null,null,history).then(r=>{if(live)setData(r)}).catch(()=>{if(live)setData({ok:false,reason:'unavailable'})});return()=>{live=false}},[area,after,history,revision])
 const date=(s:string)=>new Date(s).toLocaleString(es?'es-CR':'en-US',{timeZone:'America/Costa_Rica'})
 const names:Record<string,string>={ACTIVE:t('Active','Activo'),SCHEDULED:t('Scheduled','Programado'),EXPIRED:t('Expired','Vencido'),REVOKED:t('Revoked','Revocado'),REVIEW_PENDING:t('Evidence submitted — review pending','Evidencia enviada — revisión pendiente'),APPROVED:t('Payment approved','Pago aprobado'),RECEIVED_UNMATCHED:t('Funds received — resolution required','Fondos recibidos — requieren resolución'),REJECTED:t('Evidence rejected','Evidencia rechazada'),expired:t('Order expired','Pedido vencido'),pending:t('Payment due','Pago pendiente'),paid:t('Payment approved','Pago aprobado')}
 return <section className="customer-commercial"><h2>{t('Your commercial activity','Su actividad comercial')}</h2><nav aria-label={t('Commercial sections','Secciones comerciales')}>{[['rights','Benefits','Beneficios'],['orders','Orders','Pedidos'],['payments','Payments','Pagos'],['listings','Listing Add-ons','Complementos de anuncios'],['legacy','Existing legacy access','Acceso anterior']].map(([v,en,sp])=><button key={v} aria-pressed={area===v} onClick={()=>{setArea(v);setAfter(null);setListing(undefined)}}>{t(en,sp)}</button>)}</nav>
 {area==='rights'&&<label><input type="checkbox" checked={history} onChange={e=>{setHistory(e.target.checked);setAfter(null)}}/>{t('Include expired/revoked history','Incluir historial vencido/revocado')}</label>}<button onClick={()=>setRevision(x=>x+1)}>{t('Refresh','Actualizar')}</button>
 {!data?<p role="status">{t('Loading…','Cargando…')}</p>:!data.ok?<p role="alert">{t('Commercial information could not be loaded. Sign in and retry.','No se pudo cargar la información comercial. Inicie sesión y reintente.')}</p>:data.items.length===0?<p>{t('No records in this view.','No hay registros en esta vista.')}</p>:<div className="commercial-grid">{data.items.map((r:any)=><article key={r.id}><h3>{r.title||(es?(r.nameES||r.nameEN):r.nameEN)||r.product||t('Commercial record','Registro comercial')}</h3>{r.state&&<p>{names[r.state]||r.state}</p>}{r.source&&<p>{r.source==='ADMIN_GRANT'?t('Complimentary benefit','Beneficio de cortesía'):r.source==='LEGACY'?t('Existing legacy access','Acceso anterior'):t('Purchased benefit','Beneficio comprado')}</p>}{r.source!=='ADMIN_GRANT'&&r.amount&&<p>{r.currency} {r.amount}</p>}{r.source!=='ADMIN_GRANT'&&r.priceSource&&<p>{r.priceSource==='OFFER'?t('Offer price committed to this Order','Precio de oferta fijado en este pedido'):t('Standard price committed to this Order','Precio estándar fijado en este pedido')}</p>}{r.startsAt&&<p>{t('Starts','Inicio')}: {date(r.startsAt)}</p>}{r.endsAt&&<p>{t('Ends','Fin')}: {date(r.endsAt)}</p>}{r.class==='FOUNDING_MEMBERSHIP'&&!r.endsAt&&<p>{t('Lifetime','De por vida')}</p>}{r.source!=='ADMIN_GRANT'&&r.deadline&&<p>{t('Payment deadline','Fecha límite de pago')}: {date(r.deadline)} (Costa Rica)</p>}{r.paid&&<p>{r.fulfilled?t('Benefit fulfilled; current access follows its term','Beneficio entregado; el acceso depende de su período'):r.awaitingPublication?t('Payment approved — awaiting listing publication','Pago aprobado — esperando la publicación del anuncio'):t('Payment approved — fulfillment pending','Pago aprobado — entrega pendiente')}</p>}{r.late&&<p>{t('Late evidence — does not reopen the Order','Evidencia tardía — no reabre el pedido')}</p>}{area==='orders'&&<Link href={`/commercial/${r.id}?lang=${language}`}>{t('Order detail','Detalle del pedido')}</Link>}{area==='payments'&&<Link href={`/payments/${r.order}?lang=${language}`}>{t('Payment detail','Detalle del pago')}</Link>}{area==='listings'&&<button onClick={()=>setListing(r.id)}>{t('View optional Add-ons','Ver complementos opcionales')}</button>}</article>)}</div>}
 {after&&<button onClick={()=>setAfter(null)}>{t('First page','Primera página')}</button>}{data?.ok&&data.next&&<button onClick={()=>setAfter(data.next)}>{t('Next','Siguiente')}</button>}{listing&&<CommercialCatalog key={listing} language={language} listing={listing}/>}
 <CommercialCatalog language={language}/></section>
}
