'use client'
import {useEffect,useRef,useState,type FormEvent} from 'react'
import AccountProfileImage from './AccountProfileImage'
import AccountPhoneSettings from './AccountPhoneSettings'
import AccountPushSettings from './AccountPushSettings'
import {useSiteTheme} from './theme/ThemeProvider'
import {readSettingsProfile,saveSettingsProfile} from '@/lib/account-identity/settings-actions'
import {readAccountEmail} from '@/lib/auth/account-email-action'
import {requestAccountEmailChange,usableAuthUser,hubPath} from '@/lib/auth/account-access'
import {supabase} from '@/lib/supabase'
// Legacy presentation-only props are deliberately ignored, never migrated into account truth.
type Props={language:'en'|'es';[legacyPresentationProp:string]:unknown}
type Profile={name:string|null;biography:string|null;language:'en'|'es'|null;revision:number}
export default function MarketHubSettings({language}:Props){
 const es=language==='es',t=(en:string,sp:string)=>es?sp:en,{theme,setTheme}=useSiteTheme()
 const [profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[bio,setBio]=useState(''),[locale,setLocale]=useState<'en'|'es'>(language),[profileLoading,setProfileLoading]=useState(true),[profileError,setProfileError]=useState(false),[saving,setSaving]=useState<'profile'|'language'|null>(null),[profileStatus,setProfileStatus]=useState(''),[languageStatus,setLanguageStatus]=useState('')
 const [email,setEmail]=useState<Awaited<ReturnType<typeof readAccountEmail>>|null>(null),[newEmail,setNewEmail]=useState(''),[emailBusy,setEmailBusy]=useState(false),[emailStatus,setEmailStatus]=useState('')
 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordStatus,setPasswordStatus]=useState(''),[signingOut,setSigningOut]=useState(false),[signoutStatus,setSignoutStatus]=useState('')
 const retry=useRef<{key:string;id:string}|null>(null)
 const unavailable=t('This section could not be loaded. Retry or sign in again.','No se pudo cargar esta sección. Reintente o vuelva a iniciar sesión.')
 const failed=t('The change could not be confirmed. Try again.','No se pudo confirmar el cambio. Inténtelo de nuevo.')
 const dirty=!!profile&&(name!==(profile.name??'')||bio!==(profile.biography??''))
 async function loadProfile(){setProfileLoading(true);try{const r=await readSettingsProfile();if(!r.ok){setProfileError(true);return}setProfile(r.profile);setName(r.profile.name??'');setBio(r.profile.biography??'');setLocale(r.profile.language??language);setProfileError(false);setProfileStatus('');setLanguageStatus('');retry.current=null}catch{setProfileError(true)}finally{setProfileLoading(false)}}
 async function loadEmail(){try{setEmail(await readAccountEmail())}catch{setEmail({ok:false})}}
 useEffect(()=>{void loadProfile();void loadEmail()},[])
 async function save(section:'profile'|'language'){
  if(!profile||saving)return
  const status=section==='profile'?setProfileStatus:setLanguageStatus
  if(Array.from(name).length>120||Array.from(bio).length>2000){status(t('Use at most 120 characters for the name and 2,000 for the biography.','Use un máximo de 120 caracteres para el nombre y 2.000 para la biografía.'));return}
  const patch=section==='profile'?{name,biography:bio}:{language:locale},key=JSON.stringify([profile.revision,patch]);if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()}
  setSaving(section);status('')
  try{const r=await saveSettingsProfile(retry.current.id,profile.revision,patch);if(!r.ok){status(r.reason==='conflict'?t('A newer change exists. Reload the saved profile before editing again; reloading discards these unsaved edits.','Existe un cambio más reciente. Vuelva a cargar el perfil antes de editar; se descartarán estos cambios sin guardar.'):r.reason==='invalid'?t('Check the field limits and language.','Revise los límites de los campos y el idioma.'):failed);return}
   retry.current=null;setProfile(r.profile);status(t('Saved.','Guardado.'))
   if(section==='profile'){setName(r.profile.name??'');setBio(r.profile.biography??'')}
   else{const destination=new URL(window.location.href);destination.pathname=hubPath(locale);if(destination.searchParams.has('lang'))destination.searchParams.set('lang',locale);window.location.assign(destination.pathname+destination.search)}
  }catch{status(failed)}finally{setSaving(null)}
 }
 async function changeEmail(e:FormEvent){e.preventDefault();setEmailBusy(true);setEmailStatus('');try{const r=await requestAccountEmailChange(newEmail,hubPath(language),language);if(!r.ok){setEmailStatus(t('The request could not be accepted. Check the email address or sign in again.','No se pudo aceptar la solicitud. Revise el correo o vuelva a iniciar sesión.'));return}setNewEmail('');setEmailStatus(t('Request accepted. Complete the provider confirmation steps. This does not mean the new email is confirmed.','Solicitud aceptada. Complete la confirmación del proveedor. Esto no significa que el nuevo correo esté confirmado.'));await loadEmail()}catch{setEmailStatus(failed)}finally{setEmailBusy(false)}}
 async function changePassword(e:FormEvent){e.preventDefault();if(password.length<6||password!==confirmation){setPasswordStatus(t('Use at least six characters and matching passwords.','Use al menos seis caracteres y contraseñas iguales.'));return}setPasswordBusy(true);setPasswordStatus('');try{await usableAuthUser();const {error}=await supabase.auth.updateUser({password});if(error){setPasswordStatus(t('Password not changed. You may need to sign in again or use password recovery.','La contraseña no cambió. Puede que deba iniciar sesión de nuevo o recuperar la contraseña.'));return}setPassword('');setConfirmation('');setPasswordStatus(t('Password updated.','Contraseña actualizada.'))}catch{setPasswordStatus(failed)}finally{setPasswordBusy(false)}}
 async function signout(){setSigningOut(true);setSignoutStatus('');try{const {error}=await supabase.auth.signOut({scope:'global'});if(error){setSignoutStatus(failed);return}setProfile(null);setEmail(null);setName('');setBio('');setNewEmail('');setPassword('');setConfirmation('');retry.current=null;setSignoutStatus(t('Signed out. Returning to the homepage…','Sesión cerrada. Volviendo al inicio…'));window.location.replace(es?'/es':'/en')}catch{setSignoutStatus(failed)}finally{setSigningOut(false)}}
 return <div className="real-settings">
  <section aria-labelledby="settings-profile"><h2 id="settings-profile">{t('Profile','Perfil')}</h2><AccountProfileImage language={language}/>
   {profileLoading?<p role="status">{t('Loading profile…','Cargando perfil…')}</p>:profileError?<><p role="alert">{unavailable}</p><button type="button" onClick={loadProfile}>{t('Retry profile','Reintentar perfil')}</button></>:profile&&<form onSubmit={e=>{e.preventDefault();void save('profile')}}>
    <label>{t('Name','Nombre')}<input value={name} maxLength={120} autoComplete="name" disabled={!!saving} aria-describedby="profile-status" onChange={e=>{setName(e.target.value);setProfileStatus('')}}/></label>
    <p>{t('A display name, not a verified legal identity.','Nombre para mostrar, no una identidad legal verificada.')}</p>
    <label>{t('Biography','Biografía')}<textarea rows={5} maxLength={2000} value={bio} disabled={!!saving} aria-describedby="profile-status" onChange={e=>{setBio(e.target.value);setProfileStatus('')}}/></label>
    <button disabled={!dirty||!!saving}>{saving==='profile'?t('Saving…','Guardando…'):t('Save profile','Guardar perfil')}</button>{' '}<button type="button" disabled={!!saving} onClick={loadProfile}>{t('Reload saved profile','Volver a cargar el perfil guardado')}</button>
    <p id="profile-status" role="status">{profileStatus||(dirty?t('Unsaved changes.','Cambios sin guardar.'):t('No unsaved changes.','Sin cambios pendientes.'))}</p>
   </form>}
  </section>
  <section aria-labelledby="settings-account"><h2 id="settings-account">{t('Account','Cuenta')}</h2><h3>{t('Email','Correo electrónico')}</h3>
   {!email?<p role="status">{t('Loading email…','Cargando correo…')}</p>:!email.ok?<><p role="alert">{unavailable}</p><button type="button" onClick={loadEmail}>{t('Retry email','Reintentar correo')}</button></>:<><p>{email.email??t('No email established.','No hay correo establecido.')} — {email.emailConfirmed?t('Confirmed','Confirmado'):t('Unconfirmed','Sin confirmar')}</p>{email.pendingEmail&&<p>{t('Pending confirmation:','Pendiente de confirmación:')} {email.pendingEmail}</p>}<form onSubmit={changeEmail}><label>{t('New email','Nuevo correo')}<input type="email" autoComplete="email" required maxLength={254} value={newEmail} disabled={emailBusy} aria-describedby="email-status" onChange={e=>setNewEmail(e.target.value)}/></label><button disabled={emailBusy||!newEmail.trim()}>{emailBusy?t('Requesting…','Solicitando…'):t('Request email change','Solicitar cambio de correo')}</button></form></>}
   <p id="email-status" role="status">{emailStatus}</p><AccountPhoneSettings language={language}/>
   {profile&&!profileError&&<form onSubmit={e=>{e.preventDefault();void save('language')}}><label>{t('Language','Idioma')}<select value={locale} disabled={!!saving} aria-describedby="language-status" onChange={e=>{setLocale(e.target.value as 'en'|'es');setLanguageStatus('')}}><option value="en">English</option><option value="es">Español</option></select></label><button disabled={!!saving||dirty||locale===profile.language}>{saving==='language'?t('Saving…','Guardando…'):t('Save language','Guardar idioma')}</button><p id="language-status" role="status">{languageStatus||(dirty?t('Save profile changes before changing language.','Guarde los cambios del perfil antes de cambiar el idioma.'):profile.language===null?t('Not saved; the current route supplies the default.','Sin guardar; la ruta actual determina el valor inicial.'):locale!==profile.language?t('Unsaved language change.','Cambio de idioma sin guardar.'):'')}</p></form>}
  </section>
  <section aria-labelledby="settings-appearance"><h2 id="settings-appearance">{t('Appearance','Apariencia')}</h2><p>{t('Saved in this browser only; not synchronized with your account.','Se guarda solo en este navegador; no se sincroniza con su cuenta.')}</p><div className="settings-buttons"><button type="button" aria-pressed={theme==='light'} onClick={()=>setTheme('light')}>{t('Light','Claro')}</button><button type="button" aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}>{t('Dark','Oscuro')}</button></div></section>
  <section aria-labelledby="settings-notifications"><h2 id="settings-notifications">{t('Notifications','Notificaciones')}</h2><AccountPushSettings language={language}/></section>
  <section aria-labelledby="settings-security"><h2 id="settings-security">{t('Security','Seguridad')}</h2><form onSubmit={changePassword}><label>{t('New password','Nueva contraseña')}<input type="password" autoComplete="new-password" minLength={6} required value={password} disabled={passwordBusy} aria-describedby="password-status" onChange={e=>setPassword(e.target.value)}/></label><label>{t('Confirm password','Confirmar contraseña')}<input type="password" autoComplete="new-password" minLength={6} required value={confirmation} disabled={passwordBusy} aria-describedby="password-status" onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={passwordBusy||!password||!confirmation}>{passwordBusy?t('Saving…','Guardando…'):t('Change password','Cambiar contraseña')}</button><p id="password-status" role="status">{passwordStatus}</p></form>
   <button type="button" disabled={signingOut} onClick={signout}>{signingOut?t('Signing out…','Cerrando sesión…'):t('Sign out everywhere','Cerrar sesión en todas partes')}</button><p>{t('Ends provider sessions. Already-issued access tokens may remain valid until they expire.','Cierra las sesiones del proveedor. Los tokens de acceso ya emitidos pueden seguir siendo válidos hasta vencer.')}</p><p role="status">{signoutStatus}</p>
  </section>
  <style jsx>{`.real-settings{display:grid;gap:20px;min-width:0;color:var(--foreground)}.real-settings>section{min-width:0;padding:20px;border:1px solid var(--border);border-radius:18px;background:var(--surface-raised)}.real-settings h2{margin:0 0 16px}.real-settings label{display:flex;flex-direction:column;gap:7px;margin:16px 0}.real-settings input,.real-settings textarea,.real-settings select{box-sizing:border-box;min-width:0;width:100%;padding:12px;border:1px solid var(--border);border-radius:9px;background:var(--surface);color:inherit;font:inherit}.real-settings option{background:#fff;color:#111}.real-settings button{box-sizing:border-box;min-height:44px;max-width:100%;padding:10px 14px;border:1px solid currentColor;border-radius:9px;background:transparent;color:inherit;font:inherit;white-space:normal;overflow-wrap:anywhere}.real-settings button:disabled{opacity:.55}.real-settings button[aria-pressed=true]{border:2px solid #ff6b00}.real-settings :focus-visible{outline:3px solid #ff6b00;outline-offset:3px}.real-settings p{overflow-wrap:anywhere;line-height:1.5}.settings-buttons{display:flex;gap:12px;flex-wrap:wrap}@media(max-width:390px){.real-settings>section{padding:12px}}`}</style>
 </div>
}
