'use client'
import {useMemo,useRef,useState} from 'react'
import {evaluatePropertyPriceValuation,loadPropertyPriceValuationOptions} from '@/lib/property-price-valuation-action'
import type {Question,Dimension,Result,Option,Level} from '@/lib/property-price-valuation-contract'
import {sortValuationPeers,type PeerSort} from '@/lib/property-price-valuation-presentation'
import {listingHref} from '@/lib/listing-route'
import styles from './PropertyPriceValuation.module.css'
const areaLabels:Record<string,string>={'under-100m2':'<100 m²','100-500m2':'100–<500 m²','500-1000m2':'500–<1,000 m²','1000-5000m2':'1,000–<5,000 m²','5000m2-1-hectare':'5,000–<10,000 m²','1-5-hectares':'10,000–<50,000 m²','over-5-hectares':'≥50,000 m²','under-50m2':'<50 m²','50-100m2':'50–<100 m²','100-200m2':'100–<200 m²','200-400m2':'200–<400 m²','400-800m2':'400–<800 m²','800m2-plus':'≥800 m²'}
const dimensions:Dimension[]=['bedrooms','bathrooms','parking','year_built','construction_land','environment','terrain','utility','accessibility','legal_status']
const names:Record<Dimension,[string,string]>={bedrooms:['Bedrooms','Dormitorios'],bathrooms:['Bathrooms','Baños'],parking:['Parking','Estacionamientos'],year_built:['Year built','Año de construcción'],construction_land:['Construction / land','Construcción / terreno'],environment:['Environment','Entorno'],terrain:['Terrain','Terreno'],utility:['Utilities','Servicios'],accessibility:['Accessibility','Accesibilidad'],legal_status:['Legal status','Estado legal']}
export default function PropertyPriceValuation({lang,listingId}:{lang:'en'|'es';listingId?:string}){
 const es=lang==='es',t=(en:string,spanish:string)=>es?spanish:en
 const [kind,setKind]=useState<'listing'|'hypothetical'>(listingId?'listing':'hypothetical'),[id,setId]=useState(listingId??'')
 const [transaction,setTransaction]=useState<'sale'|'rent'>('sale'),[province,setProvince]=useState(''),[canton,setCanton]=useState(''),[district,setDistrict]=useState(''),[propertyType,setPropertyType]=useState('')
 const [propertyArea,setPropertyArea]=useState(''),[constructionArea,setConstructionArea]=useState(''),[price,setPrice]=useState(''),[currency,setCurrency]=useState<'CRC'|'USD'>('CRC')
 const [geographyLevel,setGeographyLevel]=useState<Level>('canton'),[normalization,setNormalization]=useState<'land'|'construction'>('land'),[active,setActive]=useState<Dimension[]>([]),[chars,setChars]=useState<Record<string,string>>({})
 const [options,setOptions]=useState<Option[]>([]),[optionsBusy,setOptionsBusy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null)
 const generation=useRef(0),inFlight=useRef(false)
 const [sort,setSort]=useState<{key:PeerSort;direction:'asc'|'desc';activated:boolean}>({key:'title',direction:'asc',activated:false}),[page,setPage]=useState(0)
 const rows=useMemo(()=>sortValuationPeers(result?.peers??[],sort.key,sort.direction),[result,sort]),pageSize=20,visible=rows.slice(page*pageSize,(page+1)*pageSize)
 const number=(v:number|null)=>v===null?'—':new Intl.NumberFormat(es?'es-CR':'en-US',{maximumFractionDigits:2}).format(v)
 const money=(v:number|null)=>v===null?'—':'₡'+number(v)
 function edit(){generation.current++;setError('')}
 function choices(type:string,parent?:string){return options.filter(o=>o.type===type&&(parent===undefined||o.parentId===Number(parent)))}
 function selectOptions(type:string,parent?:string){return <><option value="">{t('Select','Seleccione')}</option>{choices(type,parent).map(o=><option key={o.id} value={o.id}>{o[lang]}</option>)}</>}
 async function loadOptions(){if(optionsBusy)return;setOptionsBusy(true);try{const r=await loadPropertyPriceValuationOptions();if(r.ok)setOptions(r.options);else setError(t('Sign in with Price / m² access to load property options.','Inicie sesión con acceso a Precio / m² para cargar las opciones.'))}catch{setError(t('Options could not be loaded.','No se pudieron cargar las opciones.'))}finally{setOptionsBusy(false)}}
 async function evaluate(event:React.FormEvent){event.preventDefault();if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');const requestGeneration=++generation.current
  const question:Question={subject:kind==='listing'?{kind:'listing',listingId:id}:{kind:'hypothetical',transaction,province:Number(province),canton:Number(canton),district:district?Number(district):null,propertyType:Number(propertyType),propertyArea:Number(propertyArea),constructionArea:constructionArea?Number(constructionArea):null,characteristics:Object.fromEntries(Object.entries(chars).filter(([,v])=>v).map(([d,v])=>[d,Number(v)])),askingPrice:price?{amount:Number(price),currency}:null},geographyLevel,normalization,activeDimensions:active}
  try{const response=await evaluatePropertyPriceValuation(question);if(requestGeneration!==generation.current)return
   if(response.ok){setResult(response.result);setPage(0)}else setError(response.code==='authentication_required'?t('Sign in to evaluate.','Inicie sesión para evaluar.'):response.code==='entitlement_required'?t('Price / m² access is required.','Se requiere acceso a Precio / m².'):response.code==='subject_unavailable'?t('This canonical listing is unavailable or access is restricted.','Este anuncio canónico no está disponible o su acceso está restringido.'):response.code==='insufficient_evidence'?t('The subject lacks evidence required by this comparable question.','Al inmueble le falta evidencia requerida por esta comparación.'):response.code==='incomplete_evidence'?t('Peer evidence is incomplete. The previous result is unchanged.','La evidencia comparable está incompleta. El resultado anterior no cambia.'):response.code==='invalid_question'?t('Check the subject facts and selected comparable constraints.','Revise los datos del inmueble y las restricciones seleccionadas.'):t('Complete evidence could not be established. The previous result is unchanged.','No se pudo establecer evidencia completa. El resultado anterior no cambia.'))
  }catch{if(requestGeneration===generation.current)setError(t('Evaluation failed. The previous result is unchanged.','La evaluación falló. El resultado anterior no cambia.'))}finally{inFlight.current=false;setBusy(false)}
 }
 function changeSort(key:PeerSort){setSort(old=>({key,activated:true,direction:old.activated&&old.key===key&&old.direction==='asc'?'desc':'asc'}));setPage(0)}
 const statNames:Record<keyof Result['statistics'],string>={minimum:t('Minimum','Mínimo'),p10:'P10',p25:'P25',median:t('Median','Mediana'),average:t('Mean','Media'),p75:'P75',p90:'P90',maximum:t('Maximum','Máximo'),iqr:'IQR'}
 const intervalNames:Record<string,string>={below_p10:t('Below P10','Por debajo de P10'),p10_to_p25:'P10–P25',p25_to_median:t('P25–Median','P25–Mediana'),at_median:t('At the median','En la mediana'),median_to_p75:t('Median–P75','Mediana–P75'),p75_to_p90:'P75–P90',above_p90:t('Above P90','Por encima de P90')}
 return <main className={styles.workspace}>
  <header><p>{t('PRICE / m² MARKET INTELLIGENCE','INTELIGENCIA DE MERCADO DE PRECIO / m²')} · 12B</p><h1>{t('Property Price Valuation','Valoración del precio de la propiedad')}</h1><p>{t("Where does this property's price fall among comparable properties?",'¿Dónde se ubica el precio de esta propiedad entre propiedades comparables?')}</p></header>
  <form onSubmit={evaluate} onChange={edit} className={styles.form}>
   <h2>{t('Define the subject and comparison','Defina el inmueble y la comparación')}</h2>
   <label>{t('Subject','Inmueble')}<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="hypothetical">{t('Hypothetical property','Propiedad hipotética')}</option><option value="listing">{t('Existing listing','Anuncio existente')}</option></select></label>
   {kind==='listing'?<label>{t('Listing ID','ID del anuncio')}<input required value={id} onChange={e=>setId(e.target.value)}/></label>:<>
    <button type="button" disabled={optionsBusy} onClick={loadOptions}>{optionsBusy?t('Loading…','Cargando…'):t('Load property options','Cargar opciones de propiedad')}</button>
    <label>{t('Transaction','Transacción')}<select value={transaction} onChange={e=>setTransaction(e.target.value as typeof transaction)}><option value="sale">{t('Sale','Venta')}</option><option value="rent">{t('Monthly rent','Alquiler mensual')}</option></select></label>
    <label>{t('Province','Provincia')}<select required value={province} onChange={e=>{setProvince(e.target.value);setCanton('');setDistrict('')}}>{selectOptions('province')}</select></label>
    <label>{t('Canton','Cantón')}<select required value={canton} onChange={e=>{setCanton(e.target.value);setDistrict('')}}>{selectOptions('canton',province)}</select></label>
    <label>{t('District (optional)','Distrito (opcional)')}<select value={district} onChange={e=>setDistrict(e.target.value)}>{selectOptions('district',canton)}</select></label>
    <label>{t('Property Type','Tipo de propiedad')}<select required value={propertyType} onChange={e=>setPropertyType(e.target.value)}>{selectOptions('property_type')}</select></label>
    <label>{t('Exact property area · m²','Área exacta del terreno · m²')}<input required type="number" step="any" min="0" value={propertyArea} onChange={e=>setPropertyArea(e.target.value)}/></label>
    <label>{t('Exact construction area · m² (required for improved property)','Área exacta de construcción · m² (obligatoria para inmueble construido)')}<input type="number" step="any" min="0" value={constructionArea} onChange={e=>setConstructionArea(e.target.value)}/></label>
    <label>{t('Proposed asking price (optional)','Precio solicitado propuesto (opcional)')}<input type="number" step="any" min="0" value={price} onChange={e=>setPrice(e.target.value)}/></label>
    <label>{t('Original currency','Moneda original')}<select value={currency} onChange={e=>setCurrency(e.target.value as typeof currency)}><option>CRC</option><option>USD</option></select></label>
   </>}
   <label>{t('Comparison geography','Geografía de comparación')}<select value={geographyLevel} onChange={e=>setGeographyLevel(e.target.value as Level)}><option value="province">{t('Province','Provincia')}</option><option value="canton">{t('Canton','Cantón')}</option><option value="district">{t('District','Distrito')}</option></select></label>
   <label>{t('Comparable normalization identity','Identidad de normalización de comparables')}<select value={normalization} onChange={e=>setNormalization(e.target.value as typeof normalization)}><option value="land">{t('Land','Terreno')}</option><option value="construction">{t('Construction','Construcción')}</option></select></label>
   <fieldset><legend>{t('Optional comparable constraints','Restricciones opcionales de comparables')}</legend>{dimensions.map(d=><div key={d} className={styles.constraint}><label><input type="checkbox" checked={active.includes(d)} onChange={e=>setActive(old=>e.target.checked?[...old,d]:old.filter(x=>x!==d))}/>{names[d][es?1:0]}</label>{kind==='hypothetical'&&d!=='construction_land'&&active.includes(d)&&<select aria-label={names[d][es?1:0]} required value={chars[d]??''} onChange={e=>setChars(old=>({...old,[d]:e.target.value}))}>{selectOptions(d)}</select>}</div>)}</fieldset>
   <p>{t('Selected constraints use the subject’s category. Unclassified evidence cannot establish a category constraint. Exact areas remain separate facts.','Las restricciones seleccionadas usan la categoría del inmueble. La evidencia sin clasificación no establece una restricción por categoría. Las áreas exactas siguen siendo datos separados.')}</p>
   <button type="submit" disabled={busy}>{busy?t('Evaluating…','Evaluando…'):t('Evaluate','Evaluar')}</button>
  </form>
  {error&&<p role="alert">{error}</p>}
  {result&&<section aria-label={t('Committed result','Resultado confirmado')} className={styles.result}>
   <header><h2>{result.subject.kind==='listing'?result.subject.title:t('Hypothetical property','Propiedad hipotética')}</h2><p>{t('Committed comparison','Comparación confirmada')} · {result.population.geography[lang]} · {result.population.propertyType[lang]} · {result.population.transaction==='sale'?t('Sale','Venta'):t('Monthly rent','Alquiler mensual')}</p><p>{t('Property basis','Base del inmueble')}: {result.population.propertyBasis==='land_only'?t('Land only','Solo terreno'):t('Improved property','Inmueble construido')} · {t('Normalization identity','Identidad de normalización')}: {result.population.normalization==='land'?t('Land','Terreno'):t('Construction','Construcción')} · {t('Geographic level','Nivel geográfico')}: {result.population.geographyLevel==='province'?t('Province','Provincia'):result.population.geographyLevel==='canton'?t('Canton','Cantón'):t('District','Distrito')}</p><p>{t('Subject excluded','Inmueble sujeto excluido')} · {t('Property area band','Intervalo de área del terreno')}: {areaLabels[result.population.propertyAreaRange]??result.population.propertyAreaRange} {result.population.constructionAreaRange&&<> · {t('Construction area band','Intervalo de área construida')}: {areaLabels[result.population.constructionAreaRange]??result.population.constructionAreaRange}</>}</p><p>{t('Exact subject areas','Áreas exactas del inmueble')}: {number(result.subject.propertyArea)} / {number(result.subject.constructionArea)} m²</p>{result.population.constraints.map(c=><span className={styles.tag} key={c.dimension}>{names[c.dimension][es?1:0]}: {c.label[lang]}</span>)}</header>
   <div className={styles.counts}><p>{t('Comparable Population','Población comparable')} <strong>n = {result.structuralComparablePopulationN}</strong></p><p>{t('Total-Price Population','Población de precio total')} <strong>n = {result.totalPricePopulationN}</strong></p></div>
   <p>{t('Monetary exclusions','Exclusiones monetarias')}: {t('missing amount','monto ausente')} {result.exclusions.missingAmount}; {t('invalid amount','monto inválido')} {result.exclusions.invalidAmount}; {t('unsupported currency','moneda no admitida')} {result.exclusions.unsupportedCurrency}.</p>
   {result.outcome!=='complete'&&<p role="status">{result.outcome==='no_structural_peers'?t('No structurally comparable peers.','No hay propiedades estructuralmente comparables.'):result.outcome==='no_eligible_prices'?t('Structural peers have no eligible asking-price observations.','Las propiedades comparables no tienen observaciones elegibles de precio solicitado.'):t('Distribution only: no eligible subject asking price.','Solo distribución: no hay un precio solicitado elegible para el inmueble sujeto.')}</p>}
   <h3>{t('Observed asking-price distribution · CRC','Distribución observada del precio solicitado · CRC')} {result.unit==='monthly_asking_price'&&t('/ month','/ mes')}</h3>
   {result.totalPricePopulationN>0&&<QuantilePlot result={result} label={t('Quantiles and subject price; not a density estimate','Cuantiles y precio del inmueble; no es una estimación de densidad')}/>}
   {result.totalPricePopulationN>0&&<p>{t('Line: observed minimum–maximum. Box: P25–P75. Amber dot: subject asking price, when available.','Línea: mínimo–máximo observado. Caja: P25–P75. Punto ámbar: precio solicitado del inmueble, cuando esté disponible.')}</p>}
   <dl className={styles.stats}>{Object.entries(result.statistics).map(([key,v])=><div key={key}><dt>{statNames[key as keyof typeof statNames]}</dt><dd>{money(v)}</dd></div>)}</dl>
   <h3>{t('Subject asking price','Precio solicitado del inmueble')}: {money(result.subject.askingPriceCrc)}</h3>
   {result.subject.originalPrice!==null&&<p>{t('Original denomination','Denominación original')}: {result.subject.currency} {number(result.subject.originalPrice)}</p>}
   {result.position&&<div><p>{t('Percentile position','Posición percentil')}: <strong>{number(result.position.percentilePosition)}</strong> · {intervalNames[result.position.interval]}</p><p>{t('Below / equal / above','Por debajo / igual / por encima')}: {result.position.belowCount} / {result.position.equalCount} / {result.position.aboveCount} · N = {result.totalPricePopulationN}</p><p>{t('Difference from peer median','Diferencia respecto de la mediana comparable')}: {money(result.position.difference)} ({number(result.position.percentDifference)}%)</p>{result.position.tail&&<p>{t('Difference from','Diferencia respecto de')} P{result.position.tail.thresholdPercentile}: {money(result.position.tail.differenceFromThreshold)} ({number(result.position.tail.percentDifferenceFromThreshold)}%)</p>}</div>}
   <details><summary>{t('Population and methodology','Población y metodología')}</summary><p>{t('Active canonical listings in the committed geography, same transaction, Property Type, Property Basis, normalization identity, area bands and explicitly selected constraints. The subject never contributes to the peer distribution. No automatic broadening. Cross-source physical duplicates are not resolved here.','Anuncios canónicos activos en la geografía confirmada, misma transacción, tipo, base del inmueble, identidad de normalización, intervalos de área y restricciones seleccionadas. El inmueble sujeto nunca contribuye a la distribución comparable. No hay ampliación automática. Aquí no se resuelven duplicados físicos entre fuentes.')}</p><p>{t('Linear interpolation: (n − 1) × p. External-subject midrank: 100 × (below + 0.5 × equal) / N. Median differences use the peer median as denominator. C/L is construction area divided by land area, not site coverage.','Interpolación lineal: (n − 1) × p. Rango medio del inmueble externo: 100 × (inferiores + 0,5 × iguales) / N. Las diferencias usan la mediana comparable como denominador. C/T es área construida dividida por área de terreno, no cobertura del lote.')}</p><p>{t('Acquisition completed; a transaction-wide snapshot is not guaranteed.','Adquisición completa; no se garantiza una instantánea de toda la transacción.')} {result.analyticalDate}</p>{result.fx&&<p>BCCR · USD → CRC · {result.fx.rate} · {result.fx.effectiveDate}</p>}{result.trail.map(r=><p key={r.dimension}>{names[r.dimension][es?1:0]}: {r.beforeCount} → {r.afterCount}</p>)}</details>
   <h3>{t('Comparable properties','Propiedades comparables')}</h3>
   <div className={styles.tableScroll}><table><thead><tr>{([['title',t('Property','Propiedad')],['priceCrc',t('Asking price · CRC','Precio solicitado · CRC')],['propertyArea',t('Property m²','Terreno m²')],['constructionArea',t('Construction m²','Construcción m²')]] as [PeerSort,string][]).map(([key,label])=><th key={key} aria-sort={sort.key===key?(sort.direction==='asc'?'ascending':'descending'):'none'}><button onClick={()=>changeSort(key)}>{label} {sort.key===key?(sort.direction==='asc'?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><a href={listingHref(p.id,p.transaction,lang)}>{p.title}</a></td><td data-label={t('Asking price','Precio solicitado')}>{money(p.priceCrc)}{p.currency&&<small>{p.currency} {number(p.originalPrice)}</small>}</td><td data-label={t('Property m²','Terreno m²')}>{number(p.propertyArea)}</td><td data-label={t('Construction m²','Construcción m²')}>{number(p.constructionArea)}</td></tr>)}</tbody></table></div>
   <nav aria-label={t('Peer pages','Páginas de comparables')}><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t('Previous','Anterior')}</button> {page+1} / {Math.max(1,Math.ceil(rows.length/pageSize))} <button disabled={(page+1)*pageSize>=rows.length} onClick={()=>setPage(p=>p+1)}>{t('Next','Siguiente')}</button></nav>
   <p className={styles.axiom}>{t('TWUANIS REPORTS MARKET EVIDENCE. TWUANIS DOES NOT PRESCRIBE DECISIONS.','TWUANIS REPORTA EVIDENCIA DEL MERCADO. TWUANIS NO PRESCRIBE DECISIONES.')}</p>
  </section>}
 </main>
}
function QuantilePlot({result:r,label}:{result:Result;label:string}){
 const s=r.statistics,min=Math.min(s.minimum!,r.subject.askingPriceCrc??s.minimum!),max=Math.max(s.maximum!,r.subject.askingPriceCrc??s.maximum!),x=(v:number)=>max===min?300:30+540*(v-min)/(max-min)
 return <svg className={styles.plot} viewBox="0 0 600 84" role="img" aria-label={label}><title>{label}</title><line x1={x(s.minimum!)} x2={x(s.maximum!)} y1="40" y2="40" stroke="currentColor"/><rect x={x(s.p25!)} y="25" width={Math.max(1,x(s.p75!)-x(s.p25!))} height="30" fill="currentColor" opacity=".15"/>{[s.minimum,s.p10,s.p25,s.median,s.p75,s.p90,s.maximum].map((v,i)=><line key={i} x1={x(v!)} x2={x(v!)} y1={i===3?20:30} y2={i===3?60:50} stroke="currentColor"/>)}{r.subject.askingPriceCrc!==null&&<circle cx={x(r.subject.askingPriceCrc)} cy="12" r="5" fill="#d97706"/>}<text x={x(s.median!)} y="78" textAnchor="middle" fontSize="12">P50</text></svg>
}
