'use client'
import CanonicalMarketWorkspace from '../CanonicalMarketWorkspace'
import type {ExplorerOptions,Filters,Language} from '../market-filters/types'
import {configurationQuestion,configurationShareQuestion,evidenceContext,type ConfigurationResult} from './contract'
import shared from '../market-summary/workspace.module.css'
import styles from './frequency.module.css'
export default function ConfigurationFrequency({options,filters,language='en'}:{options:ExplorerOptions;filters:Filters;language?:Language}){
 const es=language==='es',integer=new Intl.NumberFormat(es?'es-CR':'en-US'),percent=new Intl.NumberFormat(es?'es-CR':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2})
 return <CanonicalMarketWorkspace<ConfigurationResult> engine="configuration" options={options} filters={filters} language={language} title={es?'Frecuencia de configuración de propiedades':'Property Configuration Frequency'} primaryQuestion={configurationQuestion[language]}>
 {(committed,heading,id)=>{const r=committed.result;return <>
  <section className={shared.evidence} aria-labelledby={`${id}-frequency`} data-frequency-result>
   <h3 id={`${id}-frequency`} ref={heading} tabIndex={-1}>{es?'Frecuencia de evidencia positiva':'Positive-evidence frequency'}</h3><p className={shared.sectionQuestion}>{configurationShareQuestion[language]}</p>
   <div className={styles.counts}><p><strong data-positive-count>{integer.format(r.matchingCount)}</strong><span>{es?'anuncios acreditan positivamente la configuración completa':'listings positively establish the complete configuration'}</span></p><p><strong data-base-count>{integer.format(r.marketSize)}</strong><span>{es?'anuncios en todo el mercado definido · denominador':'listings in the entire defined market · denominator'}</span></p></div>
   {r.percentage===null?<p role="status" data-share>{es?'Mercado vacío: no hay denominador para establecer un porcentaje.':'Empty market: no denominator exists to establish a percentage.'}</p>:<><p className={styles.share} data-share>{percent.format(r.percentage)}% <span>{es?'del mercado definido':'of the defined market'}</span></p><div className={styles.track} aria-hidden="true"><div data-frequency-bar className={styles.fill} style={{width:`${r.percentage}%`}}/></div><p className={styles.note}>{es?'La parte coloreada representa únicamente pertenencia acreditada positivamente. El resto no está clasificado como ausencia o no coincidencia conocida.':'The filled portion represents positively established membership only. The remainder is not classified as absence or known nonmembership.'}</p>{r.percentage>0&&r.percentage<0.005&&<p className={styles.note}>{es?'Porcentaje positivo inferior a 0,005%; se muestra redondeado a dos decimales.':'Positive share below 0.005%; displayed rounded to two decimal places.'}</p>}</>}
   {!r.selectedCombination&&<p>{es?'Sin restricciones de configuración seleccionadas: la configuración incluye todo el mercado definido.':'No configuration constraints selected: the configuration includes the entire defined market.'}</p>}
   <p className={styles.context}>{evidenceContext[language]}</p>
  </section>
  <details className={shared.method}><summary>{es?'Metodología':'Methodology'}</summary><p>{es?'El denominador cuenta anuncios distintos, activos y canónicos que cumplen transacción, geografía y tipo de propiedad. El numerador exige conjuntamente todos los atributos seleccionados, incluidos varios términos de una misma dimensión.':'The denominator counts distinct active canonical listings satisfying transaction, geography and property type. The numerator requires all selected attributes together, including multiple terms within one dimension.'}</p><p>{es?'Las categorías se identifican mediante identidades canónicas; sus etiquetas no determinan pertenencia. Los rangos son restricciones, no medidas exactas. Año de construcción y distancia a carretera requieren evidencia numérica que establezca la restricción seleccionada.':'Categories use canonical identities; their labels do not determine membership. Ranges are constraints, not exact measurements. Year built and road distance require numerical evidence establishing the selected constraint.'}</p><p>{es?'El porcentaje proviene del servidor y usa todo el mercado como denominador. No se distinguen los casos desconocidos de las no coincidencias conocidas. No se enumeran configuraciones alternativas ni se evalúa demanda, valor o rareza.':'The percentage comes from the server and uses the whole market as denominator. Unknown cases are not distinguished from known nonmembers. No alternate configurations are enumerated; demand, value and rarity are not evaluated.'}</p></details>
 </>}}
 </CanonicalMarketWorkspace>
}
