'use client'
import {useEffect,useRef,useState} from 'react'
import {executeComparablesHub} from '@/lib/comparables-hub-action'
import {comparablesTitle,comparablesQuestion,comparableDimensions,comparableLabels,parseComparablesRequest,type ComparablesRequest,type ComparablesResponse} from '@/lib/comparables-hub-contract'
import type {PriceMeterComparableBrowserSuccessEvidence} from '@/lib/price-meter-comparable-browser-contract'
import {positionLabels,positionNumber,positionIntervals} from '@/lib/price-meter-property-position-presentation'
import ComparativeDiscoveryAccess from '../ComparativeDiscoveryAccess'
import AnalysisActions from '../AnalysisActions'
import styles from '../market-summary/workspace.module.css'
import cohort from './comparables.module.css'
import local from '../price-meter-position/position.module.css'
function restore(text?:string):ComparablesRequest|null{try{return text?parseComparablesRequest(JSON.parse(text)):null}catch{return null}}
const blank:ComparablesRequest={subjectListingId:'',geographyLevel:'canton',normalizationBasis:'land',activeDimensions:[]}
function Evidence({r,language}:{r:PriceMeterComparableBrowserSuccessEvidence;language:'en'|'es'}){
 const es=language==='es',l=positionLabels[language],f=(v:number,s=false)=>positionNumber(v,language,s),unit=r.transactionType==='rent'?(es?'CRC/m²/mes':'CRC/m²/month'):'CRC/m²'
 return <><dl className={local.metrics}>{[[es?'Precio de la propiedad por m²':'Subject Price / m²',`${f(r.propertyPricePerM2)} ${unit}`],[es?'Mediana de la cohorte':'Cohort median',`${f(r.distribution.median)} ${unit}`],[l.percentile,f(r.percentile.position)],[es?'Propiedad − mediana':'Subject − median',`${f(r.medianPosition.difference,true)} ${unit} (${f(r.medianPosition.percentDifference,true)}%)`]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 <p>{es?'El porcentaje usa la mediana de la cohorte como referencia.':'The percentage uses the cohort median as its reference.'}</p>
 <div className={local.position} aria-label={l.percentile}><div className={local.track}><span style={{left:`${r.percentile.position}%`}}/></div><div className={local.ends}><span>0</span><strong>{l.percentile}: {f(r.percentile.position)}</strong><span>100</span></div></div>
 <p>{l.below}: {r.percentile.belowCount} · {l.equal}: {r.percentile.equalCount} · {l.above}: {r.percentile.aboveCount}</p><p>{l.interval}: {positionIntervals[r.distributionInterval]}</p>
 <details><summary>{l.distribution}</summary><dl className={local.metrics}>{Object.entries(r.distribution).map(([k,v])=><div key={k}><dt>{k in l?l[k as 'minimum'|'median'|'maximum'|'iqr']:k.toUpperCase()}</dt><dd>{f(v)} {unit}</dd></div>)}</dl></details>
 <details><summary>{es?'Valores numéricos sin redondear':'Unrounded numerical evidence'}</summary><dl className={local.metrics}>{[[es?'Propiedad':'Subject',r.propertyPricePerM2],[l.percentile,r.percentile.position],[l.difference,r.medianPosition.difference],[es?'Diferencia porcentual (%)':'Percentage difference (%)',r.medianPosition.percentDifference],...Object.entries(r.distribution)].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><p>{unit}</p></details>
 {r.tail&&<p>{l.tail}: P{r.tail.thresholdPercentile} = {f(r.tail.thresholdPricePerM2)} {unit}. {l.tailDifference}: {f(r.tail.differenceFromThreshold,true)} {unit} ({f(r.tail.percentDifferenceFromThreshold,true)}%; P{r.tail.thresholdPercentile}).</p>}
 {r.constructionToLandContext&&<p>{l.ratio}: {f(r.constructionToLandContext.constructionToLandRatio)} ({f(r.constructionToLandContext.constructionAreaM2)} m² / {f(r.constructionToLandContext.propertyAreaM2)} m²). {es?'No es cobertura del terreno.':'This is not site coverage.'}</p>}
 </>
}
function Workspace({language,serialized}:{language:'en'|'es';serialized?:string}){
 const es=language==='es',initial=restore(serialized),l=positionLabels[language]
 const[draft,setDraft]=useState<ComparablesRequest>(initial??blank),[editing,setEditing]=useState(true),[busy,setBusy]=useState(false)
 const[committed,setCommitted]=useState<{request:ComparablesRequest;response:Extract<ComparablesResponse,{evidence:unknown}>}|null>(null)
 const[error,setError]=useState(serialized&&!initial?(es?'No se pudo restaurar la pregunta guardada.':'The saved question could not be restored.'):'')
 const lock=useRef(false),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>()=>{generation.current++},[]);useEffect(()=>{if(committed)heading.current?.focus()},[committed])
 async function apply(event:React.FormEvent){event.preventDefault();if(lock.current)return;let request:ComparablesRequest
  try{request=parseComparablesRequest(draft)}catch{setError(es?'Ingresa un ID de anuncio válido y define la cohorte.':'Enter a valid listing ID and define the cohort.');return}
  lock.current=true;const ticket=++generation.current;setBusy(true);setError('')
  try{const response=await executeComparablesHub(request);if(ticket!==generation.current)return
   if('access'in response){setCommitted(null);setError(es?'Se requiere una sesión y acceso autorizado.':'Sign in with authorized access to run this analysis.');return}
   if('error'in response){setError(es?'No se pudo establecer la cohorte. Comprueba la propiedad, su geografía, las áreas exactas y las características seleccionadas. La evidencia previa no ha sido reemplazada.':'The cohort could not be established. Check the property, its geography, exact areas and selected characteristics. Prior evidence has not been replaced.');return}
   setCommitted({request,response});setEditing(false)
  }catch{if(ticket===generation.current)setError(es?'Análisis no disponible. Inténtalo de nuevo.':'Analysis unavailable. Please retry.')}
  finally{if(ticket===generation.current){lock.current=false;setBusy(false)}}
 }
 const r=committed?.response.evidence,p=committed?.response.presentation
 const areaLabel=(value:string)=>es?value.replace('Under','Menos de').replace('hectares','hectáreas'):value
 return <section className={`${styles.summary} ${local.workspace}`}><header className={styles.introduction}><p className={styles.eyebrow}>{es?'Inteligencia de Mercado':'Market Intelligence'}</p><h2>{comparablesTitle[language]}</h2><p className={styles.primaryQuestion}>{comparablesQuestion[language]}</p><p>{es?'Selecciona una propiedad existente y las características que deben compartir sus comparables. La propiedad queda excluida de la cohorte.':'Select an existing property and the characteristics its comparables must share. The subject is excluded from the cohort.'}</p></header>
 <form hidden={!editing} className={styles.inputs} onSubmit={apply}><h3>{es?'Propiedad y cohorte':'Property and cohort'}</h3><fieldset disabled={busy} className={styles.fieldset}><div className={styles.inputGrid}>
 <label>{es?'ID del anuncio':'Listing ID'}<input aria-label={es?'ID del anuncio':'Listing ID'} value={draft.subjectListingId} onChange={e=>setDraft({...draft,subjectListingId:e.target.value})} autoComplete="off" placeholder="00000000-0000-0000-0000-000000000000" required/></label>
 <label>{es?'Geografía de la propiedad':'Subject geography'}<select value={draft.geographyLevel} onChange={e=>setDraft({...draft,geographyLevel:e.target.value as ComparablesRequest['geographyLevel']})}>{(['district','canton','province'] as const).map(g=><option key={g} value={g}>{l[g]}</option>)}</select></label>
 <label>{es?'Denominador de área exacta':'Exact-area denominator'}<select value={draft.normalizationBasis} onChange={e=>setDraft({...draft,normalizationBasis:e.target.value as ComparablesRequest['normalizationBasis']})}><option value="land">{es?'Área del terreno':'Property Area'}</option><option value="construction">{es?'Área de construcción':'Construction Area'}</option></select></label></div>
 <p>{es?'Límites obligatorios: mismo tipo de propiedad, banda canónica de área del terreno y, para propiedades mejoradas, banda de área de construcción. La transacción y la base proceden de la propiedad. No se amplía la cohorte automáticamente.':'Compulsory boundaries: same Property Type, canonical Property Area band and, for improved properties, Construction Area band. Transaction and Property Basis come from the subject. The cohort never expands automatically.'}</p>
 <fieldset className={styles.fieldset}><legend>{es?'Características opcionales que deben coincidir':'Optional characteristics to match'}</legend><div className={cohort.dimensions}>{comparableDimensions.map(d=><label key={d}><input type="checkbox" checked={draft.activeDimensions.includes(d)} onChange={e=>setDraft({...draft,activeDimensions:e.target.checked?[...draft.activeDimensions,d]:draft.activeDimensions.filter(x=>x!==d)})}/>{comparableLabels[d][language]}</label>)}</div></fieldset>
 <p>{es?'Cada selección exige la categoría registrada de la propiedad. Todas las selecciones se intersectan. Una característica ausente o ambigua no se interpreta como cero ni se sustituye; la solicitud no se ejecutará con esa selección.':'Each selection requires the subject’s recorded category. All selected dimensions intersect. A missing or ambiguous characteristic is not zero and is not substituted; the request cannot complete with that selection.'}</p>
 <button type="submit" className={styles.apply}>{busy?(es?'Analizando…':'Analyzing…'):(es?'Analizar cohorte':'Analyze Cohort')}</button></fieldset></form>
 {error&&<p className={styles.error} role="alert">{error}</p>}
 <div aria-live="polite" aria-busy={busy}>{committed&&r&&p&&<section className={styles.evidence}><div className={styles.identity}><div><h3 ref={heading} tabIndex={-1}>{es?'Evidencia de la cohorte comparable':'Comparable cohort evidence'}</h3>{committed.response.subjectTitle&&<p>{committed.response.subjectTitle}</p>}<p className={local.id}>{r.listingId}</p></div><button className={styles.modify} disabled={busy} onClick={()=>{setDraft(committed.request);setEditing(true)}}>{es?'Modificar':'Modify'}</button></div>
 {editing&&<p>{es?'La evidencia corresponde a la última pregunta ejecutada.':'Evidence belongs to the last executed question.'}</p>}
 <p>{l[r.transactionType]} · {l[r.propertyBasis]} · {l[r.normalizationBasis]} · {r.transactionType==='rent'?(es?'CRC/m²/mes':'CRC/m²/month'):'CRC/m²'}</p>
 <p>{l[committed.request.geographyLevel]}: {p.geographyOptions.find(g=>g.level===committed.request.geographyLevel)?.label[language]} · {l.type}: {p.baseCohort.propertyType[language]}</p>
 <p>{es?'Banda del área del terreno':'Property Area band'}: {areaLabel(committed.response.areaLabels.property)}{p.baseCohort.constructionAreaRange&&<> · {es?'Banda del área de construcción':'Construction Area band'}: {areaLabel(committed.response.areaLabels.construction??p.baseCohort.constructionAreaRange)}</>}</p>
 <p>{es?'Características seleccionadas':'Selected characteristics'}: {r.activeDimensions.length?r.activeDimensions.map(d=>`${comparableLabels[d][language]}: ${p.optionalDimensions.find(x=>x.dimension===d)?.value[language]??'—'}`).join(' · '):(es?'Ninguna; solo límites obligatorios.':'None; compulsory boundaries only.')}</p>
 <p><strong>{es?'Comparables':'Peers'} n = {r.comparisonPopulationCount}</strong> · {es?'Propiedad excluida por identidad.':'Subject excluded by identity.'}</p>
 {r.status==='no_peers'?<><p>{es?'Precio de la propiedad por m²':'Subject Price / m²'}: {positionNumber(r.propertyPricePerM2,language)} {r.transactionType==='rent'?(es?'CRC/m²/mes':'CRC/m²/month'):'CRC/m²'}</p><p>{es?'No hay comparables en la cohorte definida. La mediana, el percentil y las diferencias no están establecidos. No se amplían los límites.':'No peers in the defined cohort. Median, percentile and differences are not established. Boundaries are not relaxed.'}</p></>:<Evidence r={r} language={language}/>}
 <details><summary>{es?'Formación de la población':'Population trail'}</summary><p>{es?'Población base':'Base population'}: {r.populationTrail.basePopulationCount}</p>{r.populationTrail.steps.map(s=><p key={s.dimension}>{comparableLabels[s.dimension][language]}: {s.beforeCount} → {s.afterCount} ({es?'excluidos':'removed'}: {s.removedCount})</p>)}<p>{es?'Población final':'Final population'}: {r.populationTrail.finalPopulationCount}</p></details>
 <p>{l.date}: {committed.response.analyticalDate}. {committed.response.fx?`BCCR USD → CRC: ${committed.response.fx.rate} · ${committed.response.fx.effectiveDate} · ${es?'referencia de venta':'reference sale'} · ${committed.response.fx.resolutionMode==='exact'?(es?'fecha exacta':'exact date'):(es?'observación anterior aplicable':'applicable prior observation')}`:(es?'Evidencia monetaria de oferta en CRC.':'Asking monetary evidence in CRC.')}</p>
 <AnalysisActions engineType="price-meter" language={language} filters={{analysis_question:'comparables',comparable_request:JSON.stringify(committed.request)}} result={committed.response} defaultName={comparablesTitle[language]}/></section>}</div>
 <details className={styles.method}><summary>{es?'Metodología':'Methodology'}</summary><p>{es?'Una propiedad activa con importe de oferta positivo y áreas exactas válidas. Cohorte limitada por geografía, transacción, tipo, base y bandas de área. Las características seleccionadas se intersectan en orden canónico. Ausencia de membresía no significa una característica negativa. No hay tolerancias inventadas ni valores exactos inferidos de rangos.':'One active property with positive asking amount and valid exact areas. Cohort bounded by geography, transaction, type, basis and area bands. Selected characteristics intersect in canonical order. Absent membership does not imply a negative characteristic. No invented tolerances or exact values inferred from ranges.'}</p><p>{es?'La propiedad se excluye por ID; otras propiedades con atributos o precios iguales permanecen elegibles. Cero comparables no establece estadísticas; uno o más permite la evidencia existente. Percentil de rango medio = 100 × (inferiores + iguales / 2) / n. Diferencia = propiedad − mediana; el porcentaje usa la mediana. Colas estrictas: inferior a P10 o superior a P90.':'The subject is excluded by ID; other properties with equal attributes or prices remain eligible. Zero peers establishes no statistics; one or more permits the existing evidence. Midrank percentile = 100 × (below + equals / 2) / n. Difference = subject − median; percentage uses the median. Strict tails: below P10 or above P90.'}</p><p>{es?'Evidencia agregada de ofertas, no ventas cerradas. No es una puntuación de similitud, confianza o valoración, ni una explicación causal.':'Aggregate asking evidence, not completed sales. This is not a similarity score, confidence score, valuation or causal explanation.'}</p></details>
 <p>{es?'TWUANIS REPORTA EVIDENCIA DEL MERCADO. TWUANIS NO PRESCRIBE DECISIONES.':'TWUANIS REPORTS MARKET EVIDENCE. TWUANIS DOES NOT PRESCRIBE DECISIONS.'}</p></section>
}
export default function ComparableWorkspace(props:{language:'en'|'es';serialized?:string}){return <ComparativeDiscoveryAccess language={props.language}><Workspace key={props.serialized??'new'} {...props}/></ComparativeDiscoveryAccess>}
