'use client'
import {useId} from 'react'
import type {ConstructionLandEvidence as Evidence} from './contract'

export default function ConstructionLandEvidence({evidence,language}:{evidence:Evidence;language:'en'|'es'}){
 const es=language==='es',id=useId(),{context,relationship,cohorts}=evidence
 const number=(n:number)=>new Intl.NumberFormat(es?'es-CR':'en-US',{maximumSignificantDigits:6}).format(n)
 const unit=es?`CRC / m² de ${context.normalizationBasis==='land'?'terreno':'construcción'}`:`CRC / ${context.normalizationBasis==='land'?'land':'construction'} m²`
 const points=relationship.coordinates,maxX=Math.max(1,...points.map(p=>p.constructionToLandRatio)),maxY=Math.max(1,...points.map(p=>p.normalizedPricePerM2))
 const empty=context.marketListingCount===0,represented=relationship.evidence.representedObservationCount
 const absent=es?'No establecido':'Not established'
 return <div data-cl-evidence>
 <section><h3>{es?'¿Cómo difiere la mediana del precio por m² entre cohortes de construcción/terreno?':'How does median Price / m² differ across Construction-to-Land cohorts?'}</h3>
 <p>{es?'Propiedades representadas':'Represented properties'}: n = {represented}. {es?'Cohortes con datos':'Populated cohorts'}: {relationship.evidence.populatedCohortCount}.</p>
 {empty?<p role="status">{es?'No hay propiedades en el mercado definido.':'No properties in the defined market.'}</p>:!represented?<p role="status">{es?'El mercado tiene propiedades, pero ninguna establece ambas áreas exactas y el precio por m² seleccionado.':'The market contains properties, but none establish both exact areas and the selected Price / m² evidence.'}</p>:<>
 <svg viewBox="0 0 400 260" role="img" aria-labelledby={id} style={{width:'100%',maxWidth:700,height:'auto'}}><title id={id}>{es?'Mediana observada de construcción/terreno y mediana del precio por m² por cohorte':'Observed median Construction-to-Land ratio and median Price / m² by cohort'}</title><path d="M45 30V210H380" fill="none" stroke="currentColor"/><text x="45" y="235" fill="currentColor">0</text><text x="380" y="235" textAnchor="end" fill="currentColor">{number(maxX)}</text><text x="45" y="20" textAnchor="start" fill="currentColor" fontSize="12">{number(maxY)}</text>{points.map((p,i)=><circle key={i} cx={45+335*p.constructionToLandRatio/maxX} cy={210-180*p.normalizedPricePerM2/maxY} r="5" fill="#ff6b00"><title>{number(p.constructionToLandRatio)} · {number(p.normalizedPricePerM2)} {unit} · n={p.observationCount}</title></circle>)}</svg>
 <p>{es?'Eje horizontal: mediana de construcción/terreno.':'Horizontal axis: median Construction-to-Land ratio.'}</p><p>{es?'Eje vertical: mediana':'Vertical axis: median'} {unit}. {es?'Cada punto es evidencia agregada; no representa necesariamente una propiedad individual.':'Each point is aggregate evidence; it does not necessarily represent an individual property.'}</p></>}
 <dl>{cohorts.map(c=><div key={c.definition.key} style={{padding:'12px 0',borderBottom:'1px solid #444'}}><dt><strong>{c.definition.minimumExclusive!==null?`${number(c.definition.minimumExclusive)} < C/L`:`${number(c.definition.minimumInclusive!)} ≤ C/L`}{c.definition.maximumExclusive!==null?` < ${number(c.definition.maximumExclusive)}`:''}</strong> · n = {c.n}</dt><dd style={{marginLeft:0}}>{es?'Mediana exacta de C/L':'Median exact C/L'}: {c.medianExactRatio===null?absent:number(c.medianExactRatio)} · {es?'Mediana del precio por m²':'Median Price / m²'}: {c.medianPricePerM2===null?absent:`${number(c.medianPricePerM2)} ${unit}`}</dd></div>)}</dl></section>
 <section><h3>{es?'¿Qué asociación de rangos se observa entre construcción/terreno y precio por m²?':'What rank association is observed between Construction-to-Land ratio and Price / m²?'}</h3><p>Spearman ρ: <strong>{relationship.spearmanRho===null?absent:number(relationship.spearmanRho)}</strong></p>{relationship.spearmanRho===null&&<p>{relationship.evidence.hasSufficientEvidence?(es?'Los rangos no permiten establecer la correlación.':'The ranks do not establish a computable correlation.'):(es?'Se requieren al menos 3 cohortes con datos y 12 propiedades representadas.':'At least 3 populated cohorts and 12 represented properties are required.')}</p>}</section>
 <details><summary>{es?'Metodología y límites':'Methodology and limits'}</summary><p>{es?'C/L = área exacta de construcción ÷ área exacta del terreno. Ambas deben ser positivas, finitas y analíticamente utilizables. Los rangos no sustituyen mediciones exactas. C/L puede superar 1.':'C/L = exact Construction Area ÷ exact Property Area. Both must be positive, finite and analytically usable. Ranges do not substitute for exact measurements. C/L may exceed 1.'}</p><p>{es?'C/L no establece cobertura del suelo, huella del edificio, densidad, FAR ni capacidad de desarrollo.':'C/L does not establish site coverage, building footprint, density, FAR or development capacity.'}</p><p>{context.normalizationBasis==='land'?(es?'C/L = C/L y precio por m² = P/L comparten el terreno como denominador.':'C/L = C/L and Price / m² = P/L share land area as a denominator.'):(es?'El área de construcción está en el numerador de C/L y en el denominador de P/C.':'Construction Area appears in the numerator of C/L and the denominator of P/C.')}</p><p>{es?'Spearman usa las medianas de las cohortes, con rangos promedio en los empates. La asociación es descriptiva, no causal. No se calcula regresión, R² ni cambio porcentual modelado.':'Spearman uses cohort medians, with average ranks for ties. Association is descriptive, not causal. No regression, R² or modeled percentage change is calculated.'}</p></details>
 <p>{es?'TWUANIS REPORTA EVIDENCIA DEL MERCADO. TWUANIS NO PRESCRIBE DECISIONES.':'TWUANIS REPORTS MARKET EVIDENCE. TWUANIS DOES NOT PRESCRIBE DECISIONS.'}</p>
 </div>
}
