'use client'
import {useEffect,useId,useRef,useState} from 'react'
import {executePriceMeterApply} from '@/lib/price-meter-apply-action'
import {validatePriceMeterApply} from '@/lib/price-meter-apply-contract'
import {validateDistributionIdentity} from '@/lib/price-meter-selected-contract'
import {summaryKeys,summaryOptions,summaryLabel,summaryIdentity,summarySnapshot} from '../market-summary/contract'
import {applyFilterChange} from '../market-filters/utils'
import type {ExplorerOptions,Filters} from '../market-filters/types'
import FilterSelect from '../market-filters/FilterSelect'
import AnalysisActions from '../AnalysisActions'
import {distributionQuestion,type DistributionEvidence,type DistributionContext} from './contract'
import styles from '../market-summary/workspace.module.css'
import chart from './distribution.module.css'
export default function DistributionWorkspace({options,filters,language,source}:{options:ExplorerOptions;filters:Filters;language:'en'|'es';source:'workspace'|'standalone'}){
 const es=language==='es',id=useId(),title=es?'Distribución del precio por m²':'Price / m² Distribution'
 const [draft,setDraft]=useState(()=>summarySnapshot(filters)),[basis,setBasis]=useState(filters.property_basis??''),[normalization,setNormalization]=useState(filters.normalization_basis??'')
 const [open,setOpen]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(false)
 const [committed,setCommitted]=useState<{filters:Filters;labels:string[];result:Awaited<ReturnType<typeof executePriceMeterApply>>;context:DistributionContext;evidence:DistributionEvidence}|null>(null)
 const generation=useRef(0),inFlight=useRef(false),heading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>()=>{generation.current++},[])
 useEffect(()=>{if(committed)heading.current?.focus()},[committed])
 const incoming=JSON.stringify(filters),previous=useRef(incoming)
 useEffect(()=>{if(previous.current!==incoming){previous.current=incoming;generation.current++;inFlight.current=false;setPending(false);setDraft(summarySnapshot(filters));setBasis(filters.property_basis??'');setNormalization(filters.normalization_basis??'');setOpen(true);setError(false)}},[incoming,filters])
 async function apply(){if(inFlight.current)return;let snapshot:Filters,labels:string[],identity:ReturnType<typeof validateDistributionIdentity>
 try{snapshot=validatePriceMeterApply(draft);labels=summaryIdentity(snapshot,options,language);identity=validateDistributionIdentity({propertyBasis:basis,normalizationBasis:normalization})}catch{setError(true);return}
 const ticket=++generation.current;inFlight.current=true;setPending(true);setError(false)
 try{const result=await executePriceMeterApply(snapshot,language,source,['distribution'],identity)
 if(ticket!==generation.current)return
 const context=result.distributionContext as DistributionContext
 const intelligence='saleIntelligence' in result?result.saleIntelligence:result.rentIntelligence
 const values=Object.values(intelligence.distributions) as DistributionEvidence[]
 if(values.length!==1||!context||context.propertyBasis!==identity.propertyBasis||context.normalizationBasis!==identity.normalizationBasis||context.transactionType!==snapshot.transaction_type)throw Error('Invalid distribution response')
 setCommitted({filters:{...snapshot,property_basis:identity.propertyBasis,normalization_basis:identity.normalizationBasis},labels,result,context,evidence:values[0]});setOpen(false)
 }catch{if(ticket===generation.current)setError(true)}finally{if(ticket===generation.current){inFlight.current=false;setPending(false)}}}
 const nf=new Intl.NumberFormat(es?'es-CR':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2}),integer=new Intl.NumberFormat(es?'es-CR':'en-US')
 function field(key:typeof summaryKeys[number]){return <FilterSelect key={key} compact label={summaryLabel(key,language)} filterKey={key} options={summaryOptions(key,options,language,draft)} filters={draft} language={language} onFilterChange={(k,v)=>setDraft(d=>k==='accessibility'?{...d,[k]:v||undefined}:applyFilterChange(d,k,v))} emptyLabel={['transaction_type','property_type','province','canton'].includes(key)?(es?'Seleccionar (obligatorio)':'Select (required)'):(es?'Sin restricción':'Unrestricted')}/>}
 const valueText=(v:number)=>v>0&&v<0.005?new Intl.NumberFormat(es?'es-CR':'en-US',{maximumSignificantDigits:4}).format(v):nf.format(v)
 const c=committed?.context,d=committed?.evidence
 const unit=c?(es?`CRC / m² de ${c.normalizationBasis==='land'?'terreno':'construcción'}`:`CRC / ${c.normalizationBasis==='land'?'land':'construction'} m²`):''
 const stats=d?[['minimum',es?'Mínimo observado':'Observed minimum'],['p10','P10'],['p25','P25'],['median',es?'Mediana':'Median'],['p75','P75'],['p90','P90'],['maximum',es?'Máximo observado':'Observed maximum']]as const:[]
 return <article className={styles.summary} aria-label={title}>
 <header className={styles.introduction}><p className={styles.eyebrow}>{es?'Precio por m²':'Price / m²'}</p><h2>{title}</h2><p className={styles.primaryQuestion}>{distributionQuestion[language]}</p></header>
 {committed&&c&&<div className={styles.identity}><div><p className={styles.eyebrow}>{es?'Definición del mercado':'Market definition'}</p><ul>{committed.labels.map((s,i)=><li key={i}>{s}</li>)}</ul><p className={styles.eyebrow} style={{marginTop:20}}>{es?'Definición del precio por m²':'Price / m² definition'}</p><p data-ppm2-identity>{c.propertyBasis==='land_only'?(es?'Terreno sin construcción':'Vacant Land'):(es?'Propiedad con construcción':'Improved Property')} · {unit} · {c.transactionType==='rent'?(es?'Precio de oferta mensual de alquiler':'Monthly rental asking price'):(es?'Precio de oferta de venta':'Sale asking price')}</p><p>{es?'Fecha analítica':'Analytical date'}: {c.analyticalDate}. {c.fx?`${c.fx.source} USD → CRC: ${c.fx.rate} · ${es?'Referencia de venta':'Reference sale'} · ${c.fx.effectiveDate}`:(es?'Sin conversión USD en el contexto adquirido.':'No USD conversion in the acquired context.')}</p></div><button type="button" className={styles.modify} aria-expanded={open} aria-controls={id} disabled={pending} onClick={()=>setOpen(!open)}>{es?'Modificar':'Modify'}</button></div>}
 <section id={id} hidden={!open} className={styles.inputs}><fieldset disabled={pending} className={styles.fieldset}><legend>{es?'Definir el mercado':'Define the market'}</legend><p>{es?'Transacción, tipo de propiedad, provincia y cantón son obligatorios.':'Transaction, Property Type, Province and Canton are required.'}</p><div className={styles.inputGrid}>{summaryKeys.slice(0,5).map(field)}</div><details className={styles.optional}><summary>{es?'Restricciones opcionales':'Optional constraints'}</summary><div className={styles.inputGrid}>{summaryKeys.slice(5).map(field)}</div></details>
 <h3>{es?'Definir precio por m²':'Define Price / m²'}</h3><div className={`${styles.inputGrid} ${chart.controls}`}><label>{es?'Base de propiedad':'Property Basis'}<select aria-label={es?'Base de propiedad':'Property Basis'} value={basis} onChange={e=>{setBasis(e.target.value);setNormalization(e.target.value==='land_only'?'land':'')}}><option value="">{es?'Seleccionar':'Select'}</option><option value="land_only">{es?'Terreno sin construcción':'Vacant Land'}</option><option value="improved_property">{es?'Propiedad con construcción':'Improved Property'}</option></select></label>{basis==='land_only'?<p>{es?'Normalización: área del terreno (única opción válida).':'Normalization: Land Area (only valid choice).'}</p>:basis==='improved_property'?<label>{es?'Normalización':'Normalization'}<select aria-label={es?'Normalización':'Normalization'} value={normalization} onChange={e=>setNormalization(e.target.value)}><option value="">{es?'Seleccionar':'Select'}</option><option value="land">{es?'Área del terreno':'Land Area'}</option><option value="construction">{es?'Área de construcción':'Construction Area'}</option></select></label>:null}</div><button type="button" className={styles.apply} disabled={pending} onClick={apply}>{pending?(es?'Analizando…':'Analyzing…'):(es?'Analizar distribución del precio por m²':'Analyze Price / m² Distribution')}</button></fieldset></section>
 {error&&<p role="alert" className={styles.error}>{es?'Revisa las entradas requeridas. No se pudo completar el análisis; el resultado anterior se conserva.':'Check required inputs. Analysis could not complete; the previous result is retained.'}</p>}
 {committed&&c&&d&&<div aria-live="polite" aria-busy={pending} data-ppm2-result><section className={styles.evidence}><h3 ref={heading} tabIndex={-1}>{title} — {unit}</h3><p className={styles.sectionQuestion}>{distributionQuestion[language]}</p><p data-ppm2-n>{es?'Observaciones elegibles':'Eligible observations'}: <strong>{integer.format(d.sampleSize)}</strong> · {es?'Anuncios del mercado definido':'Defined-market listings'}: {integer.format(c.marketListingCount)}</p>
 {d.sampleSize===0?<p>{c.marketListingCount===0?(es?'El mercado definido no contiene anuncios.':'The defined market contains no listings.'):(es?'No se establecieron observaciones elegibles para esta definición de precio por m².':'No eligible observations were established for this Price / m² definition.')}</p>:<><p className={styles.count}><strong data-ppm2-median>{valueText(d.median!)}</strong><span>{es?'Mediana':'Median'} · {unit}</span></p><div className={chart.ruler} role="img" aria-label={es?'Posiciones de cuantiles en escala lineal entre mínimo y máximo observados. Valores exactos debajo.':'Quantile positions on a linear scale from observed minimum to maximum. Exact values below.'}>{stats.map(([key,label])=><span key={key} title={label} style={{left:`${d.maximum===d.minimum?50:(d[key]!-d.minimum!)/(d.maximum!-d.minimum!)*100}%`}}/>)}</div><p>{es?'Escala lineal completa del mínimo al máximo observado; no se recortan extremos.':'Full linear scale from observed minimum to maximum; extremes are not clipped.'}</p><dl className={chart.values}>{stats.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{valueText(d[key]!)} <small>{unit}</small></dd></div>)}</dl></>}
 </section><details className={styles.method}><summary>{es?'Metodología':'Methodology'}</summary><p>{es?'Una distribución corresponde a una transacción, base de propiedad y normalización. Cada observación divide el precio de oferta normalizado a CRC por el área exacta elegible del anuncio. Los rangos restringen el mercado; no sustituyen medidas exactas. Base desconocida y evidencia no elegible no producen observaciones.':'One distribution represents one transaction, Property Basis and normalization. Each observation divides the CRC-normalized asking price by the listing’s eligible exact area. Ranges constrain the market; they do not substitute exact measurements. Unknown basis and ineligible evidence do not produce observations.'}</p><p>{es?'Los cuantiles se establecen en el servidor mediante interpolación lineal sobre observaciones ordenadas. n permanece explícito. No se infiere valor, causalidad ni confianza cualitativa. La relación construcción/terreno no establece huella ni cobertura.':'Quantiles are established server-side by linear interpolation over ordered observations. n remains explicit. No value judgment, causation or qualitative confidence is inferred. Construction/land ratio does not establish footprint or site coverage.'}</p></details><AnalysisActions engineType="price-meter" language={language} filters={{...committed.filters,analysis_question:'distribution'}} result={committed.result} defaultName={title}/></div>}
 </article>
}
