import type {PriceMeterComparableBrowserDimension as Dimension,PriceMeterComparableBrowserEvidence,PriceMeterComparableBrowserPresentation} from './price-meter-comparable-browser-contract'
export const comparablesTitle={en:'User-Defined Comparable Cohort',es:'Cohorte comparable definida por el usuario'}
export const comparablesQuestion={en:"How does this property's asking Price / m² compare with the cohort matching its compulsory boundaries and selected canonical characteristics?",es:'¿Cómo se compara el precio de oferta por m² de esta propiedad con la cohorte que cumple sus límites obligatorios y las características canónicas seleccionadas?'}
export const comparableDimensions:Dimension[]=['bedrooms','bathrooms','parking','year_built','construction_land','environment','terrain','utility','accessibility','legal_status']
export const comparableLabels:Record<Dimension,{en:string;es:string}>={bedrooms:{en:'Bedrooms',es:'Habitaciones'},bathrooms:{en:'Bathrooms',es:'Baños'},parking:{en:'Parking',es:'Estacionamiento'},year_built:{en:'Year Built',es:'Año de construcción'},construction_land:{en:'Construction-to-Land',es:'Construcción/terreno'},environment:{en:'Environment',es:'Entorno'},terrain:{en:'Terrain',es:'Terreno'},utility:{en:'Utilities',es:'Servicios'},accessibility:{en:'Accessibility',es:'Accesibilidad'},legal_status:{en:'Legal Status',es:'Estado legal'}}
export type ComparablesRequest={subjectListingId:string;geographyLevel:'province'|'canton'|'district';normalizationBasis:'land'|'construction';activeDimensions:Dimension[]}
// Browser intent validation only; canonical eligibility and authorization remain server-owned.
export function parseComparablesRequest(input:unknown):ComparablesRequest{
 if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Invalid request')
 const v=input as Record<string,unknown>
 if(Object.keys(v).length!==4||Object.keys(v).some(k=>!['subjectListingId','geographyLevel','normalizationBasis','activeDimensions'].includes(k))||typeof v.subjectListingId!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v.subjectListingId.trim())||!['province','canton','district'].includes(String(v.geographyLevel))||!['land','construction'].includes(String(v.normalizationBasis))||!Array.isArray(v.activeDimensions)||v.activeDimensions.length>10||new Set(v.activeDimensions).size!==v.activeDimensions.length||v.activeDimensions.some(d=>!comparableDimensions.includes(d)))throw Error('Invalid request')
 return {subjectListingId:v.subjectListingId.trim(),geographyLevel:v.geographyLevel as ComparablesRequest['geographyLevel'],normalizationBasis:v.normalizationBasis as ComparablesRequest['normalizationBasis'],activeDimensions:comparableDimensions.filter(d=>(v.activeDimensions as unknown[]).includes(d))}
}
export type ComparablesResponse={access:'authentication_required'|'entitlement_required'}|{error:'invalid_request'|'execution_unavailable'}|{evidence:PriceMeterComparableBrowserEvidence;presentation:PriceMeterComparableBrowserPresentation;subjectTitle:string|null;areaLabels:{property:string;construction:string|null};analyticalDate:string;fx:null|{rate:number;effectiveDate:string;source:string;resolutionMode:string}}
