export const contextText={
 en:{title:'Price / m² Difference Context',geographic:'Geographic context',size:'Size relationship',ratio:'Construction-to-Land market relationship',characteristic:'Explicit characteristic comparison',add:'Add A/B comparison',remove:'Remove comparison',commit:'Run selected contexts',loading:'Loading selected evidence…',error:'Context request unavailable.',select:'Select',optional:'Not constrained',reference:'Percentage reference',propertyType:'Property Type',propertyArea:'Property Area',constructionArea:'Construction Area',constructionLand:'C:L cohort',province:'Province',canton:'Canton',district:'District',characteristicType:'Characteristic type',characteristicValue:'Positive characteristic',population:'Population',represented:'Represented observations',subject:'Subject included',yes:'Yes',no:'No',unknown:'Not established',details:'Quantitative evidence',coordinate:'Median observed coordinate',rank:'Rank',difference:'Signed difference',percentage:'Percentage difference',denominator:'Percentage denominator',state:'State',native:'Native CRC',bccr:'BCCR reference sale conversion',unconstrained:'Unconstrained',boundary:'Contextual evidence is independently observed and may describe different explicitly identified populations. It is presented alongside the subject’s Phase 12 difference. It does not establish causation or decompose that difference.'},
 es:{title:'Contexto de la diferencia de precio por m²',geographic:'Contexto geográfico',size:'Relación con el tamaño',ratio:'Relación de mercado construcción/terreno',characteristic:'Comparación explícita de características',add:'Agregar comparación A/B',remove:'Eliminar comparación',commit:'Ejecutar contextos seleccionados',loading:'Cargando evidencia seleccionada…',error:'Solicitud de contexto no disponible.',select:'Seleccione',optional:'Sin restricción',reference:'Referencia porcentual',propertyType:'Tipo de propiedad',propertyArea:'Área de terreno',constructionArea:'Área de construcción',constructionLand:'Cohorte C:L',province:'Provincia',canton:'Cantón',district:'Distrito',characteristicType:'Tipo de característica',characteristicValue:'Característica positiva',population:'Población',represented:'Observaciones representadas',subject:'Propiedad incluida',yes:'Sí',no:'No',unknown:'No establecido',details:'Evidencia cuantitativa',coordinate:'Coordenada exacta observada mediana',rank:'Rango',difference:'Diferencia con signo',percentage:'Diferencia porcentual',denominator:'Denominador porcentual',state:'Estado',native:'CRC nativo',bccr:'Conversión de venta de referencia BCCR',unconstrained:'Sin restricción',boundary:'La evidencia contextual se observa de forma independiente y puede describir poblaciones diferentes, identificadas explícitamente. Se presenta junto a la diferencia de la Fase 12 de la propiedad. No establece causalidad ni descompone esa diferencia.'}
} as const
const vocabulary:Record<string,[string,string]>={
 established:['Established','Establecido'],not_established:['Not established','No establecido'],not_applicable:['Not applicable','No aplicable'],withheld:['Withheld','No autorizado'],execution_unavailable:['Execution unavailable','Ejecución no disponible'],invalid_request:['Invalid request','Solicitud inválida'],
 position_prerequisite_failed:['Phase 12 prerequisite not established; context not executed.','Requisito de Fase 12 no establecido; contexto no ejecutado.'],
 district_has_no_child_level:['District has no authorized child comparison level.','El Distrito no tiene un nivel inferior autorizado para comparar.'],
 no_child_observations:['No child-geography observations established.','No se establecieron observaciones de geografía inferior.'],
 normalization_mismatch:['Question does not match the committed normalization.','La pregunta no coincide con la normalización confirmada.'],
 improved_property_required:['This methodology requires Improved Property.','Esta metodología requiere una propiedad con construcción.'],
 exact_subject_ratio_not_established:['Exact subject C:L identity is not established.','La identidad C:L exacta de la propiedad no está establecida.'],
 requires_three_populated_bands:['Requires at least three populated bands.','Requiere al menos tres bandas pobladas.'],
 requires_three_cohorts_and_twelve_observations:['Requires three populated cohorts and twelve represented observations.','Requiere tres cohortes pobladas y doce observaciones representadas.'],
 requires_eight_per_cohort:['Requires at least eight observations in each cohort.','Requiere al menos ocho observaciones en cada cohorte.'],
 mathematical_degeneracy:['Mathematical result not established.','Resultado matemático no establecido.'],
 no_represented_observations:['No represented observations.','Sin observaciones representadas.'],
 shared_property_area_mathematical_coupling:['Withheld: shared Property Area mathematical coupling.','No autorizado: acoplamiento matemático por área de terreno compartida.'],
 shared_construction_area_mathematical_coupling:['Withheld: shared Construction Area mathematical coupling.','No autorizado: acoplamiento matemático por área de construcción compartida.'],
 invalid_comparison_definition:['Invalid explicit A/B definition, duplicate, or unsupported identity.','Definición A/B inválida, duplicada o identidad no compatible.'],
 comparison_resolution_unavailable:['Comparison definitions could not be resolved.','No se pudieron resolver las definiciones de comparación.'],
 context_evidence_incomplete:['Complete contextual evidence could not be acquired.','No se pudo adquirir evidencia contextual completa.'],
 context_execution_unavailable:['Context calculation unavailable.','Cálculo de contexto no disponible.'],empty_cohort:['Empty cohort.','Cohorte vacía.'],
 populated_bands:['Populated bands','Bandas pobladas'],populated_cohorts:['Populated cohorts','Cohortes pobladas'],represented_observations:['Represented observations','Observaciones representadas'],spearman_rho:['Spearman rho','Rho de Spearman'],log_log_alpha:['Log-log alpha','Alfa log-log'],log_log_beta:['Log-log slope','Pendiente log-log'],modeled_ten_percent_area_change:['Modeled 10% area change','Cambio modelado del 10% del área'],r_squared:['R²','R²'],regression:['Regression','Regresión'],subject_construction_land_ratio:['Subject C:L ratio (not Site Coverage)','Relación C:L de la propiedad (no cobertura del suelo)'],median_a:['Median A','Mediana A'],median_b:['Median B','Mediana B'],median_a_minus_b:['Median A − median B','Mediana A − mediana B'],percent_difference:['Percentage difference','Diferencia porcentual'],
 selected_market_median:['Selected market median','Mediana del mercado seleccionado'],cohort_A:['Cohort A median','Mediana de la cohorte A'],cohort_B:['Cohort B median','Mediana de la cohorte B'],
 minimum:['Minimum','Mínimo'],maximum:['Maximum','Máximo'],median:['Median','Mediana'],iqr:['IQR','RIC'],bedrooms:['Bedrooms','Habitaciones'],bathrooms:['Bathrooms','Baños'],parking:['Parking','Estacionamiento'],year_built:['Year built','Año de construcción'],utility:['Utility','Servicio'],environment:['Environment','Entorno'],terrain:['Terrain','Terreno'],accessibility:['Accessibility','Accesibilidad'],legal_status:['Legal status','Estado legal']
}
export function contextLabel(key:string,lang:'en'|'es') {return vocabulary[key]?.[lang==='en'?0:1]??key}
