import type { PositionState } from './price-meter-property-position-browser-contract'
export const positionLabels = {
  en: { sale:'Sale', rent:'Rent', land_only:'Vacant Land', improved_property:'Improved Property', title:'Property Price / m² Position — Phase 12', geography:'Reference geography', district:'District', canton:'Canton', province:'Province', normalization:'Normalization', land:'Land', construction:'Construction', choose:'Select a reference geography', loading:'Loading evidence…', subject:'Subject Price / m²', type:'Fixed Property Type', areas:'Property Area and Construction Area: unconstrained reference population', included:'The actual subject observation is included exactly once.', n:'Population n', complete:'Complete reference evidence', median:'Reference median', percentile:'Percentile (midrank)', difference:'Difference from reference median', denominator:'Percentage denominator: selected population median', distribution:'Distribution and position evidence', minimum:'Minimum', maximum:'Maximum', iqr:'IQR', below:'Below', equal:'Equal', above:'Above', interval:'Distribution interval', tail:'Tail threshold', tailDifference:'Difference from threshold', ratio:'Subject Construction-to-Land ratio (not Site Coverage)', date:'Analytical date', native:'Canonical monetary evidence in CRC.', fx:'USD converted to analytical CRC using BCCR reference sale methodology.', access:'Sign in with Price / m² Intelligence access to view this evidence.', districtMissing:'Canonical District is not established. Select an available scope explicitly.', boundary:'TWUANIS REPORTS MARKET EVIDENCE. TWUANIS DOES NOT PRESCRIBE DECISIONS.' },
  es: { sale:'Venta', rent:'Alquiler', land_only:'Terreno sin construcción', improved_property:'Propiedad con construcción', title:'Posición del precio por m² de la propiedad — Fase 12', geography:'Geografía de referencia', district:'Distrito', canton:'Cantón', province:'Provincia', normalization:'Normalización', land:'Terreno', construction:'Construcción', choose:'Seleccione una geografía de referencia', loading:'Cargando evidencia…', subject:'Precio por m² de la propiedad', type:'Tipo de propiedad fijo', areas:'Área de terreno y construcción: población de referencia sin restricciones de área', included:'La observación real de la propiedad se incluye exactamente una vez.', n:'Población n', complete:'Evidencia de referencia completa', median:'Mediana de referencia', percentile:'Percentil (rango medio)', difference:'Diferencia respecto a la mediana de referencia', denominator:'Denominador del porcentaje: mediana de la población seleccionada', distribution:'Evidencia de distribución y posición', minimum:'Mínimo', maximum:'Máximo', iqr:'RIC', below:'Inferiores', equal:'Iguales', above:'Superiores', interval:'Intervalo de distribución', tail:'Umbral de la cola', tailDifference:'Diferencia respecto al umbral', ratio:'Relación construcción/terreno de la propiedad (no cobertura del suelo)', date:'Fecha analítica', native:'Evidencia monetaria canónica en CRC.', fx:'USD convertido a CRC analíticos mediante la metodología de venta de referencia del BCCR.', access:'Inicie sesión con acceso a Inteligencia de precio por m² para ver esta evidencia.', districtMissing:'No se ha establecido el Distrito canónico. Seleccione explícitamente un ámbito disponible.', boundary:'TWUANIS REPORTA EVIDENCIA DEL MERCADO. TWUANIS NO PRESCRIBE DECISIONES.' }
} as const
const messages: Record<Exclude<PositionState,'ok'>, [string,string]> = {
 subject_unavailable:['Active canonical subject unavailable.','Propiedad canónica activa no disponible.'],
 subject_ineligible:['An eligible canonical observation is not established.','No se ha establecido una observación canónica elegible.'],
 normalization_not_applicable:['Exact evidence for this normalization is not established.','No se ha establecido evidencia exacta para esta normalización.'],
 reference_definition_invalid:['The reference question is not established.','No se ha establecido la pregunta de referencia.'],
 reference_evidence_incomplete:['Complete reference evidence could not be established. No position was calculated.','No se pudo establecer evidencia de referencia completa. No se calculó una posición.'],
 reference_population_empty:['The complete external reference contains no observations.','La referencia externa completa no contiene observaciones.'],
 subject_participation_invalid:['The reference does not contain the subject exactly once with consistent evidence.','La referencia no contiene la propiedad exactamente una vez con evidencia coherente.'],
 execution_unavailable:['This analysis is temporarily unavailable.','Este análisis no está disponible temporalmente.']
}
export const positionStateText = (state: Exclude<PositionState,'ok'>, lang: 'en'|'es') => messages[state][lang === 'en' ? 0 : 1]
export const positionNumber = (value: number | null, lang: 'en'|'es', signed=false) => value === null ? '—' : new Intl.NumberFormat(lang === 'en' ? 'en-US' : 'es-CR',{maximumFractionDigits:2,signDisplay:signed?'exceptZero':'auto'}).format(value)
export const positionIntervals = {
 below_p10:'< P10', p10_to_p25:'P10 ≤ x < P25', p25_to_median:'P25 ≤ x < P50', at_median:'x = P50', median_to_p75:'P50 < x ≤ P75', p75_to_p90:'P75 < x ≤ P90', above_p90:'> P90'
} as const
