'use client'
import type {SizeContext,SizeEvidence as Evidence} from './contract'
import styles from '../market-summary/workspace.module.css'
import css from './size.module.css'

export default function SizeEvidence({context:c,evidence:e,language}:{context:SizeContext;evidence:Evidence;language:'en'|'es'}){
 const es=language==='es',nf=new Intl.NumberFormat(es?'es-CR':'en-US',{maximumFractionDigits:3})
 const number=(n:number)=>n!==0&&Math.abs(n)<.001?new Intl.NumberFormat(es?'es-CR':'en-US',{maximumSignificantDigits:4}).format(n):nf.format(n)
 const unit=es?`CRC / m² de ${c.normalizationBasis==='land'?'terreno':'construcción'}`:`CRC / ${c.normalizationBasis==='land'?'land':'construction'} m²`
 const bands=e.population.bands,points=bands.filter(b=>b.observationCount>0&&b.medianExactArea!==null&&b.medianNormalizedRatio!==null)
 // Display scales only. Server-established medians and model statistics are never recomputed.
 const maxX=Math.max(1,...points.map(b=>b.medianExactArea!)),maxY=Math.max(1,...points.map(b=>b.medianNormalizedRatio!))
 const label=(b:typeof bands[number])=>b.label.replace(/\d[\d,]*/g,value=>nf.format(Number(value.replaceAll(',','')))).replace('Under ',es?'Menos de ':'Under ').replace('hectares',es?'hectáreas':'hectares')
 const r=e.result,stats=[['Spearman ρ',es?'Asociación por rangos entre coordenadas de cohortes':'Rank association among cohort coordinates',r.spearmanRho],
 [es?'Pendiente log-log β':'Log-log slope β',es?'Relación ajustada entre log(área) y log(precio por m²)':'Fitted relationship between log(area) and log(Price / m²)',r.regression?.beta??null],
 ['R²',es?'Ajuste del mismo modelo log-log':'Fit of the same log-log model',r.regression?.rSquared??null]] as const
 return <div data-size-evidence>
 <section className={styles.evidence}><h3>{es?'Precio por m² por cohorte de tamaño':'Size Cohort Price / m²'}</h3><p className={styles.sectionQuestion}>{es?'¿Cómo difiere la mediana del precio por m² entre las cohortes del tamaño seleccionado?':'How does median Price / m² differ across the selected size cohorts?'}</p>
 <p>{es?'Anuncios del mercado definido':'Defined-market listings'}: {number(c.marketListingCount)} · {es?'Observaciones representadas':'Represented observations'}: <strong>{number(r.evidence.representedObservationCount)}</strong> · {es?'Cohortes con datos':'Populated cohorts'}: {r.evidence.populatedBandCount}</p>
 {!points.length?<p>{c.marketListingCount===0?(es?'El mercado definido no contiene anuncios.':'The defined market contains no listings.'):(es?'No se establecieron observaciones elegibles con área exacta para este análisis.':'No eligible observations with exact area were established for this analysis.')}</p>:<>
 <p>{es?'Coordenadas agregadas observadas. Eje X: mediana del área exacta (m²). Eje Y: mediana del precio por m². Escalas lineales desde cero.':'Observed aggregate coordinates. X: median exact area (m²). Y: median Price / m². Linear scales from zero.'}</p>
 <svg viewBox="0 0 640 340" className={css.plot} role="img" aria-label={es?'Coordenadas de cohortes; valores exactos en la lista siguiente.':'Cohort coordinates; exact values in the following list.'}>
 <line x1="80" y1="275" x2="590" y2="275"/><line x1="80" y1="30" x2="80" y2="275"/>
 <text x="72" y="294">0</text><text x="585" y="298" textAnchor="end">{number(maxX)} m²</text><text x="80" y="21">{number(maxY)} {unit}</text>
 {points.map((b,i)=><g key={b.range}><circle cx={80+b.medianExactArea!/maxX*500} cy={275-b.medianNormalizedRatio!/maxY*230} r="6"/><text x={80+b.medianExactArea!/maxX*500} y={262-b.medianNormalizedRatio!/maxY*230} textAnchor="middle">{i+1}</text></g>)}
 </svg></>}
 <ol className={css.bands}>{bands.map(b=><li key={b.range} data-size-band><strong>{points.includes(b)?`${points.indexOf(b)+1}. `:''}{label(b)}</strong><dl className={css.values}><div><dt>{es?'Mediana del área exacta':'Median exact area'}</dt><dd>{b.medianExactArea===null?'—':`${number(b.medianExactArea)} m²`}</dd></div><div><dt>{es?'Mediana del precio por m²':'Median Price / m²'}</dt><dd>{b.medianNormalizedRatio===null?'—':`${number(b.medianNormalizedRatio)} ${unit}`}</dd></div><div><dt>n</dt><dd>{b.observationCount}</dd></div></dl>{b.observationCount===0&&<small>{es?'Sin observaciones; medianas no establecidas.':'No observations; medians not established.'}</small>}</li>)}</ol></section>
 <section className={styles.evidence}><h3>{es?'Relación estadística':'Statistical Relationship'}</h3><p className={styles.sectionQuestion}>{es?'¿Qué relación estadística se observa entre la dimensión de tamaño seleccionada y el precio por m²?':'What statistical relationship is observed between the selected size dimension and Price / m²?'}</p><p>{es?'Coordenadas agregadas de entrada':'Aggregate input coordinates'}: {r.evidence.populatedBandCount}. {es?'Observaciones representadas':'Represented observations'}: {r.evidence.representedObservationCount}.</p>
 <dl className={css.stats}>{stats.filter(s=>s[2]!==null).map(([title,description,value])=><div key={title}><dt>{title}<small>{description}</small></dt><dd>{number(value!)}</dd></div>)}</dl>
 {stats.some(s=>s[2]===null)&&<p>{!r.evidence.hasSufficientBandEvidence?(es?'Se requieren al menos tres cohortes con datos para calcular las estadísticas de relación.':'At least three populated cohorts are required to calculate relationship statistics.'):`${stats.filter(s=>s[2]===null).map(s=>s[0]).join(', ')}: ${es?'no establecido bajo los requisitos matemáticos actuales.':'not established under the current mathematical requirements.'}`}</p>}
 <p className={css.coupling}>{es?'El área seleccionada también está en el denominador del precio por m². La asociación entre estas variables matemáticamente vinculadas no establece un efecto causal independiente del tamaño.':'The selected area is also in the Price / m² denominator. Association between these mathematically coupled variables does not establish an independent causal effect of size.'}</p></section>
 <details className={styles.method}><summary>{es?'Metodología':'Methodology'}</summary><p>{es?'Los rangos restringen pertenencia; no son medidas exactas. Cada punto usa la mediana del área exacta y la mediana del precio de oferta normalizado a CRC por m² de su cohorte. Es una coordenada agregada; no necesariamente corresponde a un anuncio real.':'Ranges constrain membership; they are not exact measurements. Each point uses its cohort’s median exact area and median CRC-normalized asking Price / m². It is an aggregate coordinate, not necessarily a real listing.'}</p><p>{es?'Spearman usa rangos con empates promediados de las coordenadas de cohortes. El modelo ajusta ln(precio por m²) = α + β ln(área) sobre esas mismas coordenadas, no sobre todos los anuncios individuales. R² describe el ajuste en espacio logarítmico; no es confianza ni exactitud predictiva.':'Spearman uses average tied ranks of cohort coordinates. The model fits ln(Price / m²) = α + β ln(area) over those same coordinates, not over every individual listing. R² describes fit in log space; it is not confidence or predictive accuracy.'}</p><p>{es?'Los límites inferiores finitos de las cohortes se incluyen; los superiores finitos se excluyen. Los valores extremos permanecen representados. Cada estadística conserva sus requisitos de cálculo; una ausencia no se reemplaza con cero.':'Finite lower cohort boundaries are inclusive; finite upper boundaries are exclusive. Extreme values remain represented. Each statistic retains its computability requirements; absence is not replaced by zero.'}</p></details>
 </div>
}
