import type {PriceMeterCrossDimensionalResult} from '@/lib/price-meter-cross-dimensional-result-contract'
import {getPriceMeterCrossDimensionalPresentation} from '@/lib/price-meter-cross-dimensional-presentation'
import CrossPlot from './CrossPlot'
import styles from './cross.module.css'

// Render only server-established aggregate evidence. Formatting is not analysis.
export default function CrossEvidence({result:r,language}:{result:PriceMeterCrossDimensionalResult;language:'en'|'es'}){
 const es=language==='es',t=(en:string,sp:string)=>es?sp:en
 const f=(v:number|null,d=3)=>v===null?'—':new Intl.NumberFormat(es?'es-CR':'en-US',{maximumFractionDigits:d}).format(v)
 const price=(v:number|null)=>v===null?'—':`₡${f(v,2)}/m²${r.context.transactionType==='rent'?t('/month','/mes'):''}`
 const p=getPriceMeterCrossDimensionalPresentation({question:r.question,language}),o=r.outcomes,v=o.variation
 const variations:Array<[string,number|null,number|null,number|null,string]>=!v?[]:v.kind==='geographic'?[
  [t('Median difference','Diferencia mediana'),v.observedMedianDifferenceMinimum,v.observedMedianDifferenceMaximum,v.observedMedianDifferenceRange,'money'],
  [t('Percentage difference','Diferencia porcentual'),v.observedPercentDifferenceMinimum,v.observedPercentDifferenceMaximum,v.observedPercentDifferenceRange,'%']
 ]:[['Spearman ρ',v.spearmanRhoMinimum,v.spearmanRhoMaximum,v.spearmanRhoRange,''],...(v.kind==='size_relationship'?[
  [t('Log-log slope','Pendiente log-log'),v.logLogSlopeMinimum,v.logLogSlopeMaximum,v.logLogSlopeRange,''],
  ['R²',v.rSquaredMinimum,v.rSquaredMaximum,v.rSquaredRange,''],
  [t('Modeled +10% area change','Cambio modelado ante +10% de área'),v.modeledTenPercentAreaChangeMinimum,v.modeledTenPercentAreaChangeMaximum,v.modeledTenPercentAreaChangeRange,'%']
 ] as Array<[string,number|null,number|null,number|null,string]>:[])]
 return <div className={styles.results}>
  <p className={styles.question}>{p.question}</p>
  <p>{t('Input','Entrada')} n = {f(r.evidence.inputObservationCount)} · {t('Represented','Representadas')} n = {f(r.evidence.representedObservationCount)} · {t('Excluded','Excluidas')} n = {f(r.evidence.excludedObservationCount)}</p>
  {r.evidence.evidence.some(e=>e.kind==='construction_to_land_relationship'||e.kind==='size_relationship'&&e.modeledStatisticsAuthorization==='withheld_mathematical_coupling')&&<p>{t('Mathematical coupling: regression, R² and modeled area change are withheld for this question. The observed coordinates and authorized descriptive Spearman evidence remain available.','Acoplamiento matemático: la regresión, R² y el cambio modelado de área se retienen para esta pregunta. Se conservan las coordenadas observadas y la evidencia descriptiva autorizada de Spearman.')}</p>}
  <section><h4>{t('Relationship across groups','Relación entre grupos')}</h4><p>{t('Established in','Establecida en')} {f(o.persistence.establishedSecondaryCohortCount)} / {f(o.persistence.examinedSecondaryCohortCount)} {t('examined groups','grupos examinados')} ({f(o.persistence.persistenceRatePercent)}%). {t('Established groups represent','Los grupos establecidos representan')} n = {f(o.persistence.establishedObservationCount)}.</p><p>{t('This is the share of groups meeting the evidence requirements, not proof of a stable direction or a confidence score.','Es la proporción de grupos que cumplen los requisitos de evidencia, no una prueba de dirección estable ni una puntuación de confianza.')}</p></section>
  <CrossPlot evidence={r.evidence} language={language}/>
  <section><h4>{t('Evidence by secondary group','Evidencia por grupo secundario')}</h4><p>{t('Open a group for exact coordinates, counts and evidence prerequisites. — means not established or withheld, never zero.','Abre un grupo para ver coordenadas exactas, conteos y requisitos de evidencia. — significa no establecido o retenido, nunca cero.')}</p>
  {r.evidence.evidence.map(e=><details key={e.secondaryCohortKey} className={styles.group}><summary>{e.secondaryCohortLabel} · n = {f(e.representedObservationCount)} · {e.status==='established'?t('Established','Establecida'):t('Not established','No establecida')}</summary>
   {e.kind==='geographic'?<><p>{t('Reference: this secondary population','Referencia: esta población secundaria')} · n = {f(e.selectedMarketSampleSize)} · {t('Median','Mediana')} {price(e.selectedMarketMedianPricePerM2)} · {t('Compared geographies','Geografías comparadas')}: {f(e.comparisonGeographyCount)}</p><div className={styles.tableWrap}><table><thead><tr>{[t('Rank','Posición'),t('Geography','Geografía'),'n',t('Median','Mediana'),t('Difference from reference','Diferencia con la referencia'),'%'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{e.geographicStatistics.map(s=><tr key={s.geographyKey}><td>{s.rank}</td><td>{s.geographyLabel}</td><td>{f(s.sampleSize)}</td><td>{price(s.medianPricePerM2)}</td><td>{price(s.medianDifferenceFromSelectedMarket)}</td><td>{f(s.medianPercentAboveOrBelowSelectedMarket)}%</td></tr>)}</tbody></table></div></>:<>
    <p>Spearman ρ = {f(e.spearmanRho)} · {t('Populated groups / required','Grupos con datos / requeridos')}: {e.kind==='size_relationship'?`${e.populatedBandCount} / ${e.requiredPopulatedBandCount}`:`${e.populatedCohortCount} / ${e.requiredPopulatedCohortCount}`} {e.kind==='construction_to_land_relationship'&&`· n ≥ ${e.requiredObservationCount}`}</p>
    {e.kind==='size_relationship'&&e.modeledStatisticsAuthorization==='authorized'?<p>{t('Log-log slope','Pendiente log-log')} = {f(e.logLogSlope)} · R² = {f(e.rSquared)} · {t('Modeled +10% area change','Cambio modelado ante +10% de área')} = {f(e.modeledTenPercentAreaChangePercent)}%</p>:<p>{t('Regression, R² and modeled area change are withheld because the selected variables share a mathematical component. Spearman is descriptive, not causal.','La regresión, R² y el cambio modelado de área se retienen porque las variables seleccionadas comparten un componente matemático. Spearman es descriptivo, no causal.')}</p>}
    <div className={styles.tableWrap}><table><thead><tr><th>{e.kind==='size_relationship'?t('Median exact area (m²)','Área exacta mediana (m²)'):t('Median C/L ratio','Razón C/L mediana')}</th><th>{t('Median Price / m²','Precio / m² mediano')}</th><th>n</th></tr></thead><tbody>{e.coordinates.map((c,i)=><tr key={i}><td>{f('areaM2'in c?c.areaM2:c.constructionToLandRatio)}</td><td>{price(c.normalizedPricePerM2)}</td><td>{f(c.observationCount)}</td></tr>)}</tbody></table></div>
   </>}
  </details>)}</section>
  <section><h4>{t('Variation across established groups','Variación entre grupos establecidos')}</h4>{variations.length?<div className={styles.tableWrap}><table><thead><tr>{[t('Evidence','Evidencia'),t('Minimum','Mínimo'),t('Maximum','Máximo'),t('Range','Rango')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{variations.map(([label,a,b,c,unit])=><tr key={label}><th>{label}</th>{[a,b,c].map((x,i)=><td key={i}>{unit==='money'?price(x):x===null?'—':`${f(x)}${unit}`}</td>)}</tr>)}</tbody></table></div>:<p>{t('Not established.','No establecida.')}</p>}</section>
  <section><h4>{t('Reversals','Reversiones')} · {r.synthesis.reversalCount}</h4>{o.reversals.length===0?<p>{t('No reversal established in the available evidence.','No se estableció una reversión con la evidencia disponible.')}</p>:o.reversals.map((x,i)=><details key={i} className={styles.group}><summary>{x.firstSecondaryCohortLabel} ↔ {x.secondSecondaryCohortLabel}</summary>{x.kind==='directional'?<p>Spearman ρ: {f(x.firstSpearmanRho)} → {f(x.secondSpearmanRho)}</p>:<div className={styles.tableWrap}><table><thead><tr><th>{t('Secondary group','Grupo secundario')}</th><th>{t('Geography','Geografía')}</th><th>{t('Median','Mediana')}</th><th>n</th></tr></thead><tbody>{[[x.firstSecondaryCohortLabel,x.firstCohortFirstGeography],[x.firstSecondaryCohortLabel,x.firstCohortSecondGeography],[x.secondSecondaryCohortLabel,x.secondCohortFirstGeography],[x.secondSecondaryCohortLabel,x.secondCohortSecondGeography]].map(([label,s],j)=>{const g=s as typeof x.firstCohortFirstGeography;return <tr key={j}><td>{label as string}</td><td>{g.geographyLabel}</td><td>{price(g.medianPricePerM2)}</td><td>{g.sampleSize}</td></tr>})}</tbody></table></div>}</details>)}</section>
  <section><h4>{t('Not established','No establecido')} · {r.synthesis.nonEstablishmentCount}</h4>{o.nonEstablishment.map(x=><p key={x.secondaryCohortKey}>{x.secondaryCohortLabel}: n = {x.reason.representedObservationCount}; {x.reason.kind==='geographic_relationship_not_established'?`${t('geographies','geografías')} ${x.reason.comparisonGeographyCount} / ${x.reason.requiredComparisonGeographyCount}`:x.reason.kind==='size_relationship_not_established'?`${t('bands','bandas')} ${x.reason.populatedBandCount} / ${x.reason.requiredPopulatedBandCount}`:`${t('cohorts','cohortes')} ${x.reason.populatedCohortCount} / ${x.reason.requiredPopulatedCohortCount}; n ≥ ${x.reason.requiredObservationCount}`}</p>)}</section>
  <p>{t('These observations do not establish causation or predict an individual property’s price.','Estas observaciones no establecen causalidad ni predicen el precio de una propiedad individual.')}</p>
 </div>
}
