'use client'
import type {CohortResult} from './contract'
import {PROPERTY_AREA_RANGE_OPTIONS,CONSTRUCTION_AREA_RANGE_OPTIONS} from '@/lib/market-intelligence-area-ranges'
import {PRICE_METER_CONSTRUCTION_LAND_COHORTS} from '@/lib/price-meter-construction-land-cohorts'
import styles from '../market-summary/workspace.module.css'
export default function CohortEvidence({result,language}:{result:CohortResult;language:'en'|'es'}){
 const es=language==='es',locale=es?'es-CR':'en-US',r=result.medianDifference,identity=result.analyticalIdentity
 const unit=es?`CRC / m² de ${identity.normalizationBasis==='land'?'terreno':'construcción'}${identity.transactionType==='rent'?' / mes':''}`:`CRC / ${identity.normalizationBasis==='land'?'land':'construction'} m²${identity.transactionType==='rent'?' / month':''}`
 const number=(n:number|null,signed=false)=>n===null?(es?'No establecido':'Not established'):new Intl.NumberFormat(locale,{maximumFractionDigits:2,signDisplay:signed?'exceptZero':'auto'}).format(Object.is(n,-0)?0:n)
 const label=(t:{termName:string;termNameEn:string|null;termNameEs:string|null})=>(es?t.termNameEs:t.termNameEn)||t.termName
 const a=r.cohortAMedian,b=r.cohortBMedian,maximum=Math.max(a??0,b??0,1)*1.1
 return <>
 <section className={styles.identity}><div><p className={styles.eyebrow}>{es?'Definición del precio por m²':'Price / m² definition'}</p><p>{identity.propertyBasis==='land_only'?(es?'Terreno vacío':'Vacant Land'):(es?'Propiedad mejorada':'Improved Property')} · {identity.transactionType==='sale'?(es?'Precio de oferta de venta':'Sale asking price'):(es?'Precio de oferta mensual de alquiler':'Monthly rental asking price')} · {unit}</p><p>{es?'Fecha analítica':'Analytical date'}: {identity.analyticalDate}</p>{result.fx&&<p>BCCR USD → CRC: {result.fx.rate} · {es?'Referencia de venta':'Reference sale'} · {result.fx.effectiveDate}</p>}</div></section>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:24}}>{(['A','B'] as const).map(key=>{const c=key==='A'?result.request.cohortA:result.request.cohortB;return <section key={key} data-cohort-definition={key}><h4>{es?'Cohorte':'Cohort'} {key}</h4><p>{result.geography[key].map(t=>(es?t.term_name_es:t.term_name_en)||t.term_name).join(' › ')}</p><p>{label(c.propertyType)}</p><p>{es?'Requiere ambas':'Requires both'}: {c.characteristics.map(label).join(es?' y ':' and ')}</p>{([['propertyAreaRange',PROPERTY_AREA_RANGE_OPTIONS,es?'Área del terreno':'Property Area'],['constructionAreaRange',CONSTRUCTION_AREA_RANGE_OPTIONS,es?'Área de construcción':'Construction Area']] as const).map(([k,opts,name])=>c[k]&&<p key={k}>{name}: {opts.find(o=>o.value===c[k])?.label.replace('Under',es?'Menos de':'Under').replace('Over',es?'Más de':'Over')}</p>)}{c.constructionLandCohortKey&&<p>{es?'Restricción construcción/terreno':'Construction-to-Land constraint'}: {(()=>{const band=PRICE_METER_CONSTRUCTION_LAND_COHORTS.find(o=>o.key===c.constructionLandCohortKey)!;return band.minimumExclusive!==null?`0 < C/L < ${band.maximumExclusive}`:band.maximumExclusive===null?`C/L ≥ ${band.minimumInclusive}`:`${band.minimumInclusive} ≤ C/L < ${band.maximumExclusive}`})()}</p>}</section>})}</div>
 <section aria-label={es?'Comparación de medianas':'Median comparison'} style={{marginTop:24}}>
 <h4>{es?'Medianas del precio de oferta por m²':'Median asking Price / m²'}</h4>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:20}}>{(['A','B'] as const).map(key=><div key={key}><strong>{es?'Cohorte':'Cohort'} {key}</strong><p>{number(key==='A'?a:b)} {unit}</p><p>n = {key==='A'?result.evidence.cohortA.sampleSize:result.evidence.cohortB.sampleSize}</p></div>)}</div>
 {(a!==null||b!==null)&&<svg viewBox="0 0 420 170" role="img" aria-label={es?'Medianas en una escala compartida; valores exactos arriba.':'Medians on one shared scale; exact values above.'} style={{width:'100%',maxWidth:750,display:'block'}}><line x1="35" y1="130" x2="385" y2="130" stroke="#999"/>{(['A','B'] as const).map((key,i)=>{const value=key==='A'?a:b;if(value===null)return null;const x=35+value/maximum*350,y=45+i*45;return <g key={key}><line x1={x} x2={x} y1={y} y2="130" stroke="#aaa" strokeDasharray="3 3"/><circle cx={x} cy={y} r="6" fill={key==='A'?'#ddd':'#8ea9c0'}/><text x="8" y={y+5} fill="currentColor" fontSize="18">{key}</text></g>})}<text x="35" y="151" fill="currentColor" fontSize="16">0</text><text x="385" y="151" textAnchor="end" fill="currentColor" fontSize="16">{number(maximum)}</text></svg>}
 <p><strong>{es?'Diferencia de medianas (A − B)':'Median difference (A − B)'}</strong>: <span data-cohort-difference>{number(r.absoluteDifference,true)}{r.absoluteDifference!==null?` ${unit}`:''}</span></p>
 <p><strong>{es?'Diferencia porcentual':'Percentage difference'}</strong>: <span data-cohort-percentage>{number(r.percentageDifference,true)}{r.percentageDifference!==null?'%':''}</span></p><p>{es?'Referencia porcentual: Cohorte':'Percentage reference: Cohort'} {r.referenceCohort}</p>
 {!result.evidence.comparisonSufficient&&<p role="status">{es?'Diferencia no establecida. Se requieren al menos':'Difference not established. At least'} {result.evidence.minimumSampleSize} {es?'observaciones elegibles en cada cohorte.':'eligible observations are required in each cohort.'} A: n = {result.evidence.cohortA.sampleSize}; B: n = {result.evidence.cohortB.sampleSize}.</p>}
 </section>
 <details className={styles.optional}><summary>{es?'Metodología':'Methodology'}</summary><p>{es?'Cada cohorte requiere su geografía, tipo de propiedad, ambas características canónicas positivas y todas las restricciones seleccionadas. Las cohortes pueden superponerse y no necesariamente abarcan todo un mercado. n cuenta observaciones elegibles de precio por m², no todas las candidatas.':'Each cohort requires its geography, Property Type, both positive canonical characteristics and all selected constraints. Cohorts may overlap and need not exhaust a market. n counts eligible Price / m² observations, not all candidates.'}</p><p>{es?'El denominador requiere un área exacta positiva. Los rangos restringen la pertenencia; no fabrican mediciones. Construcción/terreno usa ambas áreas exactas y no representa cobertura del suelo.':'The denominator requires a positive exact area. Ranges constrain membership; they do not manufacture measurements. Construction-to-Land uses both exact areas and does not represent site coverage.'}</p><p>{es?'Diferencia = mediana A − mediana B. Porcentaje = diferencia ÷ mediana de referencia seleccionada × 100. La referencia cambia el denominador, no la dirección.':'Difference = median A − median B. Percentage = difference ÷ selected reference median × 100. Reference changes the denominator, not the direction.'}</p><p>{es?'La diferencia requiere al menos':'Difference requires at least'} {result.evidence.minimumSampleSize} {es?'observaciones por cohorte. Este requisito no establece significancia estadística ni causalidad. La comparación no atribuye la diferencia a ninguna característica.':'observations per cohort. This prerequisite establishes neither statistical significance nor causation. The comparison does not attribute the difference to any characteristic.'}</p></details>
 </>
}
