export const runningQuestions = {
  "en": [
    "Is this house overpriced?",
    "What else can I get for my money?",
    "How does this property compare with the other one?",
    "What's a normal price for an apartment around here?",
    "Am I about to make a $300,000 mistake?",
    "What are houses actually asking for in this district?",
    "Would my money go further somewhere nearby?",
    "Is this property expensive because it's bigger, or just expensive?",
    "What are similar properties asking per square meter?",
    "How many comparable properties are actually available?",
    "Is this asking price unusual for a property this size?",
    "How does this district compare with the next one?",
    "What can I buy here for $250,000?",
    "Are sellers asking more for newer properties?",
    "Does more land actually mean a higher asking price?",
    "What does another bedroom usually do to the asking price?",
    "Where does this property's price/m² sit in the market?",
    "Are there enough similar listings to make this comparison meaningful?",
    "What are sellers asking for properties like this one?",
    "Which properties should I compare this one with?"
  ],
  "es": [
    "¿Está sobrevalorada esta casa?",
    "¿Qué más puedo conseguir con mi presupuesto?",
    "¿Cómo se compara esta propiedad con la otra?",
    "¿Cuál es un precio habitual para un apartamento por aquí?",
    "¿Estoy a punto de cometer un error de $300,000?",
    "¿Cuánto se está pidiendo realmente por las casas en este distrito?",
    "¿Me alcanzaría para más en algún lugar cercano?",
    "¿Esta propiedad es cara porque es más grande, o simplemente es cara?",
    "¿Cuánto se pide por metro cuadrado por propiedades similares?",
    "¿Cuántas propiedades comparables están realmente disponibles?",
    "¿Es inusual este precio de oferta para una propiedad de este tamaño?",
    "¿Cómo se compara este distrito con el de al lado?",
    "¿Qué puedo comprar aquí por $250,000?",
    "¿Piden más los vendedores por propiedades más nuevas?",
    "¿Tener más terreno realmente implica un precio de oferta más alto?",
    "¿Cómo suele variar el precio de oferta con un dormitorio adicional?",
    "¿Dónde se sitúa el precio por m² de esta propiedad en el mercado?",
    "¿Hay suficientes anuncios similares para que esta comparación sea significativa?",
    "¿Cuánto piden los vendedores por propiedades como esta?",
    "¿Con qué propiedades debería comparar esta?"
  ]
} as const
