export const runningQuestions = {
  "en": [
    "How does the price of this property compare with the price of similar properties?",
    "What other properties or homes can I get for my money?",
    "What's a normal price for an apartment in this area?",
    "Is the house in this listing overpriced?",
    "Am I underpricing my house?",
    "What prices are houses actually selling for in this district?",
    "Would my money go further somewhere nearby?",
    "Is this property expensive because it's bigger, or just expensive?",
    "What are similar properties in this area selling for per square meter?",
    "How many comparable properties are available in this area?",
    "Is this asking price unusual for a property this size in this area?",
    "How do the prices in this district compare with the prices in other districts?",
    "Am I about to make a $300,000 mistake buying something overpriced because I don't know the market?",
    "What properties can I buy in this area for $250,000?",
    "Are sellers asking higher prices for newer properties?",
    "Does more land actually mean a higher asking price?",
    "What does the number of bedrooms do to the asking price of a house in this area?",
    "Where does this property's price/m² sit in the market?",
    "What are sellers asking for properties like the one in the listing I'm looking at?",
    "Which properties should I compare this one with?"
  ],
  "es": [
    "¿Cómo se compara el precio de esta propiedad con el precio de propiedades similares?",
    "¿Qué otras propiedades o casas puedo conseguir por mi dinero?",
    "¿Cuál es un precio normal para un apartamento en esta zona?",
    "¿Está sobrevalorada la casa de este anuncio?",
    "¿Estoy poniendo mi casa a un precio demasiado bajo?",
    "¿A qué precios se están vendiendo realmente las casas en este distrito?",
    "¿Me rendiría más el dinero en algún lugar cercano?",
    "¿Esta propiedad es cara porque es más grande o simplemente es cara?",
    "¿A cuánto se están vendiendo por metro cuadrado propiedades similares en esta zona?",
    "¿Cuántas propiedades comparables están disponibles en esta zona?",
    "¿Es inusual este precio de venta para una propiedad de este tamaño en esta zona?",
    "¿Cómo se comparan los precios de este distrito con los precios de otros distritos?",
    "¿Estoy a punto de cometer un error de $300,000 comprando algo sobrevalorado porque no conozco el mercado?",
    "¿Qué propiedades puedo comprar en esta zona por $250,000?",
    "¿Están los vendedores pidiendo precios más altos por propiedades más nuevas?",
    "¿Tener más terreno realmente significa un precio de venta más alto?",
    "¿Qué efecto tiene el número de habitaciones sobre el precio de venta de una casa en esta zona?",
    "¿Dónde se sitúa el precio/m² de esta propiedad dentro del mercado?",
    "¿Qué precios están pidiendo los vendedores por propiedades como la del anuncio que estoy viendo?",
    "¿Con cuáles propiedades debería comparar esta?"
  ]
} as const
