const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),assert=require('assert/strict'),esbuild=require('esbuild'),puppeteer=require('puppeteer');
const root=process.cwd(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'twuanis-weighted-')),out=path.join(root,'outputs/engine17');fs.mkdirSync(out,{recursive:true});let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++};
const fixture=JSON.parse(fs.readFileSync(path.join(out,'fixture.json'),'utf8')),states=JSON.parse(fs.readFileSync(path.join(out,'states.json'),'utf8'));
const entry=`import React,{useState,useEffect} from 'react';import{createRoot}from'react-dom/client';import EN from '${root}/app/en/market-intelligence/MarketIntelligenceTabs';import ES from '${root}/app/es/inteligencia-de-mercado/PestanasInteligenciaMercado';import Panel from '${root}/app/components/PriceMeterApplyPanel';import ThemeProvider from '${root}/app/components/theme/ThemeProvider';import TopBar from '${root}/app/components/TopBar';
window.fixtureAuthorization="offline-only";window.calls=[];window.saved=[];window.prompt=()=> 'Saved fixture';window.pending=[];window.finish=(value)=>window.pending.shift().resolve(value);window.fail=()=>window.pending.shift().reject(Error('fixture failure'));
const options={utility:Array.from({length:8},(_,i)=>({id:String(100+i),slug:'utility-'+i,term_name_en:'Utility '+(i+1),term_name_es:'Servicio '+(i+1)})),property_area:[{slug:'500-1000m2',term_name_en:'500–<1,000 m²',term_name_es:'500–<1.000 m²'}],province:[{id:1,official_code:'1',term_name_en:'San José',term_name_es:'San José'}],canton:[{id:2,parent_id:1,official_code:'102',term_name_en:'Escazú',term_name_es:'Escazú'}],district:[],property_type:[{id:3,slug:'house',term_name_en:'Houses',term_name_es:'Casas'}],bedrooms:[{slug:'3',term_name_en:'3 bedrooms',term_name_es:'3 habitaciones'}]};
function Fixture(){const[theme,setTheme]=useState('dark');const[tab,setTab]=useState(new URLSearchParams(location.search).get('tab')||'explorer');const[,rerender]=useState(0);const language=location.pathname.startsWith('/es')?'es':'en';useEffect(()=>{const listener=()=>{setTab(new URLSearchParams(location.search).get('tab')||'explorer');rerender(v=>v+1)};window.addEventListener('fixture-nav',listener);return()=>window.removeEventListener('fixture-nav',listener)},[]);const Tabs=language==='es'?ES:EN;return <main style={{padding:'clamp(1rem,3vw,2rem)',background:'var(--background)',color:'var(--foreground)',minHeight:'100vh'}}><TopBar theme={theme} onThemeToggle={()=>setTheme(t=>t==='dark'?'light':'dark')}/><header style={{textAlign:'center',marginBottom:32}}><h1 style={{fontSize:'clamp(1.6rem,4vw,3rem)'}}>{language==='es'?'Inteligencia de Mercado':'Market Intelligence'}</h1></header>{location.pathname.includes('standalone')?<Panel options={options} filters={{...Object.fromEntries(new URLSearchParams(location.search)),analysis_question:'construction-land'}} language={language} source="standalone"/>:<Tabs activeTab={tab} options={options} filters={Object.fromEntries(new URLSearchParams(location.search))} explorerResult={null} priceMeterAnalysis={null} pricingStrategy={null} marketScarcity={null} buyerDemand={null} marketMatches={null} valuation={null} comparison={null}/>}</main>};createRoot(document.getElementById('root')).render(<ThemeProvider><Fixture/></ThemeProvider>);`;
const stubs={
 'weighted-price-action':`export async function executeWeightedPrice(input){window.calls.push(['weighted',input]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))};export async function loadWeightedPriceOptions(){return {state:'ready',options:[{id:'1',type:'province',en:'San José',es:'San José',code:'1'},{id:'3',type:'canton',en:'Central',es:'Central',code:'101'},{id:'2',type:'property_type',en:'House',es:'Casa',code:null}]}}`,
 'asking-area-ratio-action':`export async function executeAskingAreaRatio(input){window.calls.push(['ratio',input]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))};export async function loadAreaRatioOptions(){return {state:'ready',options:[{id:'1',type:'province',en:'San José',es:'San José',code:'1'},{id:'2',type:'property_type',en:'House',es:'Casa',code:null}]}}`,
 'comparables-hub-action':`export async function executeComparablesHub(input){window.calls.push(['comparables',input]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'position-hub-action':`export async function executePositionHub(input){window.calls.push(['position',input]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`, 
 'discovery-hub-action':`export async function restoreDiscoveryDraft(s){return JSON.parse(s)};export async function executeDiscoveryHub(input){window.calls.push(['discovery',input]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'comparative-discovery-action':`export async function loadPhase14Options(){return {}};export async function analyzePhase14Market(input){window.calls.push(['standalone',input]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'current-user-permissions-action':`export async function loadCurrentUserPermissionContext(){return{authenticated:true,premium:true,enterprise:true,roles:["buyer"]}}`,
 'price-meter-cross-dimensional-action':`export async function readCrossDimensionalQuestions(language){return []};export async function executeCrossDimensionalHub(...args){window.calls.push(['cross',...args]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`, 
 'price-meter-cohort-action':`export async function executePriceMeterCohortComparison(...args){window.calls.push(['cohort',...args]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'price-meter-apply-action':`export async function executePriceMeterApply(...args){window.calls.push(args);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'asking-price-action':`export async function analyzeAskingPrice(q){window.calls.push(['asking-price',q]);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'market-inventory-action':`export async function executeMarketQuestion(...args){window.calls.push(args);return new Promise((resolve,reject)=>window.pending.push({resolve,reject}))}`,
 'legacy-hub-action':`export async function executeLegacyHubQuestion(...args){window.calls.push(args);return {}}`,
 'saved-analyses':`export async function saveAnalysis(input){window.saved.push(input);return{id:'fixture',name:input.name}};export async function updateSavedAnalysis(){};export async function getSavedAnalysesByEngine(){return []}`,
 'market-comparisons':`export async function saveMarketComparison(){};export function createMarketComparisonName(){return 'fixture'}`,
 'account-storage':`export async function recordRecentActivity(){}`,
 'activity/markets':`export async function recordMarketViewed(){}`,
};
(async()=>{await esbuild.build({stdin:{contents:entry,loader:'tsx',resolveDir:root},bundle:true,jsx:'automatic',outfile:path.join(dir,'app.js'),plugins:[{name:'offline-boundaries',setup(b){b.onResolve({filter:/^(next\/|@\/lib\/|@\/app\/|.*ComparativeDiscoveryAccess|.*PriceMeterResults|.*ResultadosPrecioMetro)/},args=>{if(args.path==='next/link'||args.path==='next/navigation')return{path:args.path,namespace:'fixture'};const key=Object.keys(stubs).find(k=>args.path.endsWith('/'+k));if(/(PriceMeterResults|ResultadosPrecioMetro)$/.test(args.path))return{path:'inactive',namespace:'fixture'};if(key)return{path:key,namespace:'fixture'};if(/(PricingStrategyResults|BuyerDemandResults|ValuationResults|MarketMatchingResults|MarketScarcityResults|MarketComparisonResults)$/.test(args.path))return{path:'inactive',namespace:'fixture'};});b.onLoad({filter:/.*/,namespace:'fixture'},args=>({resolveDir:root,loader:'tsx',contents:args.path==='next/link'?`import React from 'react';export default function Link({href,prefetch,children,...p}){return <a href={href} {...p} onClick={e=>{e.preventDefault();history.pushState({},'',href);window.dispatchEvent(new Event('fixture-nav'))}}>{children}</a>}`:args.path==='next/navigation'?`export function usePathname(){return location.pathname};export function useSearchParams(){return new URLSearchParams(location.search)};export function useRouter(){return{push(url){history.pushState({},'',url);window.dispatchEvent(new Event('fixture-nav'))}}}`:args.path==='inactive'?`export default function Inactive(){return null}`:stubs[args.path]}))}}]});
const fontPath=path.join(root,'.next/dev/static/media/cc014fcb166cf364-s.p.2cu9iw-l3ih8o.woff2');const fontCss=fs.existsSync(fontPath)?`@font-face{font-family:FixtureCinzel;src:url(data:font/woff2;base64,${fs.readFileSync(fontPath).toString('base64')}) format('woff2');font-weight:100 900}body{--font-cinzel:FixtureCinzel}`:'';
const globals=fs.readFileSync(path.join(root,'app/globals.css'),'utf8').replace('@import "tailwindcss";','').replace(/@theme inline\s*\{[^}]*\}/,'');
fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html><meta name="viewport" content="width=device-width, initial-scale=1"><style>${globals}\n${fontCss}\n*{box-sizing:border-box}body{margin:0}button,select{font:inherit}a{background:transparent}h1,h2,h3,p{overflow-wrap:break-word}</style><link rel="stylesheet" href="/app.css"><div id="root"></div><script src="/app.js"></script></html>`);
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0];if(name==='/fixture.svg'){res.setHeader('Content-Type','image/svg+xml');res.end('<svg xmlns="http://www.w3.org/2000/svg" width="112" height="84" viewBox="0 0 112 84"><rect width="112" height="84" fill="#333"/><path d="M20 42L56 16L92 42V72H20Z" fill="#655d48" stroke="#d4af37" stroke-width="2"/><path d="M47 72V47H66V72" fill="#292929"/></svg>');return}const file=name==='/app.js'?'app.js':name==='/app.css'?'app.css':'index.html';res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(dir,file)))});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{browser=await puppeteer.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith(`http://127.0.0.1:${server.address().port}`)?r.continue():r.abort());
const pause=()=>new Promise(r=>setTimeout(r,80));const click=async(t)=>{await page.evaluate(t=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===t||b.getAttribute('aria-label')===t);if(!b)throw Error(t);b.click()},t);await pause()};const shot=async(name,fullPage=true)=>{await page.evaluate(()=>scrollTo(0,0));await pause();return page.screenshot({path:path.join(out,name+'.png'),fullPage})};


const count=()=>page.evaluate(()=>window.calls.length);
const choose=async(index,value)=>{await page.evaluate(({index,value})=>{const s=document.querySelectorAll('form select')[index];s.value=value;s.dispatchEvent(new Event('change',{bubbles:true}))},{index,value});await pause()};
const enter=async(index,value)=>{const inputs=await page.$$('form input');await inputs[index].click({clickCount:3});await inputs[index].press('Backspace');await inputs[index].type(value);await pause()};

for(const language of['en','es'])for(const width of[1440,375]){
 const es=language==='es',prefix=language+'-'+width,apply=es?'Analizar':'Analyze',modify=es?'Modificar':'Modify',load=es?'Cargar opciones del mercado':'Load market options';
 const url=`http://127.0.0.1:${server.address().port}/${es?'es/inteligencia-de-mercado':'en/market-intelligence'}?tab=price-meter&analysis_question=weighted-price`;
 await page.setViewport({width,height:1000});await page.goto(url+'&'+new URLSearchParams({weighted_request:JSON.stringify(fixture.question)}));await page.waitForSelector('form input');await pause();ok(await count()===0,'restore zero');await click(load);const lens=await page.$('form select');await lens.focus();await page.keyboard.press('ArrowUp');await pause();ok(await count()===0,'keyboard lens zero');await page.keyboard.press('ArrowDown');await pause();await shot(prefix+'-inputs');
 await click(apply);await page.evaluate(()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));ok(await count()===1,'double submit one');ok(await page.evaluate(()=>window.calls[0][0]==='weighted'&&window.calls[0][1].cohort.propertyType==='2'),'committed contract');
 await page.evaluate(r=>window.finish(r),fixture);await page.waitForFunction(()=>document.querySelector('form').hidden);await pause();ok(await page.evaluate(()=>document.activeElement?.tagName==='H3'),'result focus');ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no overflow');await shot(prefix+'-populated');
 await click(es?'Cambiar a modo claro':'Switch to light mode');await click(es?'Cambiar a modo oscuro':'Switch to dark mode');ok(await count()===1,'theme zero');await page.setViewport({width:width+1,height:1000});await page.setViewport({width,height:1000});ok(await count()===1,'viewport zero');
 if(width===1440){await click(es?'Contraer motores':'Collapse engines');await click(es?'Expandir motores':'Expand engines');ok(await count()===1,'sidebar zero')}
 await page.evaluate(()=>document.querySelectorAll('details').forEach(d=>d.open=true));ok(await count()===1,'disclosures zero');await shot(prefix+'-evidence');
 await page.evaluate(label=>[...document.querySelectorAll('button')].find(b=>b.textContent===label).focus(),modify);await page.keyboard.press('Enter');await pause();await enter(0,'14');ok(await count()===1,'keyboard Modify and edits zero');
 await click(apply);await page.evaluate(()=>window.fail());await pause();ok(await page.evaluate(()=>!!document.querySelector('[role=alert]')&&!!document.querySelector('dl')),'technical failure retains evidence');await shot(prefix+'-failed-rerun');
 await click(es?'Guardar análisis':'Save Analysis');await pause();ok(await count()===2,'save zero');const saved=await page.evaluate(()=>window.saved[0]);ok(JSON.parse(saved.filters.weighted_request).subject.propertyArea==='13','save committed not draft');
 await page.goto(url+'&'+new URLSearchParams({weighted_request:saved.filters.weighted_request}));await page.waitForSelector('form input');ok(await count()===0,'saved restore zero');ok(await page.$eval('form input',e=>e.value)==='13','restore subject');
 await click(load);
 for(const [i,state]of states.slice(1).entries()){
  if(i)await click(modify);
  if(state.question.subject.kind==='listing'){await choose(0,'listing');await enter(0,state.question.subject.listingId)}else{await choose(0,'hypothetical');await enter(0,state.question.subject.propertyArea);await enter(1,state.question.subject.constructionArea);await enter(2,'');await choose(1,'1');await choose(2,'3')}
  await click(apply);await page.evaluate(r=>window.finish(r),state);await pause();ok(await page.evaluate(()=>document.querySelector('form').hidden),'state committed');
  if(state.evidence.state==='distribution_only')ok(await page.evaluate(()=>!document.body.textContent.includes('Percentile position (midrank)')&&!document.body.textContent.includes('Posición percentil (rango medio)')),'distribution only no subject position');
  await shot(prefix+'-'+state.evidence.state+'-'+i);
  ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'state no overflow');
 }
 await click(modify);await click(apply);await page.evaluate(()=>window.finish({access:'entitlement_required'}));await pause();ok(await page.evaluate(()=>!document.querySelector('dl')&&!!document.querySelector('[role=alert]')),'access failure clears result');
 await click(apply);const dropdown=es?'select[aria-label=Análisis]':'select[aria-label=Analysis]';const before=await count();await page.select(dropdown,'explorer');await pause();await page.evaluate(r=>window.finish(r),fixture);await pause();ok(await count()===before,'navigation no analysis');ok(await page.evaluate(()=>!document.body.textContent.includes('Weighted PPM2 =')),'late response discarded');await page.select(dropdown,'weighted-price');await pause();ok(await count()===before,'return navigation zero');
}
ok(errors.length===0,JSON.stringify(errors));console.log(JSON.stringify({status:'PASS',checks,screenshots:out,externalRequests:'blocked',liveAnalyticalIO:false}));
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
