const fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('typescript'),assert=require('assert/strict');let checks=0,groups={};const ok=(v,g)=>{assert.ok(v,g);checks++;groups[g]=(groups[g]||0)+1},cache=new Map();function load(file){if(cache.has(file))return cache.get(file).exports;const m={exports:{}};cache.set(file,m);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,require:n=>{if(n==='server-only')return{};if(!n.startsWith('.'))throw Error('external I/O forbidden');return load(path.join(path.dirname(file),n)+'.ts')}});return m.exports}
const {analyzeWeightedPrice,weightedObservation}=load('lib/weighted-price-math.ts'),{analyzeAreaRatio}=load('lib/asking-area-ratio-math.ts'),{calculatePropertyPositionCounts,calculatePropertyPositionDifference}=load('lib/price-meter-property-position-math.ts');
const rows=(n=25,a=2,b=10)=>Array.from({length:n},(_,i)=>{const L=10+i%5*3,C=5+Math.floor(i/5)%5*2;return{id:String(i).padStart(9,'0'),L,C,P:1000+a*L+b*C+.2*((i*17)%11-5)}});
const data=rows(),subject={P:1100,L:13,C:7};let result=analyzeWeightedPrice(data,subject),fit=analyzeAreaRatio(data);ok(result.state==='subject_position','establishment');ok(JSON.stringify(result.weighting)===JSON.stringify(fit),'Engine16 parity');const values=data.map(o=>o.P/(o.L+fit.ratio*o.C)).sort((a,b)=>a-b);for(const[k,p]of[['p25',.25],['median',.5],['p75',.75]]){const j=(values.length-1)*p,i=Math.floor(j),expected=values[i]*(1-j+i)+(values[Math.ceil(j)])*(j-i);ok(Math.abs(result.distribution[k]-expected)<1e-12,'quartiles')}
ok(result.subject.weightedPrice===subject.P/(subject.L+fit.ratio*subject.C),'formula');ok(result.subject.difference===result.subject.weightedPrice-result.distribution.median,'differences');ok(result.subject.percentDifference===result.subject.difference/result.distribution.median*100,'differences');
for(const P of[.5,1,100,1000,1e6])for(const L of[1,10,100])for(const C of[1,5,100])for(const r of[.1,1,5])ok(weightedObservation(P,L,C,r)===P/(L+r*C),'formula');
for(const args of[[100,0,1,1],[100,1,0,1],[100,1,1,0],[100,1,1,-1],[Infinity,1,1,1],[100,1e308,1e308,2],[Number.MIN_VALUE,1e308,1,1],[NaN,1,1,1]]){assert.throws(()=>weightedObservation(...args));ok(true,'invalid denominator/numerator')}
for(const [v,expected]of[[1,0],[2,25],[3,50],[4,75],[5,100]])ok(calculatePropertyPositionCounts(v,[2,2,4,4],4).percentilePosition===expected,'ties/positions');ok(calculatePropertyPositionCounts(2,[2,2,2],3).percentilePosition===50,'ties/positions');ok(calculatePropertyPositionDifference(50,100).percentDifference===-50,'differences');
for(const scale of[.01,10,500]){const scaled=analyzeWeightedPrice(data.map(o=>({...o,P:o.P*scale})),{...subject,P:subject.P*scale});ok(scaled.state==='subject_position','currency scaling');ok(Math.abs(scaled.weighting.ratio-fit.ratio)<1e-10,'currency scaling');ok(Math.abs(scaled.subject.weightedPrice-result.subject.weightedPrice*scale)<1e-7,'currency scaling');ok(Math.abs(scaled.subject.percentDifference-result.subject.percentDifference)<1e-8,'currency scaling');ok(scaled.subject.percentilePosition===result.subject.percentilePosition,'currency scaling')}
for(const [a,b]of[[2,-10],[-2,10],[-2,-10]]){const r=analyzeWeightedPrice(rows(25,a,b),subject);ok(r.state==='weighting_not_applicable','sign gates');ok(!('distribution'in r)&&!('subject'in r),'withholding shape')}
for(const n of[0,1,2,3]){const r=analyzeWeightedPrice(rows(n),subject);ok(r.state==='weighting_not_established','small n');ok(!('distribution'in r),'withholding shape')}
const unpriced=analyzeWeightedPrice(data,{...subject,P:null});ok(unpriced.state==='distribution_only'&&!('subject'in unpriced),'no-price shape');ok(JSON.stringify(unpriced.distribution)===JSON.stringify(result.distribution),'no-price shape');
const reordered=analyzeWeightedPrice([...data].reverse(),subject);ok(JSON.stringify(reordered)===JSON.stringify(result),'order invariance');const frozen=data.map(Object.freeze);Object.freeze(frozen);analyzeWeightedPrice(frozen,Object.freeze(subject));ok(true,'input immutability');
const timings=[];for(const n of[1000,10000,100000]){const input=rows(n);global.gc?.();const before=process.memoryUsage().heapUsed,t=performance.now();const r=analyzeWeightedPrice(input,{...subject,P:null});ok(r.state==='distribution_only','scale');timings.push({n,ms:performance.now()-t,heapDelta:process.memoryUsage().heapUsed-before,aggregateBytes:Buffer.byteLength(JSON.stringify(r))})}
const report={status:'PASS',checks,groups,timings,liveIO:false,note:'One synthetic run per size; heap delta is GC-sensitive, not peak memory. Working evidence O(n); additional weighted sort O(n log n). No database/browser-egress savings claimed.'};fs.writeFileSync('outputs/engine17/math-resources.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
