const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require('typescript');let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++},near=(a,b,t=1e-8)=>ok(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const moduleObject={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/asking-area-ratio-math.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:moduleObject,exports:moduleObject.exports,require:n=>{if(n==='server-only')return{};throw Error('Unexpected dependency '+n)}});const m=moduleObject.exports;
// Independent pivoted elimination on normal equations is a reference ONLY on small,
// moderate-magnitude fixtures, never the production solver.
function ref(data){let A=Array.from({length:3},()=>[0,0,0,0]);for(const o of data){const x=[1,o.L,o.C];for(let j=0;j<3;j++){for(let k=0;k<3;k++)A[j][k]+=x[j]*x[k];A[j][3]+=x[j]*o.P}}for(let j=0;j<3;j++){let p=j;for(let i=j+1;i<3;i++)if(Math.abs(A[i][j])>Math.abs(A[p][j]))p=i;[A[j],A[p]]=[A[p],A[j]];assert.ok(Math.abs(A[j][j])>1e-9);const d=A[j][j];A[j]=A[j].map(x=>x/d);for(let i=0;i<3;i++)if(i!==j){const f=A[i][j];A[i]=A[i].map((v,k)=>v-f*A[j][k])}}return A.map(r=>r[3])}
for(const[df,v]of[[1,12.706204736432095],[2,4.302652729696142],[3,3.182446305284263],[10,2.2281388519649385],[30,2.042272456301238],[100,1.9839715184496334]])near(m.tCritical(df),v,1e-10);
function fixture(n,signL=1,signC=1,noise=.2){return Array.from({length:n},(_,i)=>{const L=10+i%5*3,C=5+Math.floor(i/5)%5*2;return{id:String(i).padStart(8,'0'),L,C,P:1000+signL*2*L+signC*10*C+noise*((i*17)%11-5)}})}
let pairs=0,maxRatio=0,maxBound=0;
for(const n of[12,20,25,40])for(const signs of[[1,1],[1,-1],[-1,1],[-1,-1]]){const data=fixture(n,...signs),f=m.fitAreaRatio(data),d=m.diagnoseAreaRatio(f),base=ref(data);f.coefficients.forEach((v,i)=>near(v,base[i]));for(let i=0;i<n;i++){const one=ref(data.filter((_,k)=>k!==i));one.forEach((v,j)=>near(v,d.deleted[i][j]));if(d.bound!==null){ok(Math.abs(one[1]-base[1])<=d.BL+1e-8,'single land bound');ok(Math.abs(one[2]-base[2])<=d.BC+1e-8,'single construction bound');ok(Math.abs(one[2]/one[1]-base[2]/base[1])<=d.bound+1e-8,'single ratio bound')}for(let j=i+1;j<n;j++){const two=ref(data.filter((_,k)=>k!==i&&k!==j));if(d.bound!==null){ok(Math.abs(two[1]-base[1])<=d.BL+1e-8,'land bound');ok(Math.abs(two[2]-base[2])<=d.BC+1e-8,'construction bound');const change=Math.abs(two[2]/two[1]-base[2]/base[1]);ok(change<=d.bound+1e-8,'pair ratio bound');maxRatio=Math.max(maxRatio,change);maxBound=Math.max(maxBound,d.bound)}pairs++}}
 const result=m.analyzeAreaRatio(data);if(n===12)ok(result.state==='not_established','conservative small cohort withheld');else{ok(result.state==='established','signed established '+signs);ok(Math.sign(result.ratio)===Math.sign(signs[0]*signs[1]),'signed ratio');}
}
const exact=fixture(25,1,1,0),f=m.fitAreaRatio(exact);f.coefficients.forEach((v,i)=>near(v,[1000,2,10][i]));ok(m.analyzeAreaRatio(exact).state==='not_established','exact fit uncertainty withheld');
for(const data of[fixture(3),fixture(20).map(o=>({...o,L:3})),fixture(20).map(o=>({...o,C:2*o.L}))])ok(m.analyzeAreaRatio(data).state==='not_established','prerequisite');
const noisy=fixture(100);for(const scale of[1e-8,1e8]){const a=m.fitAreaRatio(noisy),b=m.fitAreaRatio(noisy.map(o=>({...o,P:o.P*scale})));near(a.coefficients[2]/a.coefficients[1],b.coefficients[2]/b.coefficients[1])}
near(m.fitAreaRatio([...noisy].reverse()).coefficients[2],m.fitAreaRatio(noisy).coefficients[2]);
for(const [args,kind]of[[[2,10,.0001,.0001,0,2],'bounded'],[[0,1,1,1,0,2],'all_real'],[[.1,10,1,.01,0,2],'disconnected'],[[1,2,.25,1,0,2],'half_line'],[[0,1,0,0,0,2],'empty']])ok(m.fieller(...args).kind===kind,'Fieller '+kind);
// Independent HC3 sandwich in original units, using separately inverted raw normal equations.
function inverse(a){const m=a.map((r,i)=>[...r,...[0,1,2].map(j=>+(i===j))]);for(let k=0;k<3;k++){let p=k;for(let i=k+1;i<3;i++)if(Math.abs(m[i][k])>Math.abs(m[p][k]))p=i;[m[k],m[p]]=[m[p],m[k]];const v=m[k][k];m[k]=m[k].map(x=>x/v);for(let i=0;i<3;i++)if(i!==k){const v=m[i][k];m[i]=m[i].map((x,j)=>x-v*m[k][j])}}return m.map(r=>r.slice(3))}
for(const hetero of[false,true]){const data=fixture(100,1,1,2).map((o,i)=>({...o,P:o.P+(hetero?(i%7-3)*o.L:0)})),b=ref(data),A=Array.from({length:3},()=>[0,0,0]);for(const o of data){const x=[1,o.L,o.C];for(let j=0;j<3;j++)for(let k=0;k<3;k++)A[j][k]+=x[j]*x[k]}const G=inverse(A),cov=Array.from({length:3},()=>[0,0,0]);for(const o of data){const x=[1,o.L,o.C],g=G.map(r=>r.reduce((s,v,j)=>s+v*x[j],0)),h=x.reduce((s,v,j)=>s+v*g[j],0),e=o.P-x.reduce((s,v,j)=>s+v*b[j],0);for(let j=0;j<3;j++)for(let k=0;k<3;k++)cov[j][k]+=g[j]*g[k]*(e/(1-h))**2}const result=m.diagnoseAreaRatio(m.fitAreaRatio(data));for(let j=0;j<3;j++)for(let k=0;k<3;k++)near(result.covariance[j][k],cov[j][k],1e-9)}
const nearCollinear=fixture(100).map((o,i)=>({...o,C:2*o.L+(i%3)*1e-10}));ok(m.analyzeAreaRatio(nearCollinear).state==='not_established','near collinearity closed');
for(const data of[fixture(25).map((o,i)=>({...o,P:1000+10*o.C+(i%11-5)*3})),fixture(25,1,1,150)]){const r=m.analyzeAreaRatio(data);ok(r.state==='not_established','weak/unstable withheld');ok(!('ratio'in r)&&!('coefficients'in r),'withheld no candidate estimate')}
const extreme=fixture(25).map((o,i)=>i===24?{...o,L:1e9,C:3e9}:o);ok(m.analyzeAreaRatio(extreme).state==='not_established','high leverage closed');
// Count real function entries in an instrumented, disposable copy, never production telemetry.
const counters={};const measured={exports:{}};let instrumented=fs.readFileSync('lib/asking-area-ratio-math.ts','utf8');for(const name of['fitAreaRatio','diagnoseAreaRatio','fieller','certifyInfluence'])instrumented=instrumented.replace(new RegExp('(export function '+name+'[^\\n]*\\{)'), '$1 trace("'+name+'");');vm.runInNewContext(ts.transpileModule(instrumented,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:measured,exports:measured.exports,trace:n=>counters[n]=(counters[n]||0)+1,require:n=>{if(n==='server-only')return{};throw Error(n)}});
measured.exports.analyzeAreaRatio(fixture(100));for(const name of['fitAreaRatio','diagnoseAreaRatio','fieller','certifyInfluence'])ok(counters[name]===1,'one '+name);for(const k in counters)delete counters[k];measured.exports.analyzeAreaRatio(exact);ok(!counters.fieller&&!counters.certifyInfluence,'withheld early zero downstream');
const centerOnlyNoise=[...fixture(25,1,1,0),{id:'center-a',L:16,C:9,P:1132},{id:'center-b',L:16,C:9,P:1112}];ok(m.analyzeAreaRatio(centerOnlyNoise).state==='not_established','degenerate ratio uncertainty withheld even with nonzero residual SSE');
const big=fixture(10000);const start=performance.now();m.analyzeAreaRatio(big);console.log(JSON.stringify({checks,pairs,maxActualRatioChange:maxRatio,maxCertificateBound:maxBound,largeN:big.length,largeMilliseconds:performance.now()-start}));
