// Offline presentation/application verification. External I/O is replaced; no application server.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),ts=require(root+'/node_modules/typescript'),React=require(root+'/node_modules/react'),dom=require(root+'/node_modules/react-dom/server');
global.fetch=()=>{throw Error('Live I/O prohibited')};
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++},copy=v=>JSON.parse(JSON.stringify(v));
function loader(overrides={}) { const cache=new Map(); return function load(file) {
 if(Object.hasOwn(overrides,file))return overrides[file];if(cache.has(file))return cache.get(file).exports;
 const m={exports:{}};cache.set(file,m);
 const js=ts.transpileModule(fs.readFileSync(root+'/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 const req=name=>{if(name==='server-only')return {};if(name==='react')return overrides.react??React;if(name==='react/jsx-runtime')return require(root+'/node_modules/react/jsx-runtime');if(name.endsWith('.css'))return new Proxy({},{get:(_,k)=>k==='__esModule'?false:k==='default'?undefined:String(k)});
 const base=name.startsWith('@/')?name.slice(2):name.startsWith('.')?path.posix.normalize(path.posix.join(path.posix.dirname(file),name)):null;
 if(!base)throw Error('Forbidden external module '+name);const f=[base,base+'.ts',base+'.tsx'].find(f=>fs.existsSync(root+'/'+f));if(!f)throw Error(name);return load(f)};
 new Function('module','exports','require',js)(m,m.exports,req);return m.exports;
 }}
const presentation=loader()('lib/comparative-discovery-presentation.ts');
const uuid=i=>'00000000-0000-0000-0000-'+String(i).padStart(12,'0');
function result(n=3,tx='sale',basis='land',geo='province') {return {state:'complete',contractVersion:1,question:{transaction:tx,geography:{level:geo,officialCode:geo==='province'?'1':geo==='canton'?'101':'10101',termId:geo==='province'?'1':geo==='canton'?'2':'3'},propertyType:{termId:'4'},filters:{semantics:{},facts:{}}},transaction:tx,normalization:basis,unit:tx==='sale'?'CRC/m²':'CRC/m²/month',n,resultCount:n,distribution:{state:n?'established':'empty',...Object.fromEntries(['minimum','p10','p25','median','average','p75','p90','maximum','iqr'].map((k,i)=>[k,n?i+1:null]))},results:Array.from({length:n},(_,i)=>({listingId:uuid(i+1),pricePerM2:i+1,percentilePosition:i/Math.max(n,1)*100,belowCount:i,equalCount:1,aboveCount:n-i-1,percentileMethod:'midrank',differenceFromMedian:i-10,percentDifferenceFromMedian:i-10,percentageReference:'selected_population_median',interval:presentation.positions[i%7],strictTail:i%3===0?null:{thresholdPercentile:i%2?10:90,thresholdPricePerM2:15,differenceFromThreshold:i-15,percentDifferenceFromThreshold:i-15,percentageReference:i%2?'selected_population_p10':'selected_population_p90'}})),resultOrder:{primary:'price_per_square_meter_ascending',exactTieOrder:'canonical_listing_id_ascending',exactTieOrderMeaning:'transport_only'},snapshotGuaranteed:false}}
function listings(r){return r.results.map((a,i)=>({listingId:a.listingId,title:'Home '+i,thumbnail:'/image-'+i+'.jpg',price:i*100,currency:i%2?'USD':'CRC',propertyArea:i+30,constructionArea:i+20,bedrooms:i%5,bathrooms:i%3+.5,parking:i%4,yearBuilt:2000+i,province:'Provincia',canton:'Cantón',district:i%2?'Distrito':null}))}
const props=r=>({result:r,listings:listings(r),labels:{en:['Committed market'],es:['Mercado comprometido']},language:'en'});
function hookHarness() {let states=[],cursor=0,effects=[];return {react:{...React,useId(){return "offline-form"},useState(initial){const i=cursor++;if(!(i in states))states[i]=typeof initial==='function'?initial():initial;return [states[i],v=>{states[i]=typeof v==='function'?v(states[i]):v}]},useRef(initial){const i=cursor++;if(!(i in states))states[i]={current:initial};return states[i]},useMemo(fn){return fn()},useEffect(fn,deps){const i=cursor++;if(!(i in states)){states[i]=true;effects.push(fn)}}},render(Component,p){cursor=0;return Component(p)},async effects(){const e=effects;effects=[];for(const fn of e)fn();await new Promise(r=>setImmediate(r))},states}}
function nodes(tree,predicate){const out=[];function walk(n){if(Array.isArray(n)){n.forEach(walk);return}if(n&&typeof n==='object'){if(predicate(n))out.push(n);walk(n.props?.children)}}walk(tree);return out}
const text=n=>nodes(n,x=>typeof x==='object').flatMap(x=>React.Children.toArray(x.props?.children).filter(c=>typeof c==='string'||typeof c==='number')).join(' ');
async function main(){
 const r=result(1001), ls=listings(r), frozen=copy(r), rows=presentation.joinPresentation(r,ls);
 eq(rows.length,1001);eq(presentation.sortRows(rows,presentation.initialSort).map(r=>r.analysis.listingId),r.results.map(r=>r.listingId),'canonical initial order');
 for(const c of presentation.columns.filter(c=>c.sortable))for(const direction of ['asc','desc']){
  const sorted=presentation.sortRows(rows,{column:c.id,direction});eq(new Set(sorted.map(r=>r.analysis.listingId)).size,1001,c.id);
  for(let i=1;i<sorted.length;i++){const a=c.value(sorted[i-1]),b=c.value(sorted[i]);if(a===null)eq(b,null,'nulls last');else if(b!==null)ok(direction==='asc'?a<=b:a>=b,'raw complete sort '+c.id)}
  for(const size of [25,50,100]){const pages=[];for(let page=1;page<=Math.ceil(sorted.length/size);page++){const part=presentation.pageRows(sorted,page,size);ok(part.length<=size);pages.push(...part)}eq(pages.map(r=>r.analysis.listingId),sorted.map(r=>r.analysis.listingId),'page union exact')}
 }
 eq(r,frozen,'source immutable');eq(presentation.sortRows(rows,{column:'pricePerM2',direction:'desc'})[0].analysis.listingId,uuid(1001),'sort before first page');
 const tied=rows.slice(0,5).map((r,i)=>({...r,analysis:{...r.analysis,pricePerM2:1,percentilePosition:50},listing:null})).reverse();for(const dir of ['asc','desc'])eq(presentation.sortRows(tied,{column:'percentilePosition',direction:dir}).map(r=>r.analysis.listingId),[1,2,3,4,5].map(uuid));
 eq(presentation.joinPresentation(r,[ls[2],ls[0],ls[0],{...ls[1],listingId:'extraneous'}]).filter(r=>r.listing).map(r=>r.analysis.listingId),[uuid(3)],'duplicates/extra/missing independent');
 for(const tx of ['sale','rent'])for(const lang of ['en','es'])ok(presentation.listingHref(uuid(1),tx,lang).startsWith(lang==='es'?`/es/${tx==='sale'?'comprar':'alquilar-arrendar'}/anuncio/`:`/en/${tx==='sale'?'buy':'rent-lease'}/listing/`));
 for(const geo of ['province','canton','district'])for(const tx of ['sale','rent'])for(const basis of ['land','construction']){
  const a=result(0,tx,basis,geo),input={request:{question:{version:1,...a.question,geography:{level:geo,officialCode:a.question.geography.officialCode}}},normalization:basis};ok(presentation.matchesSubmission(a,input,a.question.geography.termId));ok(!presentation.matchesSubmission(a,input,'999'));
  input.request.question.filters={semantics:{utility:['8','7','8']},facts:{bedrooms:[{kind:'exact',value:'003.00'},{kind:'interval',interval:{lower:null,upper:'004.0',lowerInclusive:false,upperInclusive:true}},{kind:'category',termId:'9'}]},propertyArea:'under-100m2',constructionArea:'under-50m2'};
  a.question.filters=copy(input.request.question.filters);a.question.filters.semantics.utility=['7','8'];a.question.filters.facts.bedrooms[0].value='3';a.question.filters.facts.bedrooms[1].interval.upper='4';a.question.filters.facts.bedrooms.reverse();ok(presentation.matchesSubmission(a,input,a.question.geography.termId));a.question.filters.facts.bedrooms[1].interval.upperInclusive=false;ok(!presentation.matchesSubmission(a,input,a.question.geography.termId));
 }
 // Real application wrapper and transport, controlled stage boundaries; stage internals have independent regressions.
 let executes=0,projects=0,acquires=0,next=result(),badPresentation=false;
 const appLoad=loader({'lib/phase14-server-discovery.ts':{executePhase14ComparativeDiscovery:async(q,n)=>{executes++;return {q,n}}},'lib/phase14-browser-result.ts':{toPhase14BrowserResult:()=>{projects++;return next}},'lib/phase14-listing-presentation.ts':{getPhase14ListingPresentation:async ids=>{acquires++;eq(ids,next.results.map(r=>r.listingId));if(badPresentation)throw Error('secret');return listings(next)}},'lib/phase14-option-catalog.ts':{readPhase14OptionCatalog:async()=>({state:'unavailable'})}});
 const action=appLoad('lib/comparative-discovery-action.ts');
 for(const code of ['authentication_required','entitlement_required','invalid_request','execution_failed']){next={state:'error',contractVersion:1,code};const out=await action.analyzePhase14Market({request:{},normalization:'land'});eq(out,{analysis:next});eq(acquires,0)}
 next=result(0);eq((await action.analyzePhase14Market({request:{},normalization:'land'})).listings,[]);eq(acquires,0);
 next=result(51);let before=[executes,projects,acquires];let out=await action.analyzePhase14Market({request:{},normalization:'land'});eq([executes,projects,acquires],before.map(x=>x+1));eq(Object.keys(out),['analysis','listings']);badPresentation=true;eq((await action.analyzePhase14Market({request:{},normalization:'land'})).analysis,next);
 for(const extra of ['sort','page','pageSize','columns','userId','entitlement']){const before=executes;eq((await action.analyzePhase14Market({request:{},normalization:'land',[extra]:true})).analysis.code,'invalid_request');eq(executes,before)}
 // Real bounded reader; replace database and established hydration at their external boundary.
 let reads=[],hydrate=0,mode='ok';const db={from(table){eq(table,'listings');let ids,filters=[];const q={select(c){ok(!/description|owner|source|contact|price_millions/.test(c));return q},in(k,v){eq(k,'id');ids=v;ok(v.length<=25);return q},eq(k,v){filters.push([k,v]);return q},then(resolve,reject){reads.push(ids);eq(filters,[['listing_status','active'],['canonical_domain_version',1],['transaction_type','sale']]);let data=ids.map(id=>({id,title:'Title',images:['https://example.invalid/one','https://example.invalid/two'],current_price:.5,currency:'CRC',canonical_domain_version:1,transaction_type:'sale',property_area:200,construction_area:null}));if(mode==='missing')data=data.slice(1);if(mode==='extra')data[0].id='bad';if(mode==='duplicate')data[1]=data[0];return Promise.resolve({data,error:mode==='error'?Error('secret'):null}).then(resolve,reject)}};return q}};
 const reader=loader({'lib/supabase-admin.ts':{supabaseAdmin:db},'lib/canonical-population.ts':{hydrateCanonicalPopulation:async data=>{hydrate++;return data.map(r=>({...r,bedrooms:'3',bathrooms:'1.5',year_built:'2010',province:'Province',canton:'Canton',canonicalEvidence:{private:'secret'}}))}}})('lib/phase14-listing-presentation.ts');
 eq(await reader.getPhase14ListingPresentation([],'sale'),[]);eq(reads.length,0);
 for(const n of [1,24,25,26,50,51,1001]){reads=[];hydrate=0;const p=await reader.getPhase14ListingPresentation(Array.from({length:n},(_,i)=>uuid(i+1)),'sale');eq(p.length,n);eq(reads.length,Math.ceil(n/25));eq(hydrate,Math.ceil(n/25));ok(!JSON.stringify(p).includes('secret'));ok(!JSON.stringify(p).includes('/two'));eq(p[0].price,.5)}
 for(const state of ['extra','duplicate','error']){mode=state;await assert.rejects(()=>reader.getPhase14ListingPresentation([uuid(1),uuid(2)],'sale'));checks++}mode='missing';eq((await reader.getPhase14ListingPresentation([uuid(1),uuid(2)],'sale')).length,1);
 // Actual lossless public option catalog, complete pagination and fail-closed evidence.
 let catalogRows=[],catalogCalls=0,catalogMode='ok';const catalogDb={from(table){eq(table,'ontology_terms');let lo=0,hi=0;const q={select(s,o){ok(s.includes('id::text')&&s.includes('parent_id::text'));eq(o,{count:'exact'});return q},in(k,v){eq(k,'term_type');ok(!v.includes('listings'));return q},order(k){eq(k,'id');return q},range(a,b){lo=a;hi=b;eq(b-a+1,500);return q},then(resolve,reject){catalogCalls++;let data=copy(catalogRows.slice(lo,hi+1));if(catalogMode==='duplicate'&&data.length>1)data[1]=data[0];if(catalogMode==='lossy'&&data.length)data[0].id=Number(data[0].id);if(catalogMode==='empty')data=[];return Promise.resolve({data,count:catalogMode==='drift'&&lo?catalogRows.length+1:catalogRows.length,error:catalogMode==='error'?Error('private'):null}).then(resolve,reject)}};return q}};
 const catalogReader=loader({'lib/supabase.ts':{supabase:catalogDb}})('lib/phase14-option-catalog.ts');
 for(const n of [0,1,499,500,501,1001]){catalogRows=Array.from({length:n},(_,i)=>({id:String(BigInt('9007199254740993')+BigInt(i)),term_type:'property_type',term_name:'Type',term_name_en:'Type',term_name_es:'Tipo',official_code:null,parent_id:null,level:1}));catalogCalls=0;const c=await catalogReader.readPhase14OptionCatalog();eq(c.state,'ready');eq(c.options.length,n);eq(catalogCalls,Math.max(1,Math.ceil(n/500)));if(n)eq(c.options[0].id,'9007199254740993')}
 for(const m of ['duplicate','lossy','empty','drift','error']){catalogMode=m;eq(await catalogReader.readPhase14OptionCatalog(),{state:'unavailable'})}
 // Results component state: table operations only touch local state.
 const hooks=hookHarness(),ui=loader({react:hooks.react})('app/components/Phase14Results.tsx'),p=props(r);let tree=hooks.render(ui.default,p);
 eq(nodes(tree,n=>n.type==='tbody')[0].props.children.length,25);eq(nodes(tree,n=>n.type==='img').length,25);
 let selects=nodes(tree,n=>n.type==='select');selects[0].props.onChange({target:{value:'pricePerM2'}});selects[1].props.onChange({target:{value:'desc'}});tree=hooks.render(ui.default,p);
 eq(nodes(tree,n=>n.type==='tbody')[0].props.children[0].key,uuid(1001));
 selects=nodes(tree,n=>n.type==='select');selects[2].props.onChange({target:{value:'100'}});tree=hooks.render(ui.default,p);eq(nodes(tree,n=>n.type==='img').length,100);
 const nextButton=nodes(tree,n=>n.type==='button'&&n.props.children==='Next')[0];nextButton.props.onClick();tree=hooks.render(ui.default,p);eq(nodes(tree,n=>n.type==='tbody')[0].props.children[0].key,uuid(901));
 nodes(tree,n=>n.type==='select')[0].props.onChange({target:{value:'belowCount'}});tree=hooks.render(ui.default,p);eq(nodes(tree,n=>n.type==='tbody')[0].props.children[0].key,uuid(1));
 const checkbox=nodes(tree,n=>n.type==='input'&&n.props.type==='checkbox')[7];checkbox.props.onChange({target:{checked:false}});tree=hooks.render(ui.default,p);ok(text(tree).includes('column hidden'));eq([executes,projects,acquires],[7,7,2],'table operations no boundary calls');
 const render=loader()('app/components/Phase14Results.tsx');
 for(const language of ['en','es'])for(const n of [0,1,3,1001]){const a=result(n),html=dom.renderToStaticMarkup(React.createElement(render.default,{...props(a),language}));eq((html.match(/<tbody>/g)||[]).length,n?1:0);eq((html.match(/<img /g)||[]).length,Math.min(n,25));ok(html.includes(language==='es'?'Pregunta de mercado':'Market Question'));ok(!html.includes('secret'));if(n)ok(html.includes('aria-sort="ascending"'));}
 const tiedDistribution=result(3);for(const key of ['minimum','p10','p25','median','average','p75','p90','maximum'])tiedDistribution.distribution[key]=10;tiedDistribution.distribution.iqr=0;
 for(const language of ['en','es']){const html=dom.renderToStaticMarkup(React.createElement(render.Phase14Distribution,{result:tiedDistribution,language}));eq((html.match(/left:50%/g)||[]).length,7,'all-tied markers share the exact coordinate');ok(!html.includes('NaN'))}
 // UI hook behavior including actual submission snapshots, failures, double submit and stale unmount.
 const options=[['1','province','1',null],['2','canton','101','1'],['3','district','10101','2'],['4','property_type',null,null],['5','province','2',null]].map(([id,type,code,parentId])=>({id,type,code,parentId,en:type+' EN',es:type+' ES'}));
 let resolveRequest,pendingInput,uiCalls=0;const h=hookHarness(),panel=loader({react:h.react,'lib/comparative-discovery-action.ts':{loadPhase14Options:async()=>({state:'ready',options}),analyzePhase14Market:input=>{uiCalls++;pendingInput=copy(input);return new Promise(r=>resolveRequest=r)}}})('app/components/Phase14Discovery.tsx').default;
 const renderPanel=()=>h.render(panel,{language:'en'});let t=renderPanel();eq(uiCalls,0);await h.effects();t=renderPanel();
 const change=(index,value)=>{nodes(t,n=>n.type==='select')[index].props.onChange({target:{value}});t=renderPanel()};
 change(0,'1');change(1,'2');change(2,'3');change(3,'sale');change(4,'4');change(5,'land');eq(uiCalls,0);
 const submit=()=>nodes(t,n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});submit();submit();eq(uiCalls,1);eq(pendingInput.request.question.geography,{level:'district',officialCode:'10101'});eq(pendingInput.request.ancestorAssertions,{provinceCode:'1',cantonCode:'101'});
 resolveRequest({analysis:result(3,'sale','land','district'),listings:[]});await new Promise(r=>setImmediate(r));t=renderPanel();let committed=nodes(t,n=>typeof n.type==='function'&&n.props.result)[0];ok(committed);eq(committed.props.result.normalization,'land');
 change(5,'construction');eq(nodes(t,n=>typeof n.type==='function'&&n.props.result)[0].props.result.normalization,'land');submit();t=renderPanel();ok(nodes(t,n=>typeof n.type==='function'&&n.props.result).length===1);resolveRequest({analysis:{state:'error',contractVersion:1,code:'execution_failed'}});await new Promise(r=>setImmediate(r));t=renderPanel();ok(nodes(t,n=>typeof n.type==='function'&&n.props.result).length===1);ok(text(t).includes('could not be completed'));
 submit();resolveRequest({analysis:result(0,'sale','construction','district'),listings:[]});await new Promise(r=>setImmediate(r));t=renderPanel();eq(nodes(t,n=>typeof n.type==='function'&&n.props.result)[0].props.result.n,0);
 change(0,'5');eq(nodes(t,n=>n.type==='select')[1].props.value,'');eq(nodes(t,n=>n.type==='select')[2].props.value,'');eq(uiCalls,3);
 // Mismatched success cannot relabel the previous committed result.
 submit();resolveRequest({analysis:result(3,'sale','construction','province'),listings:[]});await new Promise(r=>setImmediate(r));t=renderPanel();eq(nodes(t,n=>typeof n.type==='function'&&n.props.result)[0].props.result.n,0);ok(text(t).includes('could not be completed'));
 change(0,'1');change(3,'rent');submit();eq(pendingInput.request.question.geography.level,'province');eq(pendingInput.request.question.transaction,'rent');resolveRequest({analysis:result(1,'rent','construction','province'),listings:[]});await new Promise(r=>setImmediate(r));t=renderPanel();eq(nodes(t,n=>typeof n.type==='function'&&n.props.result)[0].props.result.unit,'CRC/m²/month');
 change(1,'2');submit();eq(pendingInput.request.question.geography.level,'canton');resolveRequest({analysis:result(1,'rent','construction','canton'),listings:[]});await new Promise(r=>setImmediate(r));t=renderPanel();
 for(const code of ['invalid_request','authentication_required','entitlement_required','execution_failed']){submit();resolveRequest({analysis:{state:'error',contractVersion:1,code}});await new Promise(r=>setImmediate(r));t=renderPanel();ok(nodes(t,n=>n.props?.role==='alert').length===1);eq(nodes(t,n=>typeof n.type==='function'&&n.props.result)[0].props.result.question.geography.level,'canton')}
 const callsBeforeFact=uiCalls;
 // Actual numerical editor: exact/category/interval remain separate, with explicit add/remove.
  // Obtain the real local FactControl through its parent element without exporting a new product API.
 const ph=hookHarness(),pm=loader({react:ph.react,'lib/comparative-discovery-action.ts':{loadPhase14Options:async()=>({state:'ready',options})}})('app/components/Phase14Discovery.tsx');
 let parent=ph.render(pm.default,{language:'en'});await ph.effects();parent=ph.render(pm.default,{language:'en'});
 const Fact=nodes(parent,n=>typeof n.type==='function'&&n.props.dimension==='bedrooms')[0].type;
 let chosen=[];const fp={dimension:'bedrooms',options:[...options,{id:'9',type:'bedrooms',en:'3 or more',es:'3 o más'}],selected:chosen,onChange:v=>{chosen=v;fp.selected=v},language:'en'};
 // Fact belongs to ph's module closure; use a fresh ph state area for this component.
 ph.states.length=0;const renderFact=()=>ph.render(Fact,fp);let ft=renderFact();
 nodes(ft,n=>n.type==='input')[0].props.onChange({target:{value:'3'}});ft=renderFact();nodes(ft,n=>n.type==='button'&&n.props.children==='Add condition')[0].props.onClick();ft=renderFact();eq(chosen,[{kind:'exact',value:'3'}]);
 nodes(ft,n=>n.type==='select')[0].props.onChange({target:{value:'category'}});ft=renderFact();nodes(ft,n=>n.type==='select')[1].props.onChange({target:{value:'9'}});ft=renderFact();nodes(ft,n=>n.type==='button'&&n.props.children==='Add condition')[0].props.onClick();ft=renderFact();eq(chosen[1],{kind:'category',termId:'9'});
 nodes(ft,n=>n.type==='select')[0].props.onChange({target:{value:'interval'}});ft=renderFact();nodes(ft,n=>n.type==='input'&&n.props.inputMode)[1].props.onChange({target:{value:'5'}});ft=renderFact();nodes(ft,n=>n.type==='button'&&n.props.children==='Add condition')[0].props.onClick();ft=renderFact();eq(chosen[2],{kind:'interval',interval:{lower:null,upper:'5',lowerInclusive:false,upperInclusive:false}});
 nodes(ft,n=>n.type==='button'&&n.props.children==='Remove')[0].props.onClick();eq(chosen.length,2);eq(uiCalls,callsBeforeFact,'fact manipulation no execution');
 // Existing AST graph walker treats Server Actions as transport stubs, never browser runtime.
 const graphSource=fs.readFileSync(root+'/scripts/verification/pre14-phase11-boundary.cjs','utf8'),fragment=graphSource.slice(graphSource.indexOf('// Follow runtime'),graphSource.indexOf('const contract =')),graph={};
 vm.runInNewContext(fragment+'\nresult.roots=roots.length;result.modules=visited.size;',{fs,path,cp,root,ts,ok,forbidden:new Set(['lib/phase14-application.ts','lib/phase14-listing-presentation.ts','lib/phase14-option-catalog.ts','lib/phase14-server-discovery.ts','lib/phase14-browser-result.ts']),result:graph});
 console.log(JSON.stringify({status:'PASS',checks,fixtures:[0,1,3,24,25,26,50,51,1001],clientRoots:graph.roots,reachableRuntimeModules:graph.modules,liveIO:false},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1});
