// Offline only: real Step 1 / DTA / authorization modules, deny-all external loader.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),ts=require(root+'/node_modules/typescript');
global.fetch=async()=>{throw Error('Network prohibited in offline verifier')};
let checks=0,calls=[],auth=true,entitled=true,user='user-A',mode='ok';
const ok=(v,m)=>{assert.ok(v,m);checks++},copy=v=>JSON.parse(JSON.stringify(v));
const geos=[{id:'101',parent_id:'9',official_code:'1',term_type:'province',level:1},{id:'102',parent_id:'101',official_code:'101',term_type:'canton',level:2},{id:'103',parent_id:'102',official_code:'10101',term_type:'district',level:3},{id:'104',parent_id:'102',official_code:'10102',term_type:'district',level:3}];
const terms=[['9007199254740993','property_type'],['9007199254740994','property_type'],['3','environment'],['4','environment'],['5','terrain'],['6','utility'],['7','accessibility'],['8','legal_status'],['9','bedrooms'],['10','bathrooms'],['11','parking'],['12','year_built']].map(([id,term_type])=>({id,term_type,level:1,term_name:'label '+id}));
const db={from(table){assert.equal(table,'ontology_terms','population access prohibited');let filters=[],limit=Infinity;const q={select(value,options){assert.equal(options.count,'exact');calls.push({table,select:value});return q},in(k,v){filters.push([k,v]);return q},order(){return q},limit(v){limit=v;return q},retry(){return q},then(resolve,reject){return Promise.resolve().then(()=>{let data=[...geos,...terms].filter(r=>filters.every(([k,v])=>v.includes(r[k]))).map(copy);const isTerm=filters.some(([k])=>k==='id');if(mode==='unknown'&&isTerm)data=[];if(mode==='wrong'&&isTerm)data[0].term_type='terrain';if(mode==='root'&&isTerm)data[0].level=0;if(mode==='label-null'&&isTerm)data[0].term_name=null;if(mode==='duplicate'&&isTerm)data.push(data[0]);if(mode==='bad-parent'&&!isTerm)data.find(r=>r.term_type==='district').parent_id='999';if(mode==='lossy'&&isTerm)data[0].id=Number(data[0].id);return {data:data.slice(0,mode==='capped'?0:limit),count:mode==='count-null'?null:data.length,error:mode==='error'?Error('fake reference failure'):null}}).then(resolve,reject)}};return q},rpc(){throw Error('No admin RPC authorized in this test')}};
const cache=new Map(),allowed=new Set(['lib/phase14-question.ts','lib/phase14-question-commit.ts','lib/geography/dta-request.ts','lib/geography/dta-identity.ts','lib/geography/resolve-dta-geography.ts','lib/market-intelligence-area-ranges.ts','lib/price-meter-authorization.ts']);
function load(file){if(cache.has(file))return cache.get(file).exports;if(!allowed.has(file))throw Error('Unauthorized module '+file);const m={exports:{}};cache.set(file,m);const js=ts.transpileModule(fs.readFileSync(root+'/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const req=name=>{if(name==='server-only')return {};if(name==='node:crypto')return require('node:crypto');let f=name.startsWith('@/')?name.slice(2):path.posix.normalize(path.posix.join(path.posix.dirname(file),name));if(!f.endsWith('.ts'))f+='.ts';if(f==='lib/supabase-admin.ts')return {supabaseAdmin:db};if(f==='lib/supabase-server.ts')return {createServerSupabaseClient:async()=>({auth:{getUser:async()=>{calls.push({auth:true});return {data:{user:auth?{id:user}:null},error:null}}},rpc:async(name,args)=>{assert.equal(name,'current_user_has_entitlement');assert.equal(args.requested_entitlement_slug,'price-m2-intelligence');calls.push({entitlement:true});return {data:entitled,error:null}}})};return load(f)};new Function('module','exports','require',js)(m,m.exports,req);return m.exports}
const api=load('lib/phase14-question-commit.ts'),identity=load('lib/phase14-question.ts');
const base=()=>({question:{version:1,transaction:'sale',geography:{level:'district',officialCode:'10101'},propertyType:{termId:'9007199254740993'}}});
async function commit(input=base()){return api.commitPhase14Question(input)}
async function reject(input,label){await assert.rejects(()=>commit(input),undefined,label);checks++}
async function main(){
 const initial=await commit();ok(initial.question.geography.termId==='103','selected district only');ok(Object.isFrozen(initial)&&Object.isFrozen(initial.question.filters.facts),'deep immutability');api.assertPhase14ExecutionEnvelope(initial);checks++;
 for(const [level,code,id]of[['province','1','101'],['canton','101','102'],['district','10101','103']])for(const transaction of ['sale','rent']){const x=base();x.question.geography={level,officialCode:code};x.question.transaction=transaction;const r=await commit(x);ok(r.question.geography.termId===id&&r.question.geography.level===level&&r.question.geography.officialCode===code,'geographic identity '+level+transaction)}
 for(const key of ['version','transaction','geography','propertyType']){const x=base();delete x.question[key];await reject(x,'missing '+key)}
 for(const transaction of [null,[],['sale','rent'],'buy','sale,rent',1]){const x=base();x.question.transaction=transaction;await reject(x,'transaction')}
 for(const type of [null,[],{termId:9007199254740993},{termId:'0'},{termId:'-1'},{termId:'01'},{termId:'9223372036854775808'},{termId:'House'},{termId:'9999'},{termId:'3'}]){const x=base();x.question.propertyType=type;await reject(x,'type')}
 for(const geography of [{level:'country',officialCode:'CR'},{level:'district',officialCode:10101},{level:'district',officialCode:'Escazu'},{level:'canton',officialCode:'1'},{level:'district',officialCode:'99999'},null]){const x=base();x.question.geography=geography;await reject(x,'geography')}
 const ancestor=base();ancestor.ancestorAssertions={provinceCode:'1',cantonCode:'101'};ok(identity.equalPhase14Questions(initial.question,(await commit(ancestor)).question),'ancestor equality');ancestor.ancestorAssertions.cantonCode='102';await reject(ancestor,'conflicting ancestor');
 for(const filters of [undefined,{}, {semantics:{},facts:{}},{semantics:{environment:[]},facts:{year_built:[]}}]){const x=base();if(filters!==undefined)x.question.filters=filters;ok(identity.equalPhase14Questions(initial.question,(await commit(x)).question),'empty optional equality')}
 const x=base();x.question.filters={semantics:{legal_status:['8'],environment:['4','3','4'],terrain:['5'],utility:['6'],accessibility:['7']}};const one=await commit(x);x.question.filters.semantics.environment=['3','4'];ok(identity.equalPhase14Questions(one.question,(await commit(x)).question),'semantic order/dedup');ok(one.question.filters.semantics.environment.join(',')==='3,4','semantic sorted');x.question.filters.semantics.environment=['5'];await reject(x,'wrong semantic dimension');
 for(const [dim,value]of[['bedrooms','0'],['bathrooms','0.5'],['parking','0'],['year_built','9999'],['bedrooms','900719925474099312345']]){const v=base();v.question.filters={facts:{[dim]:[{kind:'exact',value}]}};ok((await commit(v)).question.filters.facts[dim][0].value===value,'valid exact '+dim)}
 for(const [dim,values]of Object.entries({bedrooms:['-1','1.5','NaN','Infinity','1e3',' 3','3.',3],parking:['-1','0.5'],bathrooms:['0','-1'],year_built:['0','10000','2018.5']}))for(const value of values){const v=base();v.question.filters={facts:{[dim]:[{kind:'exact',value}]}};await reject(v,'invalid exact '+dim)}
 const fact=(c,dim='bedrooms')=>{const v=base();v.question.filters={facts:{[dim]:[c]}};return v};
 const exact=await commit(fact({kind:'exact',value:'3'}));ok(identity.equalPhase14Questions(exact.question,(await commit(fact({kind:'exact',value:'0003.000'}))).question),'lossless decimal canonicalization');
 for(const [dim,termId]of[['bedrooms','9'],['bathrooms','10'],['parking','11'],['year_built','12']])ok((await commit(fact({kind:'category',termId},dim))).question.filters.facts[dim][0].kind==='category','category '+dim);
 await reject(fact({kind:'category',termId:'10'}),'wrong category dimension');
 const interval=(lower,upper,lowerInclusive=true,upperInclusive=true)=>({kind:'interval',interval:{lower,upper,lowerInclusive,upperInclusive}});
 const single=await commit(fact(interval('3','3')));ok(!identity.equalPhase14Questions(exact.question,single.question),'singleton remains interval');
 const category=await commit(fact({kind:'category',termId:'9'}));ok(!identity.equalPhase14Questions(category.question,exact.question),'exact/category distinct');
 for(const c of [interval(null,'3',false,true),interval('3',null,true,false),interval('1','3',false,false)])ok((await commit(fact(c))).question.filters.facts.bedrooms[0].kind==='interval','valid interval');
 for(const c of [interval(null,null,false,false),interval(null,'3',true,true),interval('3',null,true,true),interval('4','3'),interval('3','3',false,true),interval('3','3',true,false),interval('1.5','3'),interval('1','3','true',true)])await reject(fact(c),'bad interval');
 await reject(fact(interval('1','2',false,false)),'empty integer interval');await reject(fact(interval(null,'0',false,false)),'empty nonnegative interval');await reject(fact(interval('9999',null,false,false),'year_built'),'empty year domain');
 const first=await commit(fact(interval('1','3')));ok(!identity.equalPhase14Questions(first.question,(await commit(fact(interval('1','3',false,true)))).question),'inclusivity identity');ok(!identity.equalPhase14Questions(first.question,(await commit(fact(interval('1','4')))).question),'endpoint identity');
 const alternatives=base();alternatives.question.filters={facts:{bedrooms:[{kind:'category',termId:'9'},{kind:'exact',value:'3'},{kind:'exact',value:'3.0'}]}};const ordered=await commit(alternatives);alternatives.question.filters.facts.bedrooms.reverse();ok(identity.equalPhase14Questions(ordered.question,(await commit(alternatives)).question),'constraint set order');ok(ordered.question.filters.facts.bedrooms.length===2,'constraint duplicates');
 const areas=load('lib/market-intelligence-area-ranges.ts');for(const [key,options] of [['propertyArea',areas.PROPERTY_AREA_RANGE_OPTIONS],['constructionArea',areas.CONSTRUCTION_AREA_RANGE_OPTIONS]]){for(const option of options){const v=base();v.question.filters={[key]:option.value};ok((await commit(v)).question.filters[key]===option.value,'area '+option.value)}const v=base();v.question.filters={[key]:'toString'};await reject(v,'invalid area key')}
 for(const key of ['price_range','road_distance','propertyBasis','normalizationBasis','analyticalCRC','pricePerM2','ranking','similarityScore','criterion','populationLimit','sample','cursor','locale','label','subjectListingId','peerPopulation','comparableDefinition','authorization','executionId','authenticatedUserId','classificationRuleId']){const v=base();v.question[key]='forged';await reject(v,'forbidden '+key)}
 for(const value of [null,'',[],{facts:null},{semantics:null},{facts:{bedrooms:null}},{facts:{bedrooms:[{kind:'exact',value:'3',extra:true}]}},{facts:{bad:[]}},{semantics:{environment:[3]}},{propertyArea:null}]){const v=base();v.question.filters=value;await reject(v,'malformed optional')}
 const sparse=base();sparse.question.filters={semantics:{environment:new Array(1)}};await reject(sparse,'sparse selection');const accessor=base();Object.defineProperty(accessor.question,'version',{enumerable:true,get(){throw Error('getter must not execute')}});await reject(accessor,'accessor');
 for(const mutate of [q=>q.transaction='rent',q=>q.geography.officialCode='10102',q=>q.propertyType.termId='9007199254740994',q=>q.filters={facts:{bedrooms:[{kind:'exact',value:'3'}]}}]){const v=base();mutate(v.question);ok(!identity.equalPhase14Questions(initial.question,(await commit(v)).question),'changed question')}
 for(const m of ['unknown','wrong','root','label-null','duplicate','bad-parent','lossy','capped','count-null','error']){mode=m;await reject(base(),'reference failure '+m)}mode='ok';
 for(const state of ['anonymous','unentitled']){auth=state!=='anonymous';entitled=false;calls=[];await reject(base(),state);ok(!calls.some(c=>c.table),'denial before reference access')}auth=entitled=true;
 calls=[];const authorized=await commit();ok(calls[0].auth&&calls[1].entitlement&&calls.slice(2).every(c=>c.table==='ontology_terms'),'real auth ordering');user='user-B';const another=await commit();ok(identity.equalPhase14Questions(authorized.question,another.question),'user excluded from question');ok(authorized.executionId!==another.executionId&&another.authenticatedUserId==='user-B','separate attempts and identities');
 assert.throws(()=>api.assertPhase14ExecutionEnvelope(copy(authorized)));checks++;assert.throws(()=>identity.serializePhase14Question(copy(authorized.question)));checks++;
 // Reference batching/completeness and operational rejection: never truncate intent.
 const many=Array.from({length:26},(_,i)=>({id:String(1000+i),term_type:'environment',level:1,term_name:'option'}));terms.push(...many);
 const batched=base();batched.question.filters={semantics:{environment:many.map(t=>t.id)}};calls=[];
 const batchResult=await commit(batched);ok(batchResult.question.filters.semantics.environment.length===26,'all reference selections retained');ok(calls.filter(c=>c.select==='id::text,term_type,level,term_name').length===2,'27 term references use two bounded reads');
 const oversized=base();oversized.question.filters={semantics:{environment:Array(257).fill('3')}};await reject(oversized,'oversized selections fail, no truncation');
 await reject(fact({kind:'exact',value:'1'.repeat(1025)}),'oversized decimal');
 for(const key of ['authorization','executionEnvelope','userId']){const v=base();v[key]={trusted:true};await reject(v,'outer authority rejected')}
 const badInput=base();badInput.question.filters={facts:{bedrooms:[{kind:'interval',interval:{lower:'1',upper:'3',lowerInclusive:true,upperInclusive:true,label:'EN'}}]}};await reject(badInput,'nested unknown field');
 const forged=base();Object.defineProperty(forged.question,Symbol('authority'),{value:true});await reject(forged,'symbol key');
 calls=[];await reject({question:{version:1}},'invalid has no authority work');ok(calls.length===0,'malformed request fails before any I/O');
 const captured=base(),prepared=identity.preparePhase14Question(captured);captured.question.transaction='rent';ok(prepared.question.transaction==='sale','input mutation detached');
 // Inspect real runtime client graph, following re-exports/dynamic imports/require; server actions are RPC boundaries.
 const graphSource=fs.readFileSync(root+'/scripts/verification/pre14-phase11-boundary.cjs','utf8');const fragment=graphSource.slice(graphSource.indexOf('// Follow runtime'),graphSource.indexOf('const contract ='));
 const graph={};vm.runInNewContext(fragment+'\nresult.roots=roots.length;result.modules=visited.size;', {fs,path,cp,root,ts,ok,forbidden:new Set(['lib/phase14-question.ts','lib/phase14-question-commit.ts']),result:graph});
 const contractAst=ts.createSourceFile('contract.ts',fs.readFileSync(root+'/lib/phase14-question-contract.ts','utf8'),ts.ScriptTarget.Latest,true);ok(contractAst.statements.every(ts.isTypeAliasDeclaration),'browser contract types only');
 console.log(JSON.stringify({status:'PASS',checks,clientRoots:graph.roots,reachableRuntimeModules:graph.modules,protectedViolations:0,liveIO:false,populationReads:0,loadedRealModules:[...cache.keys()]},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1});
