const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');const root=path.resolve(__dirname,'../..'),ts=require(root+'/node_modules/typescript');let checks=0;const ok=(v,l)=>{assert.ok(v,l);checks++};const cache=new Map();let mode='allow',loads=0,analyses=0,outcomeCalls=0,synthesisCalls=0,events=[];
class AuthError extends Error{};class EntitlementError extends Error{};
const mocks={'next/server':{NextResponse:{json:(body,init={})=>({body,status:init.status??200})}},'@/lib/price-meter-authorization':{PriceMeterComparableAuthenticationError:AuthError,PriceMeterComparableAuthorizationError:EntitlementError,async authorizePriceMeterIntelligenceExecution(){events.push('authorize');if(mode==='auth')throw new AuthError();if(mode==='entitlement')throw new EntitlementError();if(mode==='authority-error')throw Error('authority failed')}},'@/lib/price-meter-observation-loader':{async loadPriceMeterObservations(filters){loads++;events.push('load');assert.equal(filters.province,'3');assert.equal(filters.canton,'304');if(mode==='load-error')throw Error('load failed');return {observations}}}};
function load(rel){rel=path.resolve(root,rel);if(cache.has(rel))return cache.get(rel).exports;const m={exports:{}};cache.set(rel,m);vm.runInNewContext(ts.transpileModule(fs.readFileSync(rel,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,require(k){if(k==='server-only')return{};if(mocks[k])return mocks[k];if(k.startsWith('@/lib/price-meter-')||['@/lib/numerical-distribution','@/lib/market-intelligence-area-ranges'].includes(k))return load(k.slice(2)+'.ts');if(k.startsWith('.'))return load(path.resolve(path.dirname(rel),k)+'.ts');throw Error('Unexpected dependency '+k)},console:{error(){}}},{filename:rel});return m.exports}
const identity=load('lib/price-meter-identity.ts'),builder=load('lib/price-meter-observation-builder.ts');
const observations=builder.buildPriceMeterObservations(Array.from({length:16},(_,i)=>{const listing={id:'x'+i,transaction_type:'sale',currency:'CRC',current_price:100000+i*10000,property_type:'house',property_area:200+i*250,construction_area:70+i*30,canonicalGeography:{province:{id:'1'},canton:{id:'2'},district:{id:String(3+i%2),term_name:'District '+i%2},complete:true}};return {...listing,analyticalIdentity:identity.resolvePriceMeterAnalyticalIdentity(listing,{analyticalDate:'2026-09-19',fxIdentity:null})}}));
const analyzer=load('lib/price-meter-cross-dimensional-analyzer.ts'),analyze=analyzer.analyzePriceMeterCrossDimensionalRelationship;analyzer.analyzePriceMeterCrossDimensionalRelationship=(args)=>{analyses++;events.push('analyze');if(mode==='calculation-error')throw Error('calculation failed');return analyze(args)};
const outcomeModule=load('lib/price-meter-cross-dimensional-outcomes.ts'),evaluate=outcomeModule.evaluatePriceMeterCrossDimensionalOutcomes;
outcomeModule.evaluatePriceMeterCrossDimensionalOutcomes=(e)=>{outcomeCalls++;events.push('outcomes');if(mode==='outcome-error')throw Error('outcome failed');return evaluate(e)};
const synthesisModule=load('lib/price-meter-cross-dimensional-synthesis.ts'),synthesize=synthesisModule.buildPriceMeterCrossDimensionalSynthesis;
synthesisModule.buildPriceMeterCrossDimensionalSynthesis=(args)=>{synthesisCalls++;events.push('synthesis');if(mode==='synthesis-error')throw Error('synthesis failed');return synthesize(args)};
const route=load('app/api/price-meter/cross-dimensional/route.ts'),questions=load('lib/price-meter-cross-dimensional-question.ts').PRICE_METER_CROSS_DIMENSIONAL_QUESTIONS;
const filters={province:'3',canton:'304',transaction_type:'sale',property_type:'house'};
async function call(body){loads=0;analyses=0;outcomeCalls=0;synthesisCalls=0;events=[];return route.POST({async json(){events.push('body');return body}})}
(async()=>{
const base={questionKey:questions[0].key,filters,cohortKey:'improvedLandNormalized'};
for(const [failure,status] of [['auth',401],['entitlement',403],['authority-error',503]]){mode=failure;const result=await call(base);ok(result.status===status,'authority status '+failure);ok(loads===0&&analyses===0&&outcomeCalls===0&&synthesisCalls===0&&events.join(',')==='authorize','denied before body/acquisition '+failure)}
mode='allow';for(const body of [null,{}, {...base,questionKey:'invented'}, {...base,cohortKey:'invented'}, ...['province','canton','property_type','transaction_type'].map(k=>({...base,filters:{...filters,[k]:undefined}}))]){const result=await call(body);ok(result.status===400,'invalid identity rejected');ok(loads===0&&analyses===0&&outcomeCalls===0&&synthesisCalls===0,'invalid identity never loads')}
for(const q of questions){const result=await call({...base,questionKey:q.key});ok(result.status===200,'authorized question '+q.key);ok(loads===1&&analyses===1&&outcomeCalls===1&&synthesisCalls===1,'one request one load one calculation '+q.key);ok(events.join(',')==='authorize,body,load,analyze,outcomes,synthesis','authorization precedes bounded work');ok(result.body.question.key===q.key,'only requested question returned')}
for(const failure of ['load-error','calculation-error','outcome-error','synthesis-error']){mode=failure;const result=await call(base);ok(result.status===500,'failure returned');ok(loads===1&&analyses===(failure==='load-error'?0:1),'no recursive retry '+failure);ok(outcomeCalls===(['outcome-error','synthesis-error'].includes(failure)?1:0)&&synthesisCalls===(failure==='synthesis-error'?1:0),'failed stage stops completion '+failure)}
ok(!('GET' in route),'GET/navigation cannot execute');console.log('S9 PHASE11 CHECKS',checks,'AUTHORIZED QUESTIONS',questions.length)
})().catch(e=>{console.error(e);process.exitCode=1});
