'use client'
import {useEffect,useRef,useState} from 'react'
import {executeAskingAreaRatio,loadAreaRatioOptions} from '@/lib/asking-area-ratio-action'
import {ratioTitle,ratioQuestion,parseRatioQuestion,type RatioQuestion,type RatioResponse} from '@/lib/asking-area-ratio-contract'
import AnalysisActions from '../AnalysisActions'
import styles from './workspace.module.css'
type Success=Extract<RatioResponse,{question:RatioQuestion}>
const blank={transaction:'',geography:{level:'canton',termId:''},propertyType:'',propertyArea:{min:'',max:''},constructionArea:{min:'',max:''}}
function restore(s?:string){try{return s?parseRatioQuestion(JSON.parse(s)):blank}catch{return blank}}
export default function RatioWorkspace({language,serialized}:{language:'en'|'es';serialized?:string}){
 const es=language==='es',[draft,setDraft]=useState(()=>restore(serialized)),[committed,setCommitted]=useState<Success|null>(null),[editing,setEditing]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[catalog,setCatalog]=useState<Awaited<ReturnType<typeof loadAreaRatioOptions>>|null>(null)
 const lock=useRef(false),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);useEffect(()=>()=>{generation.current++},[]);useEffect(()=>{if(committed)heading.current?.focus()},[committed])
 const text=(en:string,esText:string)=>es?esText:en
 async function apply(e:React.FormEvent){e.preventDefault();if(lock.current)return;let q:RatioQuestion;try{q=parseRatioQuestion(draft)}catch{setError(text('Select one transaction, geography and Property Type, and four valid inclusive bounds.','Selecciona una transacción, geografía y tipo de propiedad, y cuatro límites inclusivos válidos.'));return}
 lock.current=true;setBusy(true);setError('');const ticket=++generation.current
 try{const r=await executeAskingAreaRatio(q);if(ticket!==generation.current)return;if('access'in r){setCommitted(null);setError(text('Authorized access is required.','Se requiere acceso autorizado.'))}else if('error'in r)setError(text('Analysis unavailable. Prior evidence is unchanged.','Análisis no disponible. La evidencia anterior no cambia.'));else{setCommitted(r);setEditing(false)}}catch{if(ticket===generation.current)setError(text('Analysis unavailable. Prior evidence is unchanged.','Análisis no disponible. La evidencia anterior no cambia.'))}finally{if(ticket===generation.current){lock.current=false;setBusy(false)}}}
 const options=catalog?.state==='ready'?catalog.options:[],format=(v:number)=>new Intl.NumberFormat(es?'es-CR':'en-US',{maximumSignificantDigits:6}).format(v)
 const reasons:Record<string,[string,string]>={covariance_unavailable:['Uncertainty could not be resolved for this cohort','No se pudo resolver la incertidumbre para esta cohorte'],insufficient_observations:['Insufficient residual degrees of freedom','Grados de libertad residuales insuficientes'],insufficient_variation:['Insufficient observed area variation','Variación observada de áreas insuficiente'],rank_deficiency:['The two area relationships cannot be separated','No se pueden separar las dos relaciones de área'],numerical_instability:['Numerically unresolved relationship','Relación numéricamente no resuelta'],degenerate_uncertainty:['Uncertainty cannot be established from this fit','La incertidumbre no se puede establecer con este ajuste'],ratio_not_finitely_identified:['The ratio has no established finite interval','La razón no tiene un intervalo finito establecido'],ratio_uncertainty_exceeds_policy:['Ratio uncertainty exceeds the approved 25% tolerance','La incertidumbre de la razón supera la tolerancia aprobada del 25%'],influence_stability_not_certified:['Stability under removal of one or two observations is not certified','No se certificó la estabilidad al retirar una o dos observaciones']}
 return <section className={styles.workspace} style={{minWidth:0,overflowWrap:'anywhere'}}><header><p className={styles.eyebrow}>{text('Cohort-specific relationship','Relación específica de la cohorte')}</p><h2>{ratioTitle[language]}</h2><p className={styles.question}>{ratioQuestion[language]}</p></header>
 <form className={styles.inputs} onSubmit={apply} hidden={!editing}><fieldset disabled={busy} style={{minWidth:0}}><legend>{text('Define the market question','Define la pregunta del mercado')}</legend>
 <button type="button" onClick={async()=>{try{setCatalog(await loadAreaRatioOptions())}catch{setError(text('Market options unavailable','Opciones del mercado no disponibles'))}}}>{text('Load market options','Cargar opciones del mercado')}</button>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,240px),1fr))',gap:16}}>
 <label>{text('Transaction','Transacción')}<select required value={draft.transaction} onChange={e=>setDraft({...draft,transaction:e.target.value})}><option value="">—</option><option value="sale">{text('Sale','Venta')}</option><option value="rent">{text('Monthly asking rent','Alquiler mensual de oferta')}</option></select></label>
 <label>{text('Geographic level','Nivel geográfico')}<select value={draft.geography.level} onChange={e=>setDraft({...draft,geography:{level:e.target.value,termId:''}})}>{['province','canton','district'].map((g,i)=><option key={g} value={g}>{es?['Provincia','Cantón','Distrito'][i]:g}</option>)}</select></label>
 <label>{text('Canonical geography','Geografía canónica')}<select required value={draft.geography.termId} onChange={e=>setDraft({...draft,geography:{...draft.geography,termId:e.target.value}})}><option value="">—</option>{options.filter(o=>o.type===draft.geography.level).map(o=><option key={o.id} value={o.id}>{o[language]} ({o.code})</option>)}</select></label>
 <label>{text('Property Type','Tipo de propiedad')}<select required value={draft.propertyType} onChange={e=>setDraft({...draft,propertyType:e.target.value})}><option value="">—</option>{options.filter(o=>o.type==='property_type').map(o=><option key={o.id} value={o.id}>{o[language]}</option>)}</select></label>
 {(['propertyArea','constructionArea'] as const).flatMap((dimension,i)=>(['min','max'] as const).map((bound,j)=><label key={dimension+bound}>{(es?['Área del terreno','Área de construcción']:['Property Area','Construction Area'])[i]} · {(es?['mínimo inclusivo','máximo inclusivo']:['inclusive minimum','inclusive maximum'])[j]} (m²)<input required inputMode="decimal" value={draft[dimension][bound]} onChange={e=>setDraft({...draft,[dimension]:{...draft[dimension],[bound]:e.target.value}})}/></label>))}</div>
 <p>{text('Improved Property · exact measurements only. Edits do not run analysis.','Propiedad mejorada · solo medidas exactas. Editar no ejecuta el análisis.')}</p><button className={styles.apply} type="submit">{busy?text('Analyzing…','Analizando…'):text('Analyze','Analizar')}</button></fieldset></form>
 {error&&<p role="alert">{error}</p>}
 <div aria-live="polite" aria-busy={busy}>{committed&&<section className={styles.evidence}><h3 ref={heading} tabIndex={-1}>{committed.evidence.state==='established'?text('Established relationship ratio','Razón de relación establecida'):text('Not established','No establecido')}</h3>
 {editing&&<p>{text('Evidence belongs to the last committed question.','La evidencia corresponde a la última pregunta ejecutada.')}</p>}
 <p>{committed.marketLabel[language]} · {committed.propertyTypeLabel[language]} · {committed.question.transaction==='sale'?text('Sale','Venta'):text('Monthly asking rent','Alquiler mensual de oferta')} · n = {committed.evidence.n}</p>
 <p>{text('Property Area','Área del terreno')}: [{committed.question.propertyArea.min}, {committed.question.propertyArea.max}] m² · {text('Construction Area','Área de construcción')}: [{committed.question.constructionArea.min}, {committed.question.constructionArea.max}] m²</p>
 {committed.evidence.state==='established'?<dl><dt>βC / βL</dt><dd className={styles.ratio}>{format(committed.evidence.ratio)}</dd><dt>{text('Approximate nominal 95% ratio interval','Intervalo aproximado nominal del 95% de la razón')}</dt><dd>[{format(committed.evidence.interval.lower)}, {format(committed.evidence.interval.upper)}]</dd><dt>βL · {committed.question.transaction==='rent'?text('CRC/m²/month','CRC/m²/mes'):'CRC/m²'}</dt><dd>{format(committed.evidence.coefficients.propertyArea)}</dd><dt>βC · {committed.question.transaction==='rent'?text('CRC/m²/month','CRC/m²/mes'):'CRC/m²'}</dt><dd>{format(committed.evidence.coefficients.constructionArea)}</dd></dl>:<ul>{committed.evidence.reasons?.map(r=><li key={r}>{reasons[r]?.[es?1:0]??text('Evidence unavailable','Evidencia no disponible')}</li>)}</ul>}
 <p>{text('A descriptive ratio of simultaneous fitted asking-price slopes within this exact cohort—not property value or causal contributions. Coefficient signs are preserved.','Una razón descriptiva de pendientes simultáneas ajustadas del precio de oferta dentro de esta cohorte exacta; no es valor de la propiedad ni contribución causal. Se conservan los signos de los coeficientes.')}</p>
 <p>{committed.analyticalDate} · CRC · {committed.fx?`BCCR USD → CRC ${committed.fx.rate} (${committed.fx.effectiveDate})`:text('No FX conversion required','No se requiere conversión cambiaria')}</p>
 <p>{text('Excluded for unavailable eligible monetary evidence','Excluidos por falta de evidencia monetaria elegible')}: {committed.excluded}</p>
 <details><summary>{text('Supporting evidence','Evidencia de respaldo')}</summary>{(['L','C'] as const).map((key,i)=>{const variation=committed.evidence.diagnostics?.variation as {L:{min:number;max:number};C:{min:number;max:number}}|undefined;return variation?<p key={key}>{(es?['Área del terreno observada','Área de construcción observada']:['Observed Property Area','Observed Construction Area'])[i]}: [{format(variation[key].min)}, {format(variation[key].max)}] m²</p>:null})}{(['df','rSquared','adjustedRSquared','residualScale','condition','maxLeverage','relativeIntervalDeviation','relativeInfluence'] as const).map((key,i)=>{const value=committed.evidence.diagnostics?.[key];return <p key={key}>{(es?['Grados de libertad residuales','R² descriptivo','R² ajustado','Escala residual (CRC)','Condición numérica','Apalancamiento máximo','Desviación relativa del intervalo','Límite relativo de influencia']:['Residual degrees of freedom','Descriptive R²','Adjusted R²','Residual scale (CRC)','Numerical condition','Maximum leverage','Relative interval deviation','Relative influence bound'])[i]}: {typeof value==='number'?format(value):text('Not established','No establecido')}</p>})}</details>
 <button type="button" disabled={busy} onClick={()=>{setDraft(committed.question);setEditing(true)}}>{text('Modify','Modificar')}</button>
 <AnalysisActions key={JSON.stringify(committed)} engineType="price-meter" language={language} filters={{analysis_question:'asking-area-ratio',ratio_request:JSON.stringify(committed.question)}} result={committed} defaultName={ratioTitle[language]}/>
 </section>}</div>
 <details className={styles.method}><summary>{text('Methodology','Metodología')}</summary><p>P = α + βL L + βC C + ε</p><p>{text('Exact listing-level areas and asking amounts enter one raw-scale linear model with an intercept. HC3 covariance and approximate nominal 95% Fieller-type inference assess the coefficient ratio. Interval deviation and certified one/two-observation deletion change must each remain within the approved 25% product tolerance. These tolerances are policies, not universal statistical constants.','Las áreas exactas y los importes de oferta de cada anuncio entran en un modelo lineal con intercepto. La covarianza HC3 y la inferencia aproximada nominal del 95% de tipo Fieller evalúan la razón. La desviación del intervalo y el cambio certificado al retirar una o dos observaciones deben permanecer dentro de la tolerancia aprobada del 25%. Son políticas, no constantes estadísticas universales.')}</p><p>{text('This describes a fitted relationship in the selected cohort, not value or causation. HC3 does not resolve listing dependence, measurement error, or omitted characteristics. Complete acquisition does not prove complete market coverage. No observations are removed to obtain a result. No automatic geographic or Property Type broadening.','Se describe una relación ajustada en la cohorte seleccionada, no valor ni causalidad. HC3 no resuelve la dependencia entre anuncios, errores de medición ni características omitidas. La adquisición completa no prueba cobertura completa del mercado. No se eliminan observaciones para obtener un resultado ni se amplía automáticamente la geografía o el tipo de propiedad.')}</p></details>
 </section>
}
